### ISSUE TITLE
try Enno's new Kafka 2.4 branch

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1024]
@ennru writes:

> FYI just started to warm up my Kafka with sbt branch. Kafka just released 2.4.0…
> I force pushed my latests sbt build for Kafka to my branch now.

I should give It a try

**Comment by SethTisue** [comment]
not sure whether to target both the 2.12.x and 2.13.x builds for this change, or leave 2.12.x alone and only worry about 2.13.x

**Comment by ennru** [comment]
Doing it for Scala 2.13 would be enough.
We should maybe PR the retirement of Scala-logging to Kafka so they can start looking into Scala 3...

**Comment by SethTisue** [comment]
PR: #1032

**Comment by SethTisue** [comment]
green :+1:
