### ISSUE TITLE
Add the current shapeless release to the community build

### ISSUE THREAD

**Issue by milessabin** [scala/community-builds#105]
Current release is 2.2.2 ... will be at least 2.2.3 by the time this ticket is closed.

**Comment by SethTisue** [comment]
I'm on it... it might take a while since I'll have to ramp up on dbuild first and also deal with an existing sbt-web-related failure.

**Comment by SethTisue** [comment]
Note to self: look out for specs2's dependency on shapeless 2.1.0.

**Comment by adriaanm** [comment]
I'd suggest building shapeless in a separate space, like i did to keep specs2_24 and specs2_36 separate.

**Comment by milessabin** [comment]
Current shapeless master is green with 2.12.0-M2 ... I'll mostly likely publish a 2.2.5 fairly shortly.

I looked in the main configuration for the specs2 "separate space" setup but couldn't find it ... if someone can point me in the direction of an example I'll put together a PR.

**Comment by milessabin** [comment]
FYI ... I've just published shapeless-2.2.5 with support for 2.12.0-M2.

**Comment by SethTisue** [comment]
Thanks for the heads up. I am currently working on getting a 2.11.x community build going on JDK 8. Once that's done, I'll get back to the 2.12 community build.

**Comment by SethTisue** [comment]
now done for 2.12: https://github.com/scala/community-builds/pull/121

still working on 2.11. (the Shapeless part is "done", but there are some only indirectly related failures I have to address before the changes can be merged.)

**Comment by milessabin** [comment]
Awesome thanks! :-)

**Comment by SethTisue** [comment]
now done for 2.11.x-jdk6: https://github.com/scala/community-builds/pull/141

TODO: 2.11.x-jdk8

**Comment by milessabin** [comment]
Thanks!

**Comment by SethTisue** [comment]
2.11.x-JDK 8 green build (except for a few non-Shapeless-related failures): https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/59/console

this shows that the merge of #141 was successful, so this is done!

the gears of the community build grind slowly, but they grind exceedingly fine...
