### ISSUE TITLE
upgrade to newer dbuild 0.9.3+

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#108]
this is not pressing, but presumably we should upgrade eventually

a previous attempt to upgrade from 0.9.1 to 0.9.2 went awry; gory details at https://github.com/scala-ide/uber-build/pull/64 . as of June 2015, there is no 0.9.3 release

**Comment by cunei** [comment]
I would recommend 0.9.3-M3; despite the "M3", it should be fully stable.

**Comment by SethTisue** [comment]
@cunei are there release notes for 0.9.2 and 0.9.3-M3?

**Comment by cunei** [comment]
@SethTisue Not as such; there is of course the commit log. The updated documentation pages are at https://github.com/typesafehub/dbuild/tree/v0.9.3-M3/docs/src/sphinx
At this point I could promote 0.9.3-M3 to 0.9.3-final, publish dbuild, update the website, and collect the release notes. Friday is a holiday in the US, but not in Switzerland: I should be able to take care of this matter then. @jsuereth

**Comment by SethTisue** [comment]
0.9.3 is out ([release notes](https://github.com/typesafehub/dbuild/pull/174))

**Comment by adriaanm** [comment]
I [tried 0.9.3](https://github.com/adriaanm/community-builds/commit/592055dd5562d4b47446e39dbd693278f481bf13) but it [fails](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/11/) because of https://github.com/typesafehub/config/issues/160. /cc @cunei 

I'm not sure, but it looks like the config should be accepted, and the error message for https://github.com/typesafehub/config/issues/160 is a bit overzealous. We need this construct to work around https://github.com/typesafehub/dbuild/issues/144

**Comment by SethTisue** [comment]
another reason to upgrade is to get the fix for https://github.com/typesafehub/dbuild/issues/175, except we'd actually need 0.9.4 published in order to get that fix, since it came after 0.9.3

that issue prevents dbuild from working at all locally, since sbt plugins can't be found. (I suspect it only works on Jenkins because the plugin artifacts are in the artifact cache we use there.)

**Comment by SethTisue** [comment]
actually running locally works fine as long as you run with `-n` instead of `-l`

regardless, we should be on the latest dbuild, if only to help dogfood it for RP

**Comment by SethTisue** [comment]
0.9.4 is out and includes a better default repo list.

**Comment by SethTisue** [comment]
once https://github.com/scala/community-builds/issues/185 is fixed, we'll be free to upgrade to 0.9.4 afaict

**Comment by SethTisue** [comment]
fixed for 2.11.x-jdk8 (and 2.12, once I merge it forward) by https://github.com/scala/community-builds/pull/189 . I don't think it's necessary to mess with 2.11.x(-jdk6)
