### ISSUE TITLE
re-enable Spray test suite

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#110]
figure out why https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/33/console
failed spray.httpx.unmarshalling.ScalaXmlUnmarshallerSpec

**Comment by jrudolph** [comment]
In v1.3.3 we introduced a test (and some configuration changes) to guard against XXE attacks in spray/spray#1024. See here:

https://github.com/spray/spray/blob/master/spray-httpx/src/test/scala/spray/httpx/unmarshalling/ScalaXmlUnmarshallerSpec.scala

In [the failing run](https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/34/console) the errors are these:

```
[spray] [info] The ScalaXml (NodeSeq) unmarshaller should
[spray] [info] + unmarshal XML bodies
[spray] [info] x parse XML bodies without loading in a related schema
[spray] [error]    'MalformedContent(,Some(java.lang.NullPointerException))' is incorrect:  (ScalaXmlUnmarshallerSpec.scala:44)
[spray] [info] 
[spray] [info] x parse XML bodies without loading in a related schema from a parameter
[spray] [error]    'MalformedContent(,Some(java.lang.NullPointerException))' is incorrect:  (ScalaXmlUnmarshallerSpec.scala:59)
[spray] [info] 
[spray] [info] x gracefully fail when there are too many nested entities
[spray] [error]    'MalformedContent(,Some(java.lang.NullPointerException))' is incorrect:  (ScalaXmlUnmarshallerSpec.scala:74)
[spray] [info] 
[spray] [info] x gracefully fail when an entity expands to be very large
[spray] [error]    'MalformedContent(,Some(java.lang.NullPointerException))' is incorrect:  (ScalaXmlUnmarshallerSpec.scala:84)
```

where the tests instead expects a `SAXParseException` instead of a NPE. As an NPE could mean anything from a bug in the implementation to a dependency on a specific JDK version, the tests should probably be rewritten to output the full exception including stack trace in case the exception isn't of the expected type.

**Comment by adriaanm** [comment]
Thanks, @jrudolph!

**Comment by SethTisue** [comment]
@jrudolph if or when you have a new version for us to test, let us know. for now, in the community build we are leaving the tests disabled and the version pegged at v1.3.3

**Comment by SethTisue** [comment]
for the 2.11 builds, it's fine to leave spray as-is, I think.

in the 2.12 build, spray is actually commented out because of some JSON library problem — might be easy to fix, we should revisit it

**Comment by SethTisue** [comment]
returning to this now — #324 should clear the way

**Comment by SethTisue** [comment]
these dependencies look potentially problematic:
- old Akka version (2.1, should be 2.4.x)
- old Shapeless version (1.2, should be 2.x)
- old ScalaTest version (2.2, should be 3.0.x)
- old Specs2 version (2.3, should be 3.8.x)
- two different twirl-api dependencies (??? — not sure what this is about)

@sirthias @jrudolph offhand, this looks like too many outdated libraries for likely success at including spray in the Scala 2.12 community build. it's _possible_ that you're actually using these libraries in ways that are source-compatible with the versions in the community build, but offhand it looks like a slog for us. are you interested in embarking on your own program of library-refreshing...? you'll probably need to anyway if you plan to support Scala 2.12.

I'd suggest we park this ticket until you've published spray for Scala 2.12.0-RC1 (or later)

**Comment by sirthias** [comment]
I don't think having spray as part of the community still makes sense going forward.
spray is end of life and will not be maintained.
Additionally, basically all its logic has been moved over to Akka HTTP, which is already part of the build (AFAIK). So, there shouldn't be too many constructs that adding spray would test _in addition_ to Akka HTTP.
Therefore, I'd vote to simply close this ticket.

**Comment by SethTisue** [comment]
@sirthias got it! thanks for letting us know.

yes, akka-http is in the 2.12 community build now (as of a week or two ago)
