### ISSUE TITLE
Obsolete MaxPermSize

### ISSUE THREAD

**Issue by som-snytt** [scala/community-builds#1114]
Maybe there is a one-line config to eliminate:

```
[parboiled:error] OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=640m; support was removed in 8.0
```

**Comment by SethTisue** [comment]
after poking around the dbuild source code and the docs, it seems this is controlled by `sbt-java-options`. I'll try setting it

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/pull/1115

**Comment by som-snytt** [comment]
I forgot to say "good first issue".
