### ISSUE TITLE
bump to akka 2.4-M3 in 2.12.x

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#117]
See https://github.com/akka/akka/pull/18009

That will enable removal of scala.concurrent.util.Unsafe.

**Comment by SethTisue** [comment]
after which https://issues.scala-lang.org/browse/SI-9381 can be closed

**Comment by adriaanm** [comment]
akka PR was merged

**Comment by SethTisue** [comment]
I'll get back on this as soon as the regular 2.12.x build is green again.

**Comment by SethTisue** [comment]
2.12.x is green again. now running a community build with src/library/scala/concurrent/util/Unsafe.java removed at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/146/consoleFull

**Comment by SethTisue** [comment]
fixed in #129
