### ISSUE TITLE
moving scalamock to a new org

### ISSUE THREAD

**Issue by barkhorn** [scala/community-builds#1184]
Hi, I see Scalamock is referenced here:
https://github.com/scala/community-build/blob/e4b965e78a7284408fe636510b9f369cf2835ebc/proj/scalamock.conf#L7

If we (@paulbutcher and @barkhorn) were to move this to a new organisation, would this cause you a lot of grief or is it as easy as updating the file above?
Happy to throw you a PR if it's the latter.

**Comment by SethTisue** [comment]
it's as easy as updating that file

**Comment by SethTisue** [comment]
if you decide to make the move, happy to accept a PR, or just do it myself
