### ISSUE TITLE
Continue improving JDK 15 builds

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1240]
#1225, now closed, was about getting the core of the build green on JDK 15

but there are still a lot of unnecessarily failing repos. there's no real rush, but we should gradually address them. also, as time passes, maintainers will probably address them themselves in their own repos.

**Comment by SethTisue** [comment]
I plan to focus on the 2.13.x build and worry about 2.12.x later.

failing projects at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1251/ (October 3):

`SUCCEEDED: 176`  
`FAILURES (UNEXPECTED): akka,ssl-config,fs2,scalatestplus-mockito,scala-parallel-collections,pureconfig,mockito-scala,scala-async,ip4s,scalikejdbc,scala-swing,parboiled2,avro4s`  
`BLOCKING DOWNSTREAM: akka (21), ssl-config (17), fs2 (16), scalatestplus-mockito (7), scala-parallel-collections (6), pureconfig (4), mockito-scala (3), scala-async (1), ip4s (1)`  
`FAILED: 13`  
`BLOCKED, DID NOT RUN: 45`  
`TOTAL: 234`

causes:

```
    "akka",          // needs newer sbt-osgi                                                                            
    "avro4s",        // test failure: com.sksamuel.avro4s.github.GithubIssue387                                         
    "fs2",           // needs newer sbt-osgi                                                                            
    "ip4s",          // needs newer sbt-osgi                                                                            
    "mockito",       // reflection-related test failures                                                                
    "parboiled2",    // needs newer sbt-osgi                                                                            
    "playframework", // Failed tests: play.mvc.HttpFormsTest                                                            
    "pureconfig",    // needs newer sbt-osgi                                                                            
    "scalatestplus-mockito", // needs newer sbt-osgi                                                                    
    "scala-async",   // needs newer sbt-scala-module (for newer sbt-osgi)                                               
    "scala-parallel-collections", // needs newer sbt-scala-module (for newer sbt-osgi)                                  
    "scala-swing",   // needs newer sbt-scala-module (for newer sbt-osgi)                                               
    "ssl-config",    // https://github.com/lightbend/ssl-config/issues/268                                              
    "twitter-util",  // Unrecognized VM option 'AggressiveOpts'                                                         
    "zinc",          // sbt.inc.Doc$JavadocGenerationFailed                                                             
    "scalikejdbc",   // test failure: scalikejdbc.jsr310.StatementExecutorSpec                                          
```

**Comment by gvolpe** [comment]
Hi @SethTisue , 

Fs2 has updated to the latest `sbt-osgi` a few days ago: https://github.com/typelevel/fs2/commit/8f899e6ab1cbb31ac4af8f3e705b81b9df0e62ef

I guess that should fix the issue?

**Comment by SethTisue** [comment]
@gvolpe thanks for letting me know. I'll get it in my next round of work on this.

UPDATE: done

**Comment by SethTisue** [comment]
I've been chipping away at this. current status (as of [run 1293](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1293/)): `SUCCEEDED: 215`, `BLOCKING DOWNSTREAM: mockito-scala (4), twitter-util (3), playframework (3), pureconfig (3), elastic4s (1), akka-persistence-cassandra (1), ip4s (1)`

```
  val jdk15Failures = Set[String](
    "akka-persistence-cassandra", // needs newer sbt-osgi
    "avro4s",        // test failure: com.sksamuel.avro4s.github.GithubIssue387
    "elastic4s",     // Unrecognized VM option 'CMSClassUnloadingEnabled'
    "ip4s",          // needs newer sbt-osgi
    "mockito-scala", // reflection-related test failures
    "playframework", // Failed tests: play.mvc.HttpFormsTest
    "pureconfig",    // needs newer sbt-osgi
    "twitter-util",  // Unrecognized VM option 'AggressiveOpts'
    "zinc",          // sbt.inc.Doc$JavadocGenerationFailed
  )
```

I'm feeling like this is now good enough as far as my own efforts are concerned — volunteer contributions remain welcome

**Comment by SethTisue** [comment]
oh, for the record, on 2.12.x the status (as of [run 1170](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk15-integrate-community-build/1170/)) is: `SUCCEEDED: 157` and `BLOCKING DOWNSTREAM: akka (25), fs2 (9), twitter-util (4), sbt-util (3), scala-async (2), scala-logging (2)`

and I think that's good enough. that's enough green to give good assurance that Scala and sbt are working, and addressing the remaining failures would be too annoying since so much of the 2.12.x build is now frozen
