### ISSUE TITLE
address JDK 16 failures

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1354]
sequel to #1352

first we need an ASM 9 upgrade: https://github.com/scala/bug/issues/12328

but then there are also some miscellaneous other failures, as listed in:

* https://github.com/scala/community-build/blob/2.12.x/scripts/Report.scala
* https://github.com/scala/community-build/blob/2.13.x/scripts/Report.scala

**Comment by SethTisue** [comment]
at team meeting today @retronym said there's a JVM flag we can pass to bypass errors such as "Unable to make private java.nio.DirectByteBuffer(long,int) accessible"

**Comment by SethTisue** [comment]
#1355 will get a bunch of projects green

**Comment by retronym** [comment]
@SethTisue See https://openjdk.java.net/jeps/396 ("Strongly Encapsulate JDK Internals by Default") for the relevant change. `java --illegal-access=permit ....` is the escape hatch (although it is deprecated for removal at some future release).

**Comment by SethTisue** [comment]
or if you don't care to craft exceptions and wait to just throw the barn door open,  `--permit-illegal-access`

**Comment by SethTisue** [comment]
the three parboiled-related failures:

```
    "play-doc",                 // Error creating extended parser class: Could not determine whether class 'play.doc.CodeReferenceParser$$parboiled' has already been loaded (Parboiled.java:58)
    "scalatest-tests",          // Error creating extended parser class: Could not determine whether class 'org.pegdown.Parser$$parboiled' has already been loaded
    "specs2-more",              // Error creating extended parser class: Could not determine whether class 'org.pegdown.Parser$$parboiled' has already been loaded (Parboiled.java:58)
```

seem to have been addressed in this fork: https://github.com/Byoskill/parboiled

but we can't use that fork as-is -- for one thing, `build.sbt` was moved aside. for another thing, we are frozen on an older parboiled because they upgraded ScalaTest to a newer version. though I guess we could deal with that by not bothering compiling or running the tests any more

so this seems fixable without big effort, but I'm reluctant to put in even medium effort. another possibility is to shrug and do nothing, leaving them as expected-to-fails, as there is no Scala bug here, and only one downstream project is blocked

I think I'm going to do nothing

**Comment by SethTisue** [comment]
the dispatch failure is (https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk16-integrate-community-build/24/artifact/logs/dispatch-build.log):

```
[dispatch] Running "test" in: lift-json
[dispatch] [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[dispatch] [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[dispatch] [info] compiling 1 Scala source to /home/jenkins/workspace/scala-2.12.x-jdk16-integrate-community-build/target-0.9.17/project-builds/dispatch-937b69c25d82c37612e99e10244d986bc76abd81/liftjson/target/scala-2.12/test-classes ...
[dispatch] ** COMMUNITY BUILD LINE COUNT: 18
[dispatch] [info] done compiling
[dispatch] failing seed for Lift Json.parse json is ab1gjcNDC7o9Gz5rFspYLVSLXEJ2btX6vwFYERfn2mA=
[dispatch] [info] ! Lift Json.parse json: Exception raised on property evaluation.
[dispatch] [info] > ARG_0: ""
[dispatch] [info] > Exception: java.lang.ExceptionInInitializerError: null
```

dispatch and lift-json are pretty dead these days. there is a nonzero chance that if I investigated I'd turn up something interesting, but I think the chance is quite low, so I'm going to ignore this one too, especially since it isn't blocking anything downstream.

**Comment by SethTisue** [comment]
on 2.12.x, that just leaves shapeless-java-records:

```
[shapeless-java-records] [error] /home/jenkins/workspace/scala-2.12.x-jdk16-integrate-community-build/target-0.9.17/project-builds/shapeless-java-records-a3d3e64e090868b0b606f294214ac5302b84f90e/src/main/scala/JavaRecordGeneric.scala:48:17: value permittedSubclasses is not a member of Class[?0]
[shapeless-java-records] [error]           clazz.permittedSubclasses.map(_.displayName)
[shapeless-java-records] [error]                 ^
```

but @xuwei-k's own CI doesn't test on 16 (https://github.com/xuwei-k/shapeless-java-records/blob/main/.github/workflows/ci.yml), and the failure seems highly unlikely to be Scala's fault, so I'm not going to investigate

**Comment by SethTisue** [comment]
so now let's look at 2.13.x:

```
    "akka",                     // Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks accessible: module java.base does not "opens java.lang" to unnamed module @60e89085
    "requests-scala",           // requests.RequestTests fails, unclear why
```

requests-scala doesn't seem worth investigating

akka just needs `--illegal-access=permit`, it looks like. so I've pushed that, and I can take a look tomorrow and see if that uncovers any additional failures downstream.

**Comment by xuwei-k** [comment]
https://github.com/openjdk/jdk/commit/637b0c64b0a5d67d31b4b61dee55e8d682790da0#diff-a6270f4b50989abe733607c69038b2036306d13f77276af005d023b7fc57f1a2R4424

- jdk15 `permittedSubclasses`
- jdk16 `getPermittedSubclasses`

😢

**Comment by xuwei-k** [comment]
fixed shapeless-java-records 🙇 

- https://github.com/xuwei-k/shapeless-java-records/commit/388583b1244de1d7d287623247c1d3f7ec14c019
- https://github.com/xuwei-k/shapeless-java-records/commit/022db17c3692192724537573150c808206f8f678

**Comment by SethTisue** [comment]
@xuwei-k 9827559f4a25225991ab258cb809e7639affc248 :+1: (merged onto 2.13.x as well)

**Comment by SethTisue** [comment]
> akka just needs --illegal-access=permit, it looks like

when adding this to a repo, we need to be attentive about whether to add it to `extra.options`, for unforked tests, or `javaOptions`, for forked tests

**Comment by SethTisue** [comment]
after a series of further tweaks, https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk16-integrate-community-build/28/console has 237 green repos (out of 272). declaring victory
