### ISSUE TITLE
Mayday! Deal with Bintray's impending May 1 disappearance

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1357]
It's primarily sbt plugins that I'm worried about, since in this context that's mainly where we depend on binary artifacts. There's also dbuild itself.

Anything that's coming from repo.scala-sbt.org or repo.typesafe/lightbend.com, I'm assuming will be preserved somehow, although how that would happen remains under discussion for now. (Bintray doesn't vanish until May 1.)  

So perhaps only a limited number of plugins will vanish out from under us, few enough to be dealt with individually? I'm certain that some repos in the build depend on plugins that are published to personal Bintrays, and perhaps to JCenter as well, not sure. A rough list (perhaps not complete, and also perhaps containing no-longer-needed entries):

* JCenter (?)
* dl.bintray.com/eed3si9n
* dl.bintray.com/emersonloureiro
* dl.bintray.com/scalameta
* dl.bintray.com/tpolecat
* dl.bintray.com/2m

We have those artifacts in cache in our Artifactory, but unless we do something, the contents of that cache would then become precious, instead of disposable like before.

@adriaanm: “one thing we can do is mirror those repos in our own artifactory. or at least should look into”

Some of the plugins probably aren't essential, so we could decide on a case by case basis whether to mirror the plugins to keep them available, or whether to just fork the repo in question and remove that plugin from the build.

**Comment by SethTisue** [comment]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ has additional detail

First, it says that JCenter isn't going away until February 1, 2022. So (if I understand correctly) on May 1 2021 we won't lose JCenter stuff, just `dl.bintray.com/<username>` stuff.

Second, it seems perhaps _everything_ will remain available _if resolved from Artifactory_? The community build never resolves anything except through scala-ci.typesafe.com/artifactory , so does that mean the community build will be entirely unaffected by this? Do I misunderstand? Is this too good to be true?

The passage in question is:

> Artifactory installations with remote repositories configured against Bintray and Centers will not be affected by this sunset

It also says:

> JFrog self-hosted customers can also continue fetching from these repositories, but are encouraged to migrate to the canonical repositories

I don't think we're paying JFrog to operate scala-ci.typesafe.com/artifactory, I thought we're just using it for free... is that relevant here?

**Comment by adriaanm** [comment]
Unfortunately, we're not a customer in that sense.

I do think the community build should not directly be affected. I don't know what the retention policy is on the cache... We'll potentially have to configure new remote repos in our cache.

**Comment by SethTisue** [comment]
my current plan is to ignore this unless and until something actually breaks, and when it does, deal it with it then

I recently retired the 2.11 build entirely, and that's where the truly ancient stuff was likeliest to be

I'm a little nervous how much breakage there will be in 2.12, but the 2.12 build is largely frozen anyway, so I think it will typically be fine to either 1) fork the repo and remove or update the offending plugin, 2) just drop the repo, the 2.12 build is enormous and can live with taking a hit from losing some less-important things

2.13 I'm less nervous about, everything is newer and there is higher likelihood that any problems that do arise can be resolved upstream, rather than me needing to fix it myself here

so, closing since in my view there's nothing that needs to be done before May 1

**Comment by SethTisue** [comment]
> Anything that's coming from repo.scala-sbt.org or repo.typesafe/lightbend.com, I'm assuming will be preserved somehow

this is in process at the Scala Center (repo.scala-sbt.org; ticket: https://github.com/sbt/sbt/issues/6294) and at Lightbend (the others)

**Comment by ak0rz** [comment]
> my current plan is to ignore this unless and until something actually breaks, and when it does, deal it with it then
> 
> I recently retired the 2.11 build entirely, and that's where the truly ancient stuff was likeliest to be
> 
> I'm a little nervous how much breakage there will be in 2.12, but the 2.12 build is largely frozen anyway, so I think it will typically be fine to either 1) fork the repo and remove or update the offending plugin, 2) just drop the repo, the 2.12 build is enormous and can live with taking a hit from losing some less-important things
> 
> 2.13 I'm less nervous about, everything is newer and there is higher likelihood that any problems that do arise can be resolved upstream, rather than me needing to fix it myself here
> 
> so, closing since in my view there's nothing that needs to be done before May 1

@SethTisue 
jfyi: every sbt build is broken today because of Bintray brown-out session https://status.bintray.com/

**Comment by SethTisue** [comment]
thanks! I'll keep an eye out for trouble

**Comment by SethTisue** [comment]
Today is Bintray brownout day (there will be another on April 26) and community builds are indeed failing: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk16-integrate-community-build/156/console

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

that's because we fetch dbuild itself `curl -LO "https://repo.lightbend.com/typesafe/ivy-releases/com.typesafe.dbuild/dbuild/${DBUILDVERSION}/tgzs/dbuild-${DBUILDVERSION}.tgz"`

Lightbend IT is in the process of migrating repo.lightbend.com to new hosting, so for now we just need to be patient.

**Comment by SethTisue** [comment]
repo.scala-sbt-org is now redirecting to a JFrog URL instead of a Bintray URL, as of this afternoon

@JustinPihony says repo.lightbend.com is expected to start redirecting to Cloudsmith on Tuesday

**Comment by jademanta** [comment]
Thanks for updating this thread Seth! I followed it closely.
