### ISSUE TITLE
track scalatest

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#14]
now at "scalatest/scalatest.git#scala-2.11-M8", not sure which branch we should track

**Comment by SethTisue** [comment]
in the 2.12 community build, we're on the `2.2.x-for-scala-2.12.0-M2` branch. the 2.2.x series is the current stable version, so that's plenty good enough for now, though we'll want to move it forward as 2.12 progresses.

**Comment by SethTisue** [comment]
in the 2.11 community builds (jdk6 and jdk8), `scala-2.11-M8` looks like an early 2.1.x build, so we should first try upgrading to the `2.1.x` branch, and then perhaps go further to `2.2.x`.  (there is a 3.0 branch, but it's still in flux, so it doesn't make sense for us to track it yet.)

**Comment by SethTisue** [comment]
mentioning @bvenners who might be mildly interested in following this

**Comment by bvenners** [comment]
The latest branch for the latest released version of ScalaTest is:

https://github.com/scalatest/scalatest/tree/2.2.3-and-greater

But is there a reason you want to track a development branch rather than a release tag?

**Comment by SethTisue** [comment]
so we don't have to keep bumping the tag, and so we all find out sooner if something breaks.

we don't want to track a wild-west development branch, but a lot of projects have fairly stable branches where nothing is committed unless it has passed both code review and CI, and where source compatibility is broken only rarely, or only in edge cases; tracking that kind of branch usually works fine.

**Comment by SethTisue** [comment]
done in 2.11.x-jdk6: https://github.com/scala/community-builds/pull/147

**Comment by SethTisue** [comment]
with `2.2.3-and-greater` I have seen green trial runs in all 3 builds, so even though it's not all merged through yet onto all branches (which may take a few days since the runs take so long), closing as done. :tada:
