### ISSUE TITLE
add JDK 17 build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1432]
(...and drop 16, presumably)

JDK 17 is now feature-complete and the final release lands in September, so now is a good time for this

The current JDK 17 build is "Build 26 (2021/6/11)".

using https://github.com/scala/community-build/issues/1352 as a guide to steps needed:

* [x] on all 3 behemoths:
  * `cd /usr/lib/jvm`
  * `sudo curl -O -L 'https://download.java.net/java/early_access/jdk17/26/GPL/openjdk-17-ea+26_linux-x64_bin.tar.gz'`
  * `sudo dtrx -n openjdk-17-ea+26_linux-x64_bin.tar.gz`
  * `sudo rm openjdk-17-ea+26_linux-x64_bin.tar.gz`
  * `sudo chmod -R go+rX openjdk-17-ea+26_linux-x64_bin`
  * `sudo ln -s openjdk-17-ea+26_linux-x64_bin java-17-openjdk-x64`
  * `./java-17-openjdk-x64/jdk-17/bin/java -version`
* [x] add `-jdk17-` jobs (on 2.12.x and 2.13.x) with JDK version set appropriately
* [x] make sure both jobs extract
* [x] make sure both jobs have at least a green core
* [x] update `scripts/Report.scala` (both branches)
* [x] report selected failures upstream
* [ ] ~open a separate ticket on gradually getting more projects green?~
* [x] disable the old `-jdk16-` jobs
* [x] delete the old `-jdk16-` workspace directories

**Comment by lrytz** [comment]
👍 thank you, this is the perfect time to start testing 17.

**Comment by fernandoracca** [comment]
this is great! looking forward to start using the newer JVMs.

**Comment by SethTisue** [comment]
2.13.x core is green. I will dig into the specific failures

2.12.x core fails with some lambda deserialization problem. I've opened a separate ticket on it: https://github.com/scala/bug/issues/12419

**Comment by SethTisue** [comment]
Jason fixed the deserialization thing, so the 2.12.x core is now green too (on 2.12.15-bin-b2b8816)

**Comment by SethTisue** [comment]
2.13.x status as of [this run](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk17-integrate-community-build/15/console): `FAILURES (UNEXPECTED): akka-http,akka-more,macwire,classutil`

all four repos are running afoul of https://openjdk.java.net/jeps/403, resulting in `java.lang.reflect.InaccessibleObjectException`s

I will mark them as expected-to-fail.

* macwire: notified maintainers: https://github.com/softwaremill/macwire/pull/162
* classutil: repo seems abandoned
* @patriknw heads up on the [akka-http failure](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/15/artifact/logs/akka-http-build.log) and the [akka-more failure](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/15/artifact/logs/akka-more-build.log)

I suspect it would be possible for me to make them pass by replacing `--illegal-access=...` with the more specific `--add-opens`, but in general, it's not a priority for us to get out ahead of upstream maintainers on JDK 17 support once the overall number of green projects seems adequate for QAing Scala itself.

**Comment by patriknw** [comment]
Thanks @SethTisue .
I have created issues https://github.com/akka/akka-http/issues/3852 and https://github.com/akka/akka/issues/30341

**Comment by SethTisue** [comment]
declaring victory here. we'll want to ship 2.12.15 before too much longer, in order to get the serialization fix out

**Comment by SethTisue** [comment]
2.12.15 planning thread: https://contributors.scala-lang.org/t/scala-2-12-15-planning/5152
