### ISSUE TITLE
add Akka HTTP and Akka Streams

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#146]
we should do this because it's Akka, but also because ensime-server's master branch now has them as a dependency

I tried changing our dep to `akka.git#releasing-akka-stream-and-http-experimental-1.0` but it didn't work and I decided to postpone rather than investigate. (for now we freeze ensime-server at the commit before the dependency was added)

(this was in the 2.11 build. it might be better to leave that one alone and only tackle Akka Streams in Java 8 world? dunno)

**Comment by SethTisue** [comment]
> it might be better to leave that one alone and only tackle Akka Streams in Java 8 world

definitely only worth tackling on JDK 8. the JDK 6 community build is pretty close to frozen these days; too many libs are dropping JDK 6 support, and the existing set is good enough to achieve our main goal of guarding against regressions in Scala 2.11.x

**Comment by SethTisue** [comment]
depends on https://github.com/scala/community-builds/issues/292

**Comment by SethTisue** [comment]
wip in SethTisue/community-builds#akka-http:

```
[akka-http] [error] /Users/tisue/community-builds.212/target-0.9.5/project-builds/akka-http-2993527e43e49e6d7b8326a319451cfd3000db8b/akka-stream/src/main/scala/akka/stream/javadsl/Source.scala:159: illegal inheritance from final class Inclusive
[akka-http] [error]         new Inclusive(start, end, step) {
[akka-http] [error]             ^
[akka-http] [error] one error found
```

**Comment by SethTisue** [comment]
ah, this is a real incompatibility with Scala 2.12, because https://github.com/scala/scala/pull/5226

**Comment by SethTisue** [comment]
this is an actual incompatibility with Scala 2.12, because Range.Inclusive is final since https://github.com/scala/scala/pull/5226

@ktoso can you guys work around this? in general, subclassing collections is iffy

**Comment by SethTisue** [comment]
test run with forked akka with the subclassing simply [removed](https://github.com/SethTisue/akka/commit/383c1a2bcfdc663e0f4637201d796f32863a5d09)
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/613/consoleFull~~
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/614/consoleFull~~
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/615/consoleFull~~
- https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/616/consoleFull

**Comment by som-snytt** [comment]
Also, Range got a compact toString at https://github.com/scala/scala/commit/214ea82573624bffb4d0f16f3e5c49f9370ba7a7

**Comment by SethTisue** [comment]
in the above test runs I was trying an approach of building Akka in two separate phases, first with most of the modules, then again with akka-http + akka-stream. the first phase produced an akka-actors jar for ssl-config to depend on. that part worked, but akka-http-core failed to build, with dbuild/sbt saying it couldn't find the akka-testkit and/or akka-stream-testkit modules. I guess it has to do with test dependencies vs. regular dependencies somehow. I tried tweaking the `projects` and `exclude` lists in various ways but didn't succeed in making the errors go away.

currently trying again with a slightly different approach: in the first phase, only publish akka-actor, which is all ssl-config needs. then build everything else in the second phase. I have high hopes this will work

**Comment by SethTisue** [comment]
latest attempt fails with a Scaladoc generation issue; reported upstream at https://github.com/akka/akka/issues/21543

**Comment by SethTisue** [comment]
done in https://github.com/scala/community-builds/pull/298 , but I had to fork akka to get the needed Range.Inclusive change in. reported upstream at https://github.com/akka/akka/issues/21548
