### ISSUE TITLE
dbuild launcher JARs seem to have gone missing

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1475]
specifically, `com.typesafe.dbuild#launcher-interface;1.0.1-d1` and `com.typesafe.dbuild#launcher;1.0.1-d1` don't resolve anymore

I assume this happened during the Bintray -> Cloudsmith migration some months ago but we didn't notice until now because the JARs were in cache at https://scala-ci.typesafe.com/artifactory/

but I did some config changes there that resulted in that part of the cache being cleared, so now I need to know where the original files are

**Comment by SethTisue** [comment]
for troubleshooting this outside dbuild, you can make an empty directory with this `build.sbt`:

```
resolvers += "lightbend-maven-releases" at "https://dl.cloudsmith.io/public/lightbend/maven-releases/maven/"
libraryDependencies += "com.typesafe.dbuild" % "launcher" % "1.0.1-d1"
```

(the resolver URL was suggested by @sebastian-alfers)

when you run `sbt update`. you get:

```
[Fatal Error] :1:1: Content is not allowed in prolog.
[error] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
```

looking at https://cloudsmith.io/~lightbend/repos/maven-releases/packages/detail/maven/launcher-interface/1.0.1-d1/a=noarch;xg=com.typesafe.dbuild/#files , it says all the files are 41 bytes, which seems suspicious

**Comment by sebastian-alfers** [comment]
@SethTisue  I fixed the repos and tried the above resolver / dependency and it works 👍

**Comment by SethTisue** [comment]
seems also fixed in the community build context afaict. thank you Sebastian!
