### ISSUE TITLE
get ensime and spray-json-shapeless working again in 2.12.x build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#150]
some details are in the 2.12. common.conf. they are commented out right now — it hasn't been deeply investigated yet

the spray-json-shapeless error is:

```
Missing dependency: the library io.spray#spray-json is not provided (in space "specs2_24")
```

after extraction, the log shows:

```
[info] Project spray-json-shapeless
[info]   depends on: akka, scala, scalacheck, scalatest, shapeless
```

which isn't right; in 2.11.x-jdk8 we see many more dependencies:

```
[info] Project spray-json-shapeless
[info]   depends on: akka, genjavadoc-plugin, scala, scala-logging-api, scala-logging-slf4j, scalacheck, scalatest, scalaz, scoverage, shapeless, specs2, spray-json
```

**Comment by SethTisue** [comment]
we had ENSIME frozen at an old commit because it started depending on akka-http/akka-stream, which we didn't have

the akka thing finally got sorted out just now (in the 2.12 build only) by #298 

so, we could try again with a current commit. fyi @fommil

**Comment by fommil** [comment]
I can do spray-json-shapeless easily when i return from holiday. But ensime 2.12 is pretty big because of the dependency chain and java/scala matrix for akka. We're working on it.

**Comment by fommil** [comment]
Oh btw we removed akka-http. See https://github.com/ensime/ensime-server/issues/1414 for our ticket.

**Comment by fommil** [comment]
Probably sjs is picking up lots of sbt plugin/test deps.

**Comment by SethTisue** [comment]
generally sbt plugins are not a problem in a community build context, since we don't build plugins, we just resolve them like normal (since they're Scala 2.10 based)

**Comment by SethTisue** [comment]
provisionally closing since ENSIME doesn't currently support 2.12
