### ISSUE TITLE
build circularly dependent Scala modules with fresh, not stock compiler?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#154]
as previously detailed at #142, dbuild's "assemble" builds Scala first, but then doesn't use the Scala it just built to build circularly dependent modules like scala-xml. this is arguably a bug, or at least not ideal, given that the whole idea of dbuild is to build everything using a freshly-built Scala compiler

dbuild builds Scala and its modules using the "assemble" build system. the doc on that build system says "the nested projects are built independently, each in isolation", which can be read as describing the behavior in this ticket as intentional. it's not trying and failing to override the module's Scala version — it isn't even trying.

**Comment by adriaanm** [comment]
Maybe we should just use our own release script to build scala and have dbuild to the rest?

**Comment by SethTisue** [comment]
superseded by #274
