### ISSUE TITLE
add more projects

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#161]
(I edit this list frequently. except when I forget to update it at all.)

projects we'd like to include:
- high priority:
    - Spark #763 — volunteers needed
    - (nothing else right now?)
- would be nice:
    - scastie (not a lib, but good to have some apps)
    - Play sample repos (we do have play-webgoat)
    - macwire
    - [hamsters](https://github.com/scala-hamsters/hamsters)
    - squants ([PR](https://github.com/scala/community-builds/pull/590))
    - algebird
    - thyme
    - [metal](https://github.com/denisrosset/metal)
    - scalatra
    - [finagle](https://github.com/twitter/finagle)
    - ammonite (problematic because it's built with mill now, not sbt; someone would need to make a minimal sbt build; or perhaps someday dbuild will support mill)

what _won't_ we add? important to ecosystem but probably out of scope here: Dotty, IntelliJ, Scala Native, cbt (builds itself, not built by sbt), mill (ditto, they have an sbt build at the moment but plan to eliminate it), all sbt plugins (there could be a separate build for that), ...

**Comment by SethTisue** [comment]
note to self, one dbuild feature we aren't currently taking advantage of is that dependencies can be added as binary: "Although that rather defeats the point of compiling all code using the same Scala version, it can nonetheless be quite useful in the case in which only a specific binary is available, for example in case of libraries that are proprietary and closed-source, or that are currently unmaintained."

so if we really want library A, but A depends on B and B is hard to add for whatever reason, we can always just add B as a binary dependency. something to keep in mind.

**Comment by SethTisue** [comment]
@lihaoyi I took a quick stab at scalatags but it has version-checking logic in the build that needs updating — a different set of dependencies is needed for the different Scala version, and there are Scala-version-specific source directories, too. so I'm abandoning this for now, but once the library has been updated and published for 2.12 (issue opened: https://github.com/lihaoyi/scalatags/issues/137), we could try again and it will probably just work.

**Comment by SethTisue** [comment]
we might look at https://github.com/olafurpg/scala-experiments for candidate additions. also the [Dotty community build](https://github.com/lampepfl/dotty-community-build)

**Comment by adamw** [comment]
I just noticed this & a (so far failed) attempt to add sttp. No idea how this works, but if you would need some help on the sttp's build, let me know :)

**Comment by SethTisue** [comment]
I've made a separate Spark ticket at https://github.com/scala/community-builds/issues/763

**Comment by SethTisue** [comment]
closing. this ticket has served its purpose; the build is now big enough, overall. we'll still add specific things from time to time, but there's no point to keeping this neglected ticket open.
