### ISSUE TITLE
need better documentation on doing local runs

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#162]
(accumulated random notes on this from the last few months)

though it may not even be worth documenting this better until something is done about the performance issues (its's #152)

I guess setting up local Artifactory helps performance; I haven't tried it yet. there is doc linked from #58

often, running dbuild with `-d` is key in order to see what's going on (I mean if it's the community build itself you're troubleshooting, and not a compiler bug)

document how to fix the scala version at a given SHA, to prevent global rebuilds when someone merges a Scala PR? the Jenkins jobs for community builds have a field for this, not sure how it's done locally.

how to run just one project? e.g. `./dbuild-0.9.1/bin/dbuild -n community.dbuild sbinary` works, sort of, but does bypassing the usual `scripts/jobs/integrate/community-build` method still get you the right resolvers? need to double check what value the scripts directory script adds

also building just one project doesn't really save you that much time since all projects are still extracted which takes a while. I've been working around this by commenting out big swathes of common.conf and/or community.dbuild

**Comment by matanox** [comment]
Nice doc! I'm consistently grinding close to a halt with ivy resolutions. (indeed with the `-d` option I can see something is happening v.s. just being stuck). Wondering whether a local proxy gives any gain beyond the caching already performed by default by ivy. I would assume that it would not make any difference in the single machine scenario. 

Thanks for suggesting `-d`!

**Comment by gkossakowski** [comment]
Local artifactory helps to speed up resolution for a few reasons:
- it appears to me that Ivy will resolve the same artifact multiple times; Artifactory is good at resolving only once
- when you add repos to Artifactory you can check the option to prefetch jars in the background triggered by poms requests
- Ivy cache might get corrupted and you have no option but start over
- Ivy cache is stored per dbuild version so upgrading dbuild requires recreating Ivy cache

**Comment by matanox** [comment]
I assume you are right, many thanks. But I can't really fathom why would
ivy resolve the same artifact multiple times.

**Comment by matanox** [comment]
Running for 24 hours and going, several restarts required after occasional
akka http timeouts over resolution.
Any idea why so much duplication in the resolution logging?

```
[scala-swing] [info] Resolving org.apache#apache;4 ...
[scala-swing] [info] Resolving net.databinder#dispatch-futures_2.10;0.8.10...
[scala-swing] [info] Resolving net.databinder#dispatch-futures_2.10;0.8.10...
[scala-swing] [info] Resolving org.scala-lang#scala-actors;2.10.2 ...
[scala-swing] [info] Resolving org.scala-lang#scala-actors;2.10.2 ...
[scala-swing] [info] Resolving commons-io#commons-io;2.4 ...
[scala-swing] [info] Resolving commons-io#commons-io;2.4 ...
[scala-swing] [info] Resolving org.apache.commons#commons-parent;25 ...
[scala-swing] [info] Resolving org.apache.commons#commons-parent;25 ...
[scala-swing] [info] Resolving org.apache#apache;9 ...
[scala-swing] [info] Resolving org.apache#apache;9 ...
[scala-swing] [info] Resolving com.jcraft#jsch;0.1.50 ...
[scala-swing] [info] Resolving com.jcraft#jsch;0.1.50 ...
```

And I am very curious why the entire resolution process starts over when rerunning dbuild, it looks like no caching is taking place, or dbuild is invalidating the previous resolution. It would be nice being able to tell it not to invalidate prior resolutions, when doing a rerun. Is this last aspect a pure sbt one?

**Comment by SethTisue** [comment]
@matanster you may find the ivy resolution picture improved now if you tried again — the list of the resolvers in the config file is now much shorter

**Comment by SethTisue** [comment]
> how to run just one project

or several (comma-separated); improved and documented in https://github.com/scala/community-builds/pull/331

**Comment by SethTisue** [comment]
this is an open-ended ticket, but I'm basically satisfied with the current documentation, so I'm going to go ahead and close it.

it isn't documented yet how to specify the Scala nightly you want, but I'll get to that as part of https://github.com/scala/scala-jenkins-infra/issues/189

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/wiki was updated today with fresh instructions on this

**Comment by matanox** [comment]
Thanks!

Sent from my mobile

-------- Original Message --------
