### ISSUE TITLE
improve documentation for library authors wanting to add their projects

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#163]
@milessabin writes “I think it would be helpful if the community build README had some information for community library providers on how to keep the build  up to date consistently with not breaking dependencies for other  libraries ... I would have put a PR for this together myself a while back if I'd known what was involved."

@adriaanm writes “Seth is also working on better documentation for the community build, so that you can more easily contribute the configuration needed to include your project”

I did make a good start at this at https://github.com/scala/community-builds/wiki, but it still isn't really feasible for authors to do this themselves. Because #152, #162, #158, #133, ...

**Comment by SethTisue** [comment]
the doc is now "good enough", I think

**Comment by milessabin** [comment]
Thanks for that :-)
