### ISSUE TITLE
regression: scala-partest failing (MiMa errors)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#167]
failure log: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/124/consoleFull:

```
[scala-partest] [info] scala-partest: found 40 potential binary incompatibilities
...
```

I think the responsible PR is https://github.com/scala/scala-partest/pull/40

maybe the MiMA files in the scala-partest repo just need to be updated? I haven't dealt with this before. @szeiger?

@adriaanm, is there any need for scala-partest to stay binary compatible from release to release at all...? it's not obvious to me what the point of that would be.

**Comment by szeiger** [comment]
It's not binary compatible. What's the process for updating it? Wouldn't this have to wait until a new release is published so it can be used as a baseline?

**Comment by adriaanm** [comment]
i guess we can either turn off the checks until the next release or (preferred) cut a new release and use it as a baseline

**Comment by SethTisue** [comment]
but what is the purpose of retaining the MiMa checks at all?

**Comment by adriaanm** [comment]
Backstop against accidental breakage, so we can blindly accept PRs that don't break binco. It's not intended to stop binary changes, but we have no finer comb.

**Comment by SethTisue** [comment]
I see. (@szeiger, perhaps add a bit of doc to that effect?)

**Comment by SethTisue** [comment]
@szeiger checking, is this still on your radar?
