### ISSUE TITLE
Documentation for community members trying to reproduce build failures

### ISSUE THREAD

**Issue by milessabin** [scala/community-builds#224]
It would be helpful if there were a prominent section in the README explaining how to find the relevant scalac git hash in the community build logs and how to use it in a local SBT build ... replicating the information from [here](https://github.com/scala/scala#tips--tricks) would be a start.

**Comment by lrytz** [comment]
See also https://github.com/scala/scala-jenkins-infra/issues/133

We're currently re-working the build and publish infra (fading out `build.xml`), so things are a bit in flux.

**Comment by SethTisue** [comment]
good idea. I'll take care of this.

**Comment by SethTisue** [comment]
related: #162

**Comment by SethTisue** [comment]
I just updated the wiki in this repo with all the latest advice that I could think of.
