### ISSUE TITLE
regression: spray-json-shapeless has started failing (macro issue in SimpleTraitFormat)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#226]
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/232/consoleFull:

```
[spray-json-shapeless] [info] Compiling 3 Scala sources to /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/spray-json-shapeless-b21f97052f556abdb4d07203ed3333879df6f61c/target/scala-2.11/test-classes...
[spray-json-shapeless] [error] /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/spray-json-shapeless-b21f97052f556abdb4d07203ed3333879df6f61c/src/test/scala/fommil/sjs/FamilyFormatsSpec.scala:99: inst$macro$7  is already defined as value inst$macro$7
[spray-json-shapeless] [error]   implicit val SimpleTraitFormat: RootJsonFormat[SimpleTrait] = cachedImplicit
[spray-json-shapeless] [error]                                                                 ^
[spray-json-shapeless] [error] one error found
[spray-json-shapeless] [error] (test:compileIncremental) Compilation failed
```

**Comment by SethTisue** [comment]
@fommil as the comments in https://github.com/scala/community-builds/blob/2.11.x/common.conf indicate, the dependency situation in the community build w/r/t ENSIME and spray-json-shapeless is a bit tricky. any insight into what the right path forward here might be?

**Comment by fommil** [comment]
I think this is because of the shapeless update. Can you maybe change to use the stable release tag which builds against the stable shapeless? I didn't even know we were in the community build :smile:

**Comment by SethTisue** [comment]
> Can you maybe change to use the stable release tag which builds against the stable shapeless

I'm sorry, I don't know what means. Can you be more specific about what your suggestion is?

**Comment by fommil** [comment]
This only happened building `master` spray-json-shapeless against `master` shapeless. If the build was https://github.com/fommil/spray-json-shapeless/tree/v1.1.0 vs https://github.com/milessabin/shapeless/tree/shapeless-2.2.5 there would have been no failure.

Shapeless introduced a regression, and then they fixed it. I expect you can close this now.

**Comment by SethTisue** [comment]
ok, let's see how https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/234/consoleFull does

**Comment by SethTisue** [comment]
the play2-core failure is surely unrelated. closing. thanks @fommil

**Comment by fommil** [comment]
Or is it? Muahahaha!
