### ISSUE TITLE
regression: sbt-republish started failing recently

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#234]
a recent PR merged to sbt-republish broke integrate-ide, as discussed at https://github.com/scala/scala-dev/issues/104, and is also breaking the community build

to get the build green again, I pinned to an older SHA, but we should at least to start tracking master again

**Comment by SethTisue** [comment]
~~as seen in #235 using an older SHA of sbt-republish didn't actually help. so much for that hypothesis.~~

~~looking into what else might be going on here...~~

trying again: #236

**Comment by SethTisue** [comment]
not sure yet if relevant, but: PR in scala/scala repo where 2.11.x branch was upgraded to sbt 0.13.11: https://github.com/scala/scala/pull/4993

**Comment by SethTisue** [comment]
```
[info] Project sbt-republish
[info]   depends on: sbinary, sbt, scala, scalacheck
```

last green run was: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/249/consoleFull  with scala/scala at fd7a15973d197d53b9c45dd06cb121372577e3f6 (which includes the sbt 0.13.11 upgrade), sbt-republish at 9f7109c705175c6d8e7e99c60e53959f9e4c5df0. sbt has been pinned to an old SHA for a while, and presumably sbinary and scalacheck are irrelevant here

first red run was: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/250/consoleFull with scala/scala at afb14588edeb199ad5b6b2deedb55abe3c998503, sbt-republish at c4be3f1334279b9be390fe6a6807cc8491410f38

the only diffs between those two revs in scala/scala is the change to akka-actor.version.number

**Comment by SethTisue** [comment]
yeah this has got to be https://github.com/typesafehub/sbt-republish/pull/12/commits/8c799d687ea768e28ce2e21b92a77310f6d6b977 — and I don't understand the motivation for the change

**Comment by SethTisue** [comment]
community build is fixed for now by pinning to an earlier commit, but we should still do something about the actual cause since we don't want to leave sbt-republish frozen forever

**Comment by SethTisue** [comment]
the failure looks like:

```
[sbt-republish] sbt.ResolveException: unresolved dependency: org.scala-sbt#compiler-interface;0.13.11-dbuildx499d6a7aad8fd3e4645349edfa2c6a91349a6b99: not found
```

in the last green run we saw:

```
[sbt] [info] :: delivering :: org.scala-sbt#compiler-interface;0.13.6-dbuildx6cb0e9e9b70069c5a7b2e2518acea989085cc65d :: 0.13.6-dbuildx6cb0e9e9b70069c5a7b2e2518acea989085cc65d :: release :: Sun Mar 13 00:26:13 UTC 2016
...
[sbt-republish] [info] :: delivering :: com.typesafe.sbt#compiler-interface;0.13.9-dbuildx84a74bb8e17f8841f8fa30d85380791628d6aa47 :: 0.13.9-dbuildx84a74bb8e17f8841f8fa30d85380791628d6aa47 :: release :: Sun Mar 13 01:33:09 UTC 2016
```

I don't know what to make of the `org.scala-sbt` vs `com.typesafe.sbt` here.

in the first red run `grep -i delivering red.txt | grep compiler-interface` shows only:

```
[sbt] [info] :: delivering :: org.scala-sbt#compiler-interface;0.13.6-dbuildx0be7758696a2978fb553599d1f0ab34227c24c7f :: 0.13.6-dbuildx0be7758696a2978fb553599d1f0ab34227c24c7f :: release :: Sat Mar 19 04:27:03 UTC 2016
```

**Comment by SethTisue** [comment]
the failure occurs during:

```
[sbt-republish] Processing subproject: compilerInterfacePrecompiled
```

in the green run we see:

```
[sbt-republish] Processing subproject: compilerInterfacePrecompiled
[sbt-republish] All Dependencies for subproject compilerInterfacePrecompiled:
...
[sbt-republish]    org.scala-sbt:compiler-interface:0.13.6-dbuildx6cb0e9e9b70069c5a7b2e2518acea989085cc65d:deps
[sbt-republish]    org.scala-sbt:compiler-interface:0.13.6-dbuildx6cb0e9e9b70069c5a7b2e2518acea989085cc65d:eps
```

which matches the `[sbt] [info] :: delivering` line from earlier in the log.

whereas in the red run we see:

```
[sbt-republish] Processing subproject: compilerInterfacePrecompiled
[sbt-republish] All Dependencies for subproject compilerInterfacePrecompiled:
...
[sbt-republish]    org.scala-sbt:compiler-interface:0.13.11-dbuildx499d6a7aad8fd3e4645349edfa2c6a91349a6b99:deps
```

which doesn't match the `[sbt] [info] :: delivering` line from earlier in the log, either in sbt version number or SHA.

**Comment by SethTisue** [comment]
before @eed3si9n's recent changes to sbt-republish, `compilerInterfacePrecompiled`'s `compiler-interface` dependency was determined with:

```
def sbtVersionToRepublish = "0.13.9"
...
      version := sbtVersionToRepublish
...
  originalSbtVersion <<= version { v => if (v.endsWith("SNAPSHOT")) "latest.integration" else v },
...
    libraryDependencies <++= originalSbtVersion { v =>
      Seq(("org.scala-sbt" % "compiler-interface" % v % Deps.name).artifacts(Artifact("compiler-interface-bin")),
          ("org.scala-sbt" % "compiler-interface" % v % Deps.name).artifacts(Artifact("compiler-interface-src")))
    }
```

after those changes, it's now:

```
def sbtVersionToRepublish = "0.13.11"
...
      version := sbtVersionToRepublish,
...
  originalSbtVersion <<= version { v => if (v.endsWith("SNAPSHOT")) "latest.integration" else v },
...
    libraryDependencies <++= originalSbtVersion { v =>
      Seq(("org.scala-sbt" % "compiler-interface" % v % Deps.name).withSources())
    }
```

it's not clear to me yet why with the old code, dbuild is able to substitute `0.13.6` for `0.13.9` successfully, but with the new code, dbuild leaves `0.13.11` as `0.13.11`

it's not as if dbuild isn't manipulating the version number of the dependency at all. it isn't looking for just plain `0.13.11`, it's looking for `0.13.11-dbuildx499d6a7aad8fd3e4645349edfa2c6a91349a6b99`

**Comment by performantdata** [comment]
> community build is fixed for now by pinning to an earlier commit

Should this fix integrate-ide as well?

**Comment by SethTisue** [comment]
> Should this fix integrate-ide as well?

@sschaef can you try it and see?

**Comment by SethTisue** [comment]
closing for lack of interest

**Comment by kiritsuku** [comment]
The one is basically fixed because scala-ide no longer depends on sbt and therefore this issue no longer applies.
