### ISSUE TITLE
back to upstream for scalaz-stream

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#246]
our patch has been included upstream https://github.com/functional-streams-for-scala/fs2/pull/675

**Comment by SethTisue** [comment]
https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md lists two scalaz-stream releases, 0.8.3 and 0.8.3a. I couldn't find anywhere the difference is documented, but from `git diff origin/series/0.8 origin/series/0.8a` in the scalaz-stream repo I guess the primary difference is the scalaz version:

``` diff
-  "org.scalaz" %% "scalaz-core" % "7.1.4",
+  "org.scalaz" %% "scalaz-core" % "7.2.0",
```

note that we only have scalaz-stream in the 2.12 community build, not in either 2.11 build, and that our scalaz dependency there is 7.1.x

**Comment by SethTisue** [comment]
we disabled running of tests a while back; re-enabling is worth a try, much time having passed

**Comment by SethTisue** [comment]
test run https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/487/consoleFull

**Comment by SethTisue** [comment]
test run https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/489/consoleFull (the last one failed in scalaz probably because of Adriaan's changes, so scalaz-stream didn't even get to try to build)

**Comment by SethTisue** [comment]
result: many compile errors, the first one being:

```
[scalaz-stream] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalaz-stream-449d857cd8389539d39a64f23f0b8b318748a5b5/src/main/scala/scalaz/stream/Process.scala:117: no type parameters for method apply: (head: scalaz.stream.Process.HaltEmitOrAwait[F,O], stack: Vector[scalaz.stream.Cause => scalaz.stream.Process.Trampoline[scalaz.stream.Process[F,O]]])scalaz.stream.Process.Append[F,O] in object Append exist so that it can be applied to arguments (scalaz.stream.Process.HaltEmitOrAwait[F2,O2], scala.collection.immutable.Vector[scalaz.stream.Cause => scalaz.stream.Process.Trampoline[scalaz.stream.Process[F2,O2]]])
[scalaz-stream] [error]  --- because ---
[scalaz-stream] [error] argument expression's type is not compatible with formal parameter type;
[scalaz-stream] [error]  found   : scalaz.stream.Process.HaltEmitOrAwait[F2,O2]
[scalaz-stream] [error]  required: scalaz.stream.Process.HaltEmitOrAwait[?F,?O]
[scalaz-stream] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalaz-stream-449d857cd8389539d39a64f23f0b8b318748a5b5/src/main/scala/scalaz/stream/Process.scala:117: no type parameters for method apply: (head: scalaz.stream.Process.HaltEmitOrAwait[F,O], stack: Vector[scalaz.stream.Cause => scalaz.stream.Process.Trampoline[scalaz.stream.Process[F,O]]])scalaz.stream.Process.Append[F,O] in object Append exist so that it can be applied to arguments (scalaz.stream.Process.HaltEmitOrAwait[F2,O2], scala.collection.immutable.Vector[scalaz.stream.Cause => scalaz.stream.Process.Trampoline[scalaz.stream.Process[F2,O2]]])
[scalaz-stream] [error]  --- because ---
[scalaz-stream] [error] argument expression's type is not compatible with formal parameter type;
[scalaz-stream] [error]  found   : scalaz.stream.Process.HaltEmitOrAwait[F2,O2]
[scalaz-stream] [error]  required: scalaz.stream.Process.HaltEmitOrAwait[?F,?O]
[scalaz-stream] [error]        case (append: Append[F2, O2] @unchecked) => Append(append.head, append.stack :+ next)
[scalaz-stream] [error]        case (append: Append[F2, O2] @unchecked) => Append(append.head, append.stack :+ next)
[scalaz-stream] [error]                                                    ^
[scalaz-stream] [error]                                                    ^
```

**Comment by SethTisue** [comment]
specs2 is still using scalaz-stream, not fs2, so we must keep scalaz-stream, so a change having been merged to fs2 doesn't help us. (and having both scalaz-stream and fs2 may be desirable for other reasons, anyway, at least for the time being)

**Comment by SethTisue** [comment]
> so we must keep scalaz-stream

but if most future action is on fs2, it may not be worth worrying about unforking, running tests, etc, on this one. which is I why I've unassigned myself

**Comment by SethTisue** [comment]
specs2 dropped their scalaz-stream dependency (by in-sourcing it), so I think this is no longer relevant
