### ISSUE TITLE
javadoc issues in akka

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#251]
fix wip at scala/scala#5304

**Comment by SethTisue** [comment]
5304 was replaced by scala/scala#5322 which has now been merged

**Comment by SethTisue** [comment]
common.conf currently has `-Dakka.genjavadoc.enabled=false`

**Comment by SethTisue** [comment]
fixed by @szeiger in f313974c5e492e5c0ec8681ca1e57769fd6dcaba
