### ISSUE TITLE
Either deprecation in shapeless and -Xfatal-warnings

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#253]

**Comment by SethTisue** [comment]
@milessabin in the 2.12 community build for Shapeless we have:

```
    extra.commands: ${vars.default-commands} [ "removeScalacOptions -Xfatal-warnings" ]
```

there might be other issues besides the Either.left/right deprecation, not sure. I'm not planning to tackle this myself, not sure if you're interested. (not worrying about warnings in a community build context might be acceptable)

**Comment by milessabin** [comment]
I've disabled `-Xfatal-warnings` temporarily in master. I'm fine with it being disabled in the community build for the time being.

**Comment by SethTisue** [comment]
re: the Either.left/right deprecation, you might like to comment at https://github.com/scala/scala/pull/5135#issuecomment-249655722
