### ISSUE TITLE
Mima won't extract on 2.11.x-jdk8 branch, thanks to sbt Build.scala deprecation

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#259]
after the bump to sbt 0.13.12 in #256, e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/201/consoleFull shows:

```
[mima] [info] Compiling 1 Scala source to /home/jenkins/workspace/scala-2.11.x-jdk8-integrate-community-build/target-0.9.5/extraction/0cda10cb88d19cd44580798ecbca9105433b3967/projects/c423b20b83d13ff8543247089ef9b84adc38de44/project/target/scala-2.10/sbt-0.13/classes...
[mima] [error] /home/jenkins/workspace/scala-2.11.x-jdk8-integrate-community-build/target-0.9.5/extraction/0cda10cb88d19cd44580798ecbca9105433b3967/projects/c423b20b83d13ff8543247089ef9b84adc38de44/project/Build.scala:91: trait Build in package sbt is deprecated: Use .sbt format instead
[mima] [error] object MimaBuild extends Build {
[mima] [error]                          ^
[mima] [error] one error found
[mima] [error] (compile:compileIncremental) Compilation failed
```

**Comment by SethTisue** [comment]
switching from Build.scala to build.sbt style is blocked by https://github.com/sbt/sbt/issues/2532

**Comment by dwijnand** [comment]
Why is that fatal?

**Comment by SethTisue** [comment]
it's possible some other way of discovering and running the tests in MiMa's `reporter/functional-tests/src/test` directory could be found. but rather than spend time on it, I'd rather just disable `-Xfatal-warnings` in `project/plugins.sbt` and wait for sbt 1.0

**Comment by SethTisue** [comment]
(especially since this is in the context of Scala community build work, rather in the context of MiMa itself having some burning need to be on a newer sbt version)

**Comment by dwijnand** [comment]
Apologies for shipping a release of sbt with a deprecation without a (full) substitute. My mistake.

**Comment by SethTisue** [comment]
no worries

**Comment by SethTisue** [comment]
new test run now that https://github.com/typesafehub/migration-manager/pull/122 is merged: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/202/consoleFull

**Comment by SethTisue** [comment]
fixed (no change was necessary in this repo, since we're tracking master)
