### ISSUE TITLE
regression: scala-js failing (org.scalajs.testsuite.javalib.util.DateTest)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#261]
at e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/287/console we see:

```
[scala-js] [error] Failed: Total 5238, Failed 1, Errors 0, Passed 5084, Skipped 153
[scala-js] [error] Failed tests:
[scala-js] [error]  org.scalajs.testsuite.javalib.util.DateTest
```

same error on the 2.11/JDK8 build: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/207/console

https://github.com/scala-js/scala-js/pull/2567 seems like a possible culprit

**Comment by sjrd** [comment]
I think this one is our fault, sorry. It seems we made a timezone-dependent test...

**Comment by SethTisue** [comment]
green again: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/288/console
