### ISSUE TITLE
add Scalactic

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#263]
at https://github.com/akka/akka/issues/20306 @szeiger wrote:

> I disabled compilation of some test sources because they require [...] Scalactic

but we really ought to support Scalactic. it's part of the Scalatest repo/build

**Comment by szeiger** [comment]
I already added this to the master ticket https://github.com/scala/scala-dev/issues/203

**Comment by SethTisue** [comment]
fixed in #267
