### ISSUE TITLE
add new sbt+zinc, remove old sbt+zinc

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#264]
typesafehub/zinc is obsolete and we don't need to be building it anymore

and we _should_ be building sbt/zinc, where the action is these days

**Comment by dwijnand** [comment]
I'm going to be working on several aspects from the modules splitting of sbt, so I can do this.

**Comment by dwijnand** [comment]
sbt/zinc depends on a number of dependencies including more sbt modules.

We intend to setup a dbuild for sbt modules (and later plugins) for the purpose ensuring that the latest sbt continues to work (as opposed to the community build which is ensuring the libraries continue to work with changes to Scala).

Once we have that we can start more aggressively making changes across modules in preparation for sbt 1.0, but that might leave moments of cross-module breakages.

As such we wouldn't want to the community build to suffer, so this issue might be open for a while..

**Comment by SethTisue** [comment]
we also discussed this at https://github.com/scala/community-builds/pull/290. summary: tracking sbt 1.0 master is too fragile for now, because of module interdependencies, but we could build from a tag, and then try to remember to push that tag forward from time to time

in particular, it sounds like we can go ahead and add sbt/sbt.git#v1.0.0-M4, along with its modules including sbt/zinc — the tags for the individual modules can be determined by looking at the version numbers in sbt's `project/Dependencies.scala`

**Comment by SethTisue** [comment]
@dwijnand what do you make of these errors:

```
[sbt:error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/extraction/3a1c6f7c2f41d83a27331e50e2b378fbc10a8dff/projects/693975c068ddfe9dc96e007c24e9a8b2b41ed1f8/build.sbt:41: error: value bintrayRepo is not a member of object sbt.Resolver
[sbt:error]   resolvers += Resolver.bintrayRepo("sbt", "maven-releases"),
[sbt:error]                         ^
```

at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/629/consoleFull ?

the changes I was testing are https://github.com/SethTisue/community-builds/commit/93f4fe2f1f678c9515cef209246b8f65c842af3d

it seems like dbuild must be using an old sbt somehow, but I've checked carefully that we're specifying 0.13.12 everywhere, and I see no other evidence in the log that an older version is being used

**Comment by dwijnand** [comment]
It's the very confusing https://github.com/sbt/sbt/issues/1696 which I'm sure you've found.

Haven't looked into why or how it's happening.

**Comment by SethTisue** [comment]
> which I'm sure you've found

yeah I couldn't tell if it was a real issue or just people confused about what version they're running

**Comment by SethTisue** [comment]
sbt 1.0 is now a lot closer to being a reality, so it's time or almost time to proceed with this. I asked @dwijnand about it just now and he agreed. as we already said earlier, it will probably be necessary to use tags rather than track branches.

**Comment by SethTisue** [comment]
PR: #581. interested parties please subscribe
