### ISSUE TITLE
re-add Play to 2.12.x community build for 2.12.0-RC1

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#272]
references:
- https://github.com/playframework/playframework/pull/6432
- https://github.com/adriaanm/twirl/commit/01e1b2de1303711f4a2cd6d5cf998aa9728b0190

**Comment by SethTisue** [comment]
twirl changes submitted upstream: https://github.com/playframework/twirl/pull/118/files

**Comment by SethTisue** [comment]
excluding Play-Streams subproject until akka-stream is added

**Comment by SethTisue** [comment]
play-twirl re-added: https://github.com/scala/community-builds/pull/273; twirl changes submitted upstream: https://github.com/playframework/twirl/pull/118

**Comment by schmitch** [comment]
Actually Play (even core is dependent from akka-stream). Also play, needs play-doc to work against  RC1 first (but that shouldn't be a problem I guess, 2.12.0-M5 worked).

**Comment by schmitch** [comment]
I updated https://github.com/playframework/playframework/pull/6432 to try to build against Scala 2.12.0-RC1 however these are the things I run into when running the tests:

```
[error] key not found: value userForm$1
java.util.NoSuchElementException: key not found: value userForm$1
    at scala.collection.MapLike.default(MapLike.scala:232)
    at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
```

Looks like: https://github.com/scala/scala/pull/5395

---

Then I've run into:

```
[error] /Users/schmitch/projects/schmitch/play/playframework/framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala:249: type mismatch;
[error]  found   : scala.concurrent.ExecutionContext
[error]  required: java.util.concurrent.Executor
[error]           }, ec)
```

Which happens cause the Implicits.global is no more a ExecutionContextProvider and gets down casted to ExecutionContext.
https://issues.scala-lang.org/browse/SI-8849

---

And the rest is probably SAM Types, I guess, only some times?
https://github.com/scala/scala/issues/5307

So for running the whole test suite I need to wait till RC2

**Comment by SethTisue** [comment]
> I need to wait till RC2

because Play is so important in the Scala ecosystem, I would hope you would not wait, if it all possible, since waiting delays discovery of further problems, perhaps necessitating RC3, which we should try very hard to avoid

every commit of every PR against scala/scala, even before it is merged, results in a Scala version being published that you can test against, as described in https://github.com/scala/scala/blob/2.12.x/README.md#scala-ci

**Comment by SethTisue** [comment]
Play-Streams can presumably be re-added now that https://github.com/scala/community-builds/issues/146 is resolved
