### ISSUE TITLE
add scalike-jdbc to community build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#279]
this would have caught https://issues.scala-lang.org/browse/SI-9918

**Comment by seratch** [comment]
Good to hear. If there is anything I can help, please let me know.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/598/console has

```
[scalikejdbc] Running "test" in: syntax-support-macro
[scalikejdbc] [info] Formatting 4 Scala sources {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalikejdbc-f4576e833930d18d9e6284f9b85e13c432540cce/}syntax-support-macro(test) ...
[scalikejdbc] [info] Formatting 19 Scala sources {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalikejdbc-f4576e833930d18d9e6284f9b85e13c432540cce/}core(compile) ...
[scalikejdbc] [info] Reformatted 19 Scala sources {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalikejdbc-f4576e833930d18d9e6284f9b85e13c432540cce/}core(compile).
[scalikejdbc] [info] Compiling 4 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalikejdbc-f4576e833930d18d9e6284f9b85e13c432540cce/scalikejdbc-syntax-support-macro/target/scala-2.12.0-4fa4b83-nightly/test-classes...
[scalikejdbc] scala.reflect.internal.Types$TypeError: type mismatch;
[scalikejdbc]  found   : scalikejdbc.package.SQLSyntaxSupport.type
[scalikejdbc]  required: SQLSyntaxSupportFeature.this.SQLSyntaxSupport.type
[scalikejdbc]   at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1374)
```

as expected, this is SI-9918

**Comment by seratch** [comment]
@SethTisue We've not published for RC1 because we couldn't compile due to SI-9918.

**Comment by SethTisue** [comment]
let's try again with scala/scala@be43eb5: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/599/consoleFull

**Comment by xuwei-k** [comment]
FYI compile and test successful with Scala [`2.12.0-RC1-be43eb5`](http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0-RC1-be43eb5/)
https://github.com/xuwei-k/scalikejdbc/commit/8a48c8fc732d4518635211572ac8f4cae1de72bf

**Comment by SethTisue** [comment]
dammit, there is no scala-be43eb5-nightly, because string of failures at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/, because https://github.com/scala/scala-jenkins-infra/issues/181 . I'll have to come back to this

**Comment by SethTisue** [comment]
oh, but hey wait, there is a `2.12.0-RC1-be43eb5` because Jason wanted to use it as STARR. so, https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/600/consoleFull

**Comment by SethTisue** [comment]
@seratch @xuwei-k any idea what this is about?

```
[scalikejdbc] [info] - should be faster when using TrieMap instead *** FAILED ***
[scalikejdbc] [info]   false did not equal true (SQLInterpolationSpec.scala:954)
```

from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/600/consoleFull

**Comment by seratch** [comment]
@SethTisue The test is a kind of naive micro benchmark code just to verify the benefits of simple cache built with TrieMap. The tests rarely fail on my local mache or Travis CI builds. But I found the test looks too naive. I just omitted the assertions in the test suite. Would you please try the latest again?

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/607/consoleFull (404 temporarily while Jenkins catches up)

**Comment by SethTisue** [comment]
oops, needs specs2 v3. try again: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/609/consoleFull

**Comment by SethTisue** [comment]
@seratch how about this one?

```
[scalikejdbc] [info] - should convert timeZone *** FAILED ***
[scalikejdbc] [info]   "2016-01-09 [19]:43:42" did not equal "2016-01-09 [07]:43:42" (DBSessionSpec.scala:1090)
```

**Comment by SethTisue** [comment]
fixed by #293, but running tests is disabled, unless/until we can sort out the DBSessionSpec/timeZone thing

**Comment by seratch** [comment]
@SethTisue Thanks! After fixing the test failure issue, I'll make a pull request to enable tests for th project.

**Comment by SethTisue** [comment]
> I'll make a pull request to enable tests for th project.

no need, I took care of it in https://github.com/scala/community-builds/pull/303
