### ISSUE TITLE
add kxbmap/configs to community build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#282]
https://github.com/kxbmap/configs

this would have caught [SI-9920](https://issues.scala-lang.org/browse/SI-9920)

cc @kxbmap

**Comment by SethTisue** [comment]
it depends on scalaprops/scalaprops, so we'll need that as well /cc @xuwei-k

**Comment by SethTisue** [comment]
scalaprops wants scalaz 7.2 (it uses `FreeT`). the community build is on 7.1

**Comment by SethTisue** [comment]
scalaprops has a `0.1.x` branch that's on 7.1, but we'll have to see whether configs is source-compatible with it

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/598/console : scalaprops passed, but configs gives

```
[kxbmap-configs] [info] Compiling 40 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/kxbmap-configs-71d33155fabd1277bc8cbcc2de0e12748956fcdf/core/target/scala-2.12.0-4fa4b83-nightly/test-classes...
[kxbmap-configs] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/kxbmap-configs-71d33155fabd1277bc8cbcc2de0e12748956fcdf/core/src/test/scala/configs/DeriveConfigsTest.scala:54: exception during macro expansion: 
[kxbmap-configs] [error] java.lang.NoSuchMethodError: configs.macros.MacroBase.configs$macros$Construct$$defaults$1(Lscala/reflect/api/Symbols$ClassSymbolApi;Lscala/runtime/LazyRef;)Lscala/collection/immutable/Map;
```

EDIT: as expected; that's SI-9920

**Comment by SethTisue** [comment]
I'll return to this after https://github.com/scala/scala/pull/5397 gets merged

**Comment by SethTisue** [comment]
@seratch any idea what this is about?

```
[scalikejdbc] [info] - should be faster when using TrieMap instead *** FAILED ***
[scalikejdbc] [info]   false did not equal true (SQLInterpolationSpec.scala:954)
```

from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/600/consoleFull

**Comment by SethTisue** [comment]
5397 is merged, but now we need to wait for a new 2.12.0 nightly

**Comment by SethTisue** [comment]
we have 2.12.0-5757e04-nightly now. I'll trigger a run on this after https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/694/consoleFull finishes

**Comment by SethTisue** [comment]
test run (with an even newer nightly): https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/700/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
perhaps this will run afoul of https://issues.scala-lang.org/browse/SI-9946, which was just reported a few hours ago

**Comment by SethTisue** [comment]
(The test run is on master. There is also a scala-2.12.0-RC1 branch, but the changes there are limited to Travis changes and library version changes, both irrelevant in the community build context.)

**Comment by SethTisue** [comment]
not sure what to make of this, without digging into the sources:

```
[kxbmap-configs] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/kxbmap-configs-a5cdb974f52a3d86090aae411e4dff5e6a744762/core/src/test/scala/configs/ResultTest.scala:29: configs.Result takes one type parameter, expected: two
[kxbmap-configs] [error]     implicit val instance: MonadError[Result, ConfigError] =
[kxbmap-configs] [error]                                       ^
[kxbmap-configs] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/kxbmap-configs-a5cdb974f52a3d86090aae411e4dff5e6a744762/core/src/test/scala/configs/ResultTest.scala:30: configs.Result takes one type parameter, expected: two
[kxbmap-configs] [error]       new MonadError[Result, ConfigError] {
[kxbmap-configs] [error]                      ^
[kxbmap-configs] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/kxbmap-configs-a5cdb974f52a3d86090aae411e4dff5e6a744762/core/src/test/scala/configs/ResultTest.scala:44: configs.Result takes one type parameter, expected: two
[kxbmap-configs] [error]     scalazlaws.monadError.all[Result, ConfigError]
[kxbmap-configs] [error]                               ^
[kxbmap-configs] [error] three errors found
[kxbmap-configs] [error] (core/test:compileIncremental) Compilation failed
```

@kxbmap any insight?

**Comment by xuwei-k** [comment]
Maybe https://github.com/scalaz/scalaz/pull/1049
- https://github.com/scalaz/scalaz/blob/v7.2.6/core/src/main/scala/scalaz/MonadError.scala#L8
- https://github.com/scalaz/scalaz/blob/v7.1.10/core/src/main/scala/scalaz/MonadError.scala#L3

scalaz 7.2.x

``` scala
trait MonadError[F[_], S]
```

scalaz 7.1.x

``` scala
trait MonadError[F[_,_], E]
```

**Comment by SethTisue** [comment]
ah. the community build is on scalaz 7.1.

well, I've been meaning to add a new, separate dbuild "space" for scalaz 7.2. that would allow us to move to a newer scalaprops as well. I'll do that (not sure how soon)

**Comment by SethTisue** [comment]
this is now much more feasible after #324 (I'd feared multiplying spaces, but perhaps we can afford this one space split now)

**Comment by SethTisue** [comment]
we have scalaz 7.2 now in https://github.com/scala/community-builds/pull/329
