### ISSUE TITLE
regression: scala-js tests fail (missing sources) when building PR-validated Scala (as opposed to nightly Scala)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#284]
so with `scala-abcd123-nightly` it succeeds but with `scala-abcd123-SNAPSHOT` it fails. the former is fine for testing against already-merged PRs, but we commonly need the latter to test PRs that haven't been merged yet

```
[scala-js] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[scala-js] [warn]   ::              FAILED DOWNLOADS            ::
[scala-js] [warn]   :: ^ see resolution messages for details  ^ ::
[scala-js] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[scala-js] [warn]   :: org.scala-lang#scala-library;2.12.0-a919fd7-SNAPSHOT!scala-library.jar(src)
[scala-js] [warn]   :: org.scala-lang#scala-library;2.12.0-a919fd7-SNAPSHOT!scala-library.jar(doc)
[scala-js] [warn]   :: org.scala-lang#scala-compiler;2.12.0-a919fd7-SNAPSHOT!scala-compiler.jar(src)
[scala-js] [warn]   :: org.scala-lang#scala-compiler;2.12.0-a919fd7-SNAPSHOT!scala-compiler.jar(doc)
[scala-js] [warn]   :: org.scala-lang.modules#scala-xml;1.0.5!scala-xml.jar(src)
[scala-js] [warn]   :: org.scala-lang.modules#scala-xml;1.0.5!scala-xml.jar(doc)
[scala-js] [warn]   :: org.scala-lang#scala-reflect;2.12.0-a919fd7-SNAPSHOT!scala-reflect.jar(doc)
[scala-js] [warn]   :: org.scala-lang#scala-reflect;2.12.0-a919fd7-SNAPSHOT!scala-reflect.jar(src)
[scala-js] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by SethTisue** [comment]
@adriaanm I know you hit this, any fix ideas, off the top of your head? (I haven't really thought about it yet, fighting fires elsewhere.).  FYI @sjrd

**Comment by sjrd** [comment]
Scala.js needs the `src` artifacts of `scala-library`, so basically `scala-library-2.11.8-src.jar` or something like that. To get those we use `updateClassifiers`, which apparently also needs the `doc` artifacts not to crash.

I guess the PR validator doesn't publish the `src` and `doc` artifacts, for some reason?

**Comment by dwijnand** [comment]
``` scala
transitiveClassifiers in Global := Seq(Artifact.SourceClassifier) // don't download javadoc
```

to disable downloading docs. (I have it globally as `~/.sbt/0.13/nojavadocs.sbt`)

**Comment by SethTisue** [comment]
I should revisit this, soon, now that #340 and https://github.com/scala-js/scala-js/pull/2606 have been merged.

**Comment by SethTisue** [comment]
my local testing indicates that this is now fixed for scala-js. but let's do a full Jenkins run with a randomly selected recent unmerged 2.12 PR and be sure: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/818/consoleFull (with version=2.12.0-abf0ba2-SNAPSHOT)

**Comment by SethTisue** [comment]
green!
