### ISSUE TITLE
add ssl-config to community build (needed by akka-http)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#292]
needed by akka-http, which I'm trying to build by adding `"akka-http-core", "akka-http-tests"` to extra.projects in the "akka" entry in common.conf

**Comment by SethTisue** [comment]
first hurdle: extraction was failing with

```
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/604/console
[ssl-config:error] com.fasterxml.jackson.databind.JsonMappingException: Required property 'version' is missing.
[ssl-config:error] {}
[ssl-config:error]  ^
[ssl-config:error]  at com.typesafe.dbuild.model.Utils$$anonfun$readValueT$1.apply(Utils.scala:40)
```

the error message and stack trace aren't helpful, since they're caused by no extraction output file having been written at all. how to troubleshoot?

git bisected it and found the first non-working commit in the ssl-config repo, namely https://github.com/typesafehub/ssl-config/pull/2/commits/e779642d020d6dfc53d8a16dea13b61b5476e955 . but @ktoso said that's the first real commit in the project. (but at least we know the cause isn't in some more recent commit)

while researching this, I learned that dbuild extraction works by adding a plugin to the build and then doing something in the plugin's `onLoad`. and lo and behold the ssl-config build overrides `onLoad`. getting rid of that in https://github.com/SethTisue/ssl-config/commit/640e042aac0f383264b6c9a6b73e94ce4d9779d9 got past this hurdle

**Comment by SethTisue** [comment]
next hurdle: there is a circular dependency between akka-actor and ssl-config-akka. dbuild detects this and complains:

```
[error] These items are part of cycles, and are all reachable from each other:
[error]    Project "ssl-config" uses com.typesafe.akka:akka-actor:jar (build level 0, space "default"), which is provided by: "akka".
[error]    Project "akka" uses com.typesafe:ssl-config-akka:jar (build level 0, space "default"), which is provided by: "ssl-config".
[error] The graph is not acyclic.
[error] com.typesafe.dbuild.graph.CycleException: Cycle found
[error]     at com.typesafe.dbuild.graph.Graph.checkCycles(Graphs.scala:90)
[error]     at com.typesafe.dbuild.model.RepeatableDBuildConfig.<init>(RepeatableBuild.scala:153)
```

**Comment by SethTisue** [comment]
fyi @schmitch. while you're working on 2.12 in the Play build directly, I'm working on this, but it's slooooooow going

**Comment by jrudolph** [comment]
Regarding the circular dependency: that's something that @ktoso and I were also discussing some time ago. It would probably make sense to clean this up to move `ssl-config-akka` into akka proper. We are having the same kinds of problems when releasing akka / ssl-config.

**Comment by SethTisue** [comment]
I'll try to work around it in dbuild by putting akka-http in a separate section

**Comment by ktoso** [comment]
Let me know if this blocks you in any way @SethTisue and we'll fix it ASAP.

**Comment by SethTisue** [comment]
I thiiiiiink it's sorted, but I won't know for sure until I finish #146

**Comment by SethTisue** [comment]
done in https://github.com/scala/community-builds/pull/298
