### ISSUE TITLE
2.12 build: try running Play tests

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#304]
at #155 @schmitch said it's worth a try once https://github.com/scala/scala-dev/issues/229 is resolved

**Comment by schmitch** [comment]
after: https://github.com/scala/scala/pull/5423 
also we removed sbt-remote-client: https://github.com/playframework/playframework/commit/12dfb5041372845de9f77b5a215c9aa371953147

So it should be possible to run all sorts of tests, scripted, tests inside documentation and tests inside framework. But most important tests are probably Play-Integration-Tests and Play-WS since they failed on 2.12.0-RC1

**Comment by SethTisue** [comment]
yay, 5423 is merged. but we need to wait a bit now until https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-release-main/ produces a nightly that includes it

**Comment by SethTisue** [comment]
sigh, blocked on https://github.com/sbt/sbt/issues/2758

**Comment by SethTisue** [comment]
we have 2.12.0-5757e04-nightly now. I'll trigger a Play run after https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/694/consoleFull finishes

**Comment by schmitch** [comment]
guess that should work now?

**Comment by SethTisue** [comment]
let's find out

``` diff
-      projects: ["Play"]
+      // TODO: enable more projects? these are just a few that seemed especially high-value
+      projects: ["Play", "Play-Test", "Play-Integration-Test", "Play-WS"]
       exclude: ["SBT-Plugin"]
       directory: "framework"
-      run-tests: false // TODO enable tests
```

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/702/consoleFull

**Comment by schmitch** [comment]
well looks like the generated sources of `scala-java8-compat` aren't working in dbuild?

**Comment by SethTisue** [comment]
```
[play2-core] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/play2-core-207124fe38300250221dc9668a21dc5c0c7ce4ec/framework/src/play-guice/src/main/java/play/inject/guice/GuiceApplicationBuilder.java:17: cannot find symbol
[play2-core] [error]   symbol:   class JFunction
[play2-core] [error]   location: package scala.compat.java8
[play2-core] [error] import static scala.compat.java8.JFunction.func;
[play2-core] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/play2-core-207124fe38300250221dc9668a21dc5c0c7ce4ec/framework/src/play-guice/src/main/java/play/inject/guice/GuiceApplicationBuilder.java:17: static import only from classes and interfaces
[play2-core] [error] import static scala.compat.java8.JFunction.func;
```

**Comment by SethTisue** [comment]
investigating...

**Comment by schmitch** [comment]
no need to, I guess the branch from szeiger is just too old:

https://github.com/szeiger/scala-java8-compat.git#wip/scala-2.12.0-rc1-compat

just try to upgrade it to that: https://github.com/scala/scala-java8-compat

**Comment by SethTisue** [comment]
oh, good catch, I'd forgotten that was forked.

**Comment by SethTisue** [comment]
``` diff
-    uri: "https://github.com/szeiger/scala-java8-compat.git#wip/scala-2.12.0-rc1-compat"
+    uri: "https://github.com/scala/scala-java8-compat.git"
```

new run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/703/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
in Play-Java:

```
[play2-core] java.lang.StackOverflowError
[play2-core]    at scala.tools.nsc.javac.JavaScanners$JavaScanner.putCommentChar(JavaScanners.scala:580)
[play2-core]    at scala.tools.nsc.javac.JavaScanners$JavaScanner.skipBlockComment(JavaScanners.scala:585)
```

**Comment by SethTisue** [comment]
trying again with

``` diff
-      exclude: ["SBT-Plugin"]
+      exclude: [
+        // we don't build sbt plugins
+        "SBT-Plugin"
+        // java.lang.StackOverflowError: at scala.tools.nsc.javac.JavaScanners$JavaScanner.putCommentChar(JavaScanners.scala:580)
+        "Play-Java"
+      ]
```

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/705/consoleFull

**Comment by SethTisue** [comment]
that doesn't work:

```
[play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[play2-core] [warn]     ::          UNRESOLVED DEPENDENCIES         ::
[play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[play2-core] [warn]     :: com.typesafe.play#play-java;2.6.0-dbuildx161e9aade955827b1d0e734c9ef6e23de2fb73f7: not found
[play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
```

@schmitch I'm going to stop fooling with this myself and leave it to you to suggest the next move

**Comment by schmitch** [comment]
well excluding play-java is probably bad since the Integration Tests use it (and actually not included projects will be picked up from dbuild automatically as I've seen).

Actually I ran `Play-Java` against the nightly scala:

```
resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/",
scalaVersion := "2.12.0-1f6006d-SNAPSHOT",
scalaBinaryVersion := "2.12.0-RC1"
```

and it basically works. of course it doesn't recompile every dependency, but that would be too much effort. (I'm under Mac).

Does dbuild use any kind of special `JAVA_OPTS` or `scalac` flags?
Play-Java should probably not fail since most of it is Java only code, only 4 Scala files. So the only reason it might fail is either another dependency which is forked or some wierd javadoc error (when something is enabled which isn't on my machine) or a error that only happens on specific scalac, JAVA_OPTS flags.

What also might be problematic is: `org.specs2:specs2-core:3.6.5` we use 3.8.5 so maybe this version is also a little bit outdated, but since the failure was:

```
[play2-core]    at scala.tools.nsc.javac.JavaScanners$JavaScanner.putCommentChar(JavaScanners.scala:580)
[play2-core]    at scala.tools.nsc.javac.JavaScanners$JavaScanner.skipBlockComment(JavaScanners.scala:585)
```

It's probably not the case..  So I'm a little bit clueless, too.

**Comment by SethTisue** [comment]
dbuild doesn't use any different flags I can think of that might be relevant.

It happens that I'm in the process of upgrading the community build to use specs2 3.8, but I agree it's unlikely to be related.

let's see if it at least passes omitting Play-Integration-Test: ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/720/consoleFull~~ ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/724/consoleFull~~ I'll start a build once I finish some other work

I will come back and investigate the JavaScanners thing a bit later.

**Comment by SethTisue** [comment]
ok ima let this one finish: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/728/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
yay, green. I merged that much in #325

**Comment by SethTisue** [comment]
> I will come back and investigate the JavaScanners thing a bit later

on second thought, I've overspent my time budget on this at this point. I'm going to declare victory for now unless the Play team wants to pursue it further, now or in the future.

it will be easier to revisit, anyway, once all dependencies have published for 2.12.0-RC2 or 2.12.0 final.

**Comment by schmitch** [comment]
@SethTisue actually the master branch for play now has scala 2.12 pulled in, could you try running the tests again? just a single build and see if something breaks?

**Comment by SethTisue** [comment]
sure, I'll put it in my queue. (not right away, because our Jenkins is overloaded right now with both 2.11.9 and 2.12.1 nearing completion)

**Comment by SethTisue** [comment]
@schmitch you're asking for `Play-Integration-Test` to be added, is that correct?

**Comment by schmitch** [comment]
yeah basically, but I guess every test might be running just fine.

**Comment by SethTisue** [comment]
I don't know the structure of Play (I sometimes learn it a little, and then forget again) so I'm not smart about what to add exactly, I have to be told. I'll try adding `Play-Integration-Test` unless you make a different, precise suggestion

**Comment by SethTisue** [comment]
trying `Play-Integration-Test` here: https://github.com/scala/community-builds/pull/425
