### ISSUE TITLE
Easily switch between freezing projects in time / building HEAD

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#342]
When converging on a Scala release, we can't afford to have one core project add one commit and turn the community build into a 7hr nail-biting affair.

**Comment by adriaanm** [comment]
To turn the repeatable build json into a list of URIs, extract the JSON between

```
[info] You can repeat this build (except for -SNAPSHOT references) using this configuration:
```

and

```
[info] ---== End Repeatable dbuild Configuration ===---
```

save it as rep.json and:

```
cat rep.json | jq -re '.build.projects[] | "\(.name)-uri: \"\(.uri)\""' 
```

**Comment by SethTisue** [comment]
dupe of #338 ?

**Comment by adriaanm** [comment]
yep, I'll move my comment  over
