### ISSUE TITLE
regression: simulacrum failing in 2.12 build since wartremover was added

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#347]
looks like wartremover adds itself to `libraryDependencies` which then confuses dbuild?

wartremover was added in mpilquist/simulacrum#68

it looks like the same fundamental problem (with sbt plugins that need access to the project Scala instead of Scala 2.10) as with scalafmt discussed at https://github.com/scala/community-builds/pull/341

**Comment by SethTisue** [comment]
I was able to work around the scalafmt issue with:

```
    check-missing: false
    deps.ignore: [
      "com.geirsson#scalafmt-cli"
      "com.geirsson#scalafmt"
    ]
```

probably the same trick would work here

**Comment by SethTisue** [comment]
it didn't, I don't know why, and another attempt:

```
    extra.settings: [
      "libraryDependencies in coreJVM := (libraryDependencies in coreJVM).value.filterNot(_.name == \"wartremover\")"
     ]
```

failed with:

```
[simulacrum:error] /Users/tisue/community.212/target-0.9.5/extraction/9d8fb794701d979faced9442c9e6afcea96c9b51/projects/bb7380904b8b6c5ff8a3183058262fa514615b31/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1: error: not found: value coreJVM
[simulacrum:error] libraryDependencies in coreJVM     := (libraryDependencies in coreJVM)     .value.filterNot(_.name == "wartremover")
[simulacrum:error]                        ^
```

I'm stuck. @cunei @dwijnand any ideas?

fyi @mpilquist

**Comment by dwijnand** [comment]
Try:

``` scala
extra.settings: [
  "libraryDependencies in LocalProject(\"coreJVM\") ~= (_.filterNot(_.name == \"wartremover\"))"
]
```

**Comment by SethTisue** [comment]
@dwijnand thanks, that made the compile error go away, but it also didn't make dbuild/sbt stop complaining about the missing dependency, either :-/

I'll see if I can satisfy it by pulling down some wartremover jar using aether — hopefully it won't even really matter much what's in the jar

**Comment by SethTisue** [comment]
dammit, that won't work, wartremover is actually getting run, so of course not having a compatible JAR causes errors:

```
[simulacrum] java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
[simulacrum]    at org.wartremover.WartTraverser.$anonfun$isWartAnnotation$1(WartTraverser.scala:70)
[simulacrum]    at org.wartremover.WartTraverser.$anonfun$isWartAnnotation$1$adapted(WartTraverser.scala:69)
```

**Comment by SethTisue** [comment]
hmm

> the WartRemover SBT plugin sets scalac options - make sure you're not overwriting those by having a scalacOptions := ... setting in your SBT settings. Use scalacOptions ++= ... instead

that sounds like an opening

we need to nuke e.g. `-Xplugin:/Users/tisue/.ivy2/cache/org.wartremover/wartremover_2.11/jars/wartremover_2.11-1.1.1.jar`

**Comment by SethTisue** [comment]
new, non-simulacrum-specific ticket is #364. I could use community help with this one, I burned too much time on it already
