### ISSUE TITLE
upgrade to sbt 0.13.13

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#352]
@dwijnand @eed3si9n before 0.13.13 final is released, should we a run a community build using 0.13.13-RC3, to help ensure that the new version isn't breaking people's builds?

**Comment by dwijnand** [comment]
Yes please, I was going to do that today then it slipped my mind.

If you don't get round to it today your time I'll take a shot at doing it tomorrow my time.

**Comment by SethTisue** [comment]
(I wouldn't get to it until after #280)

**Comment by dwijnand** [comment]
#354 on 2.12.x was a success

#358 testing on the 2.11.x build projects

**Comment by dwijnand** [comment]
Ok looks like 0.13.13-RC3 is good.

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/pull/371

**Comment by dwijnand** [comment]
BTW I was keeping this open for the final 0.13.13 upgrade.

**Comment by SethTisue** [comment]
it's all yours :-)
