### ISSUE TITLE
somehow accommodate projects that are using wartremover

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#364]
this came up in the context of #347 / https://github.com/scala/community-builds/pull/355 (unfreezing simulacrum)

it would be super awesome if somebody else could figure this out, I already burned too much time on it

**Comment by SethTisue** [comment]
relocated @milessabin comment:

> Given that wartremover is a linter, wouldn't it be better to patch the projects to disable it rather than freeze them? Also, are the upstream projects aware of the issue with wartremover and the freezing?

if someone could find a way to disable it just using `extra.commands`, without having to fork, that would be awesome

upstream projects are aware if I @-mention them at fork or freeze time, which I uuuusually do. we don't have a good system for this

**Comment by SethTisue** [comment]
maybe the wartremover folks could use the approach taken by scalafmt at https://github.com/olafurpg/scalafmt/pull/610 (and succinctly described at https://github.com/sbt/sbt/issues/2786#issuecomment-261773807)? (I haven't studied it enough to know whether this is plausible)  they would have to require sbt 0.13.13, which is when the synthetic-project support was added

**Comment by olafurpg** [comment]
FWIW, I use synthetic projects in the scalafix compiler plugin which may be closer to wartremover's situation. See [here](https://github.com/scalacenter/scalafix/blob/89587b55ea931fc251842705b17b49b7afa25fae/scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L34-L49) for how I deal with 2.11 and 2.12. A synthetic project is needed for each supported scala version. A nice side-effect to this is that `update` is cached on the synthetic projects, which makes resolution faster for multi-project build (esp. scala.js cross-projects in combination with SNAPSHOT versions)

**Comment by SethTisue** [comment]
this hasn't been a problem lately. we still have simulacrum frozen over it, but it hasn't caused problems with any other projects in a long time. (for all I know, some newer wartremover version may even have eased the problem.) we can reopen if needed

**Comment by SethTisue** [comment]
hit this recently adding a project (curryhoward) that has wartremover 2.2.1 which is the latest version, so there hasn't been a fix.

**Comment by SethTisue** [comment]
#698 adds wartremover to the build, fixing the problem
