### ISSUE TITLE
add japgolly libraries to 2.12 build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#368]
nyaya, and maybe others? this would have caught scala/scala-dev#248

prompted by https://groups.google.com/d/msg/scala-internals/LGRU1gEwRgQ/_28LI2jUBAAJ

@japgolly let's discuss

**Comment by japgolly** [comment]
Ok considering the Eligibility page, I think it'd be a good idea to add this subset of my libraries to the community build:
- [nyaya](https://github.com/japgolly/nyaya)
- [test-state](https://github.com/japgolly/test-state)
- [univeq](https://github.com/japgolly/univeq) (required for test-state and scalacss)
- _[scalacss](https://github.com/japgolly/scalacss) (maybe)_

**Comment by SethTisue** [comment]
ok, I'll pile all of that into the same PR and we'll see how much trouble we run into.

**Comment by japgolly** [comment]
Oh you're creating those PRs @SethTisue? Thanks! What do I need to do, if anything?

**Comment by SethTisue** [comment]
lets talk specifics at https://github.com/scala/community-builds/pull/370. I'll close this ticket, actually, since some form of the PR will surely be merged
