### ISSUE TITLE
make a 2.13.x community build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#386]
* [x] make the needed Jenkins changes (done, thx @adriaanm)
* [x] add a 2.13.x tab in the Jenkins UI
* [x] create and push a `2.13.x` branch in this repo
* [x] see if a test run succeeds
* [x] update the documentation
* [ ] consider disk space needs — do we need more room on the behemoths?

**Comment by SethTisue** [comment]
first run now that branch exists: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/7/consoleFull

EDIT: mostly succeeded, similar failures exist in the 2.12.x build currently

**Comment by SethTisue** [comment]
@adriaanm I suspect we're going to need more disk space on the behemoths for this

**Comment by SethTisue** [comment]
doc updated in wiki.

I recently merged a bunch of changes onto 2.12.x, then merged 2.12.x onto 2.13.x. a 2.13.x test run seems to be doing well so far: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/53/console . if there are failures I'll open individual tickets.

if disk space proves to be a problem, I'll open a new ticket on it when the time comes.

**Comment by SethTisue** [comment]
first completely green 2.13 run! https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/58/

**Comment by adriaanm** [comment]
:tada:

**Comment by SethTisue** [comment]
Dotty exiting (https://github.com/scala/scala-jenkins-infra/issues/205) may relieve the disk space situation

**Comment by SethTisue** [comment]
once we changed the Scala version number on the 2.13.x branch to 2.13.0, some projects broke.

I submitted upstream PRs on all failing non-leaf projects with the needed (trivial) changes. so we are now back to all green except for about 5 or 6 leaf projects (that is, projects which other projects in the build don't depend on)

I'm content to leave the leaf projects alone for now. after all, soon enough we'll start making breaking changes to Scala, and knows what kind of hell will break loose then :-)

**Comment by SethTisue** [comment]
well hmm, maybe I should comment out those leaf projects, just to get the build nominally green so that the 2.13 release-main job can proceed

**Comment by adriaanm** [comment]
The minimal fix will do here -- 2.13 is still a bit green itself anyway :-)

**Comment by SethTisue** [comment]
failing leaves commented out in 56a8cca4de89cec81228f4ff50ba97f04e84ea5c
