### ISSUE TITLE
regression (2.12.x): akka-http fails to extract

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#400]
reported by @milessabin

at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/950/consoleFull we see

```
[akka-http] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[akka-http] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[akka-http] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[akka-http] [warn] 	:: me.lessis#bintray-sbt;0.3.0-8-g6d0c3f8: not found
[akka-http] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
...
[info] Project akka-http---------------: EXTRACTION FAILED (RuntimeException: )
```
 
the responsible commit is https://github.com/akka/akka-http/commit/45bc1d6049f82fa25f59c945aed2c61bd6d91433 — it adds a dependency on a custom build of sbt-bintray, retrieved from a special resolver. our Artifactory doesn't have that resolver, so the build fails.

I'm a bit reluctant to add the resolver, since the whole thing looks like some kind of stopgap measure rather than something that will be kept? @2m, can you comment?

**Comment by dwijnand** [comment]
I believe it's a custom build including https://github.com/softprops/bintray-sbt/pull/69.

**Comment by 2m** [comment]
As @dwijnand has already identified, it is a `bintray-sbt` release of that PR, which adds support for credential resolving from Travis environment variables seamless.

How do we fix this? Can we make community build not ignore custom resolvers?

**Comment by dwijnand** [comment]
I assume that dbuild ignores custom resolvers for good reason.

I think the solution needs to be upstream. Either:

* in akka-http, use the official release of bintray-sbt, perhaps use [my workaround](https://github.com/softprops/bintray-sbt/pull/69#issuecomment-261621992) if the purpose is to pass credentials on Travis CI
* in bintray-sbt, revise the PR to something less controvertial or otherwise difficult to merge (eg. no extra keys, no sys props, just use an env var if found) so it can go in and be released

**Comment by SethTisue** [comment]
> I assume that dbuild ignores custom resolvers for good reason.

I don't know about dbuild _in general_ (@cunei would know the history on that)...

...but in the community build specifically, we want dbuild contacting resolvers out there on the Internet as little as possible, for performance reasons. it should get stuff from our Artifactory instance (https://scala-ci.typesafe.com/artifactory/). so we could solve this by adding Martynas's resolver there.

**Comment by SethTisue** [comment]
I'll just go ahead and add Martynas's resolver to our Artifactory.

Here's a (very!) recent example where @softprops handed over the keys to one of his projects: https://github.com/unfiltered/unfiltered/issues/320. Perhaps this could happen on bintray-sbt as well.

**Comment by SethTisue** [comment]
> I'll just go ahead and add Martynas's resolver to our Artifactory.

done
