### ISSUE TITLE
add monix as a good source of macro regression backstops

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#414]
it caught e.g. SI-10009

https://github.com/monix/monix/blob/cff18e4f19559a56a0f984016c3da640368c7139/monix-execution/shared/src/main/scala_2.11/monix/execution/schedulers/ExecuteMacros.scala

(inferred from the reproduction in https://gist.github.com/alexandru/26400bfc6209d4884d9cc916ad48d196)

**Comment by SethTisue** [comment]
fyi @alexandru

**Comment by SethTisue** [comment]
the cats part of this will have to wait until we have cats-laws, which we can't have until we move from ScalaCheck 1.12 to 1.13 (that's #13)
