### ISSUE TITLE
override project MiMa versions to use latest

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#418]
lots of projects out there are using antiquated MiMa versions. It would improve the MiMa testing situation greatly if the community build overrode that and forced the latest binary release to be used

EDIT: or as Dale suggests, build MiMa from source and use that

**Comment by SethTisue** [comment]
@dwijnand:

> the alternative is to re-introduce sbt-mima-plugin as a source dependency into the community build

>so even before mima is cut we dog-food and test

we used to build all sbt plugins. that was before my time, Adriaan got rid of that right around the time I started. not sure offhand what it would take to bring that back but only for certain plugins

**Comment by SethTisue** [comment]
I don't think I'm ever going to tackle this, and it's not clear that the community build is the right venue for tackling it, anyway.

**Comment by dwijnand** [comment]
Indeed, the community build should serve scala/scala's needs not mima's.
