### ISSUE TITLE
Akka: track release-2.4 branch, not master

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#421]
master is 2.5, and my guess is that breakages like https://github.com/scala/community-builds/issues/416 and https://github.com/playframework/playframework/issues/6773 and https://github.com/akka/akka-http/issues/606 are likely to recur, and I can't afford to spend time chasing them down

at the moment the whole community build is frozen while we put the finishing touches on Scala 2.12.1. I'll take care of this at the time we unfreeze

**Comment by SethTisue** [comment]
fyi @ktoso @patriknw

**Comment by SethTisue** [comment]
fixed by #429, but unfortunately I had to fork akka-http because of #430

**Comment by ktoso** [comment]
Thanks, watching #430 then.
