### ISSUE TITLE
unfork ScalaMock, it is being maintained again

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#427]
and has 2.12 support now too

as per https://github.com/paulbutcher/ScalaMock/pull/155#issuecomment-261709667

fyi @paulbutcher @barkhorn thanks & kudos to both of you for reanimating ScalaMock

I will give this a try and let you know if I need anything.

**Comment by SethTisue** [comment]
fixed by #429. unfortunately I had to fork because of #430

**Comment by barkhorn** [comment]
If i read this right, this is more of a problem with dbuild publish overrides than with the Scalamock build?
Still, if you have suggestions how to allow you to build this without a fork, let me know.

**Comment by SethTisue** [comment]
Correct, and I don't know another workaround
