### ISSUE TITLE
deal with remaining forks

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#439]
done:
- [x] monix/minitest
  - upstream PR: https://github.com/monix/minitest/pull/4
- [x] specs2
  - upstream PR (Jan 9 2017): https://github.com/etorreborre/specs2/pull/532
- [x] catalysts
  - upstream PR (Jan 9 2017): https://github.com/typelevel/catalysts/pull/10

pending:
- [ ] scala-ssh
  - upstream PR: https://github.com/veact/scala-ssh/pull/5
  - but maybe it's fine to just keep tracking @xuwei-k's fork

forked because of Coursier:
- [ ] fastparse
  - issue: https://github.com/scala/community-builds/issues/294

forked only because of bintray-sbt (typesafehub/dbuild#158):

* active: akka-contrib-extra, akka-http, akka-sse, scalamock
* moribund: sbinary, sbt-testng

list is up to date as of: December 14, 2016

a previous round of work on this was done in #322

**Comment by SethTisue** [comment]
current forks:

```
project-refs.conf:  akka-contrib-extra-uri:       "https://github.com/scalacommunitybuild/akka-contrib-extra.git#community-build-2.12"
project-refs.conf:  akka-http-uri:                "https://github.com/scalacommunitybuild/akka-http.git#community-build-2.12"
project-refs.conf:  akka-sse-uri:                 "https://github.com/scalacommunitybuild/akka-sse.git#community-build-2.12"
project-refs.conf:  fastparse-uri:                "https://github.com/scalacommunitybuild/fastparse.git#no-coursier"
project-refs.conf:  minitest-uri:                 "https://github.com/scalacommunitybuild/minitest.git#community-build-2.12"
project-refs.conf:  sbinary-uri:                  "https://github.com/scalacommunitybuild/sbinary.git#community-build-2.12"
project-refs.conf:  sbt-testng-uri:               "https://github.com/scalacommunitybuild/sbt-testng.git#community-build-2.12"
project-refs.conf:  scalamock-uri:                "https://github.com/scalacommunitybuild/ScalaMock.git#community-build-2.12"
```

**Comment by SethTisue** [comment]
I should probably expand this list to include freezes, which are just a degenerate case of forking, really

**Comment by BennyHill** [comment]
Catalysts done - sorry for the delay

**Comment by SethTisue** [comment]
@BennyHill I'll submit an unforking PR shortly

**Comment by SethTisue** [comment]
I've opened https://github.com/scala/community-builds/issues/629 on the coursier situation

**Comment by SethTisue** [comment]
the number of remaining forks is not that great, and having some freezes is not so bad, either. let's declare victory. the current state of things good enough, overall. we can continue to evaluate individual cases individually
