### ISSUE TITLE
run weekly 2.12.x community build with optimizer enabled

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#442]

**Comment by SethTisue** [comment]
we don't have enough disk space on the Jenkins nodes for this at present. (and they aren't easy to expand, they would need to be rebuilt)

**Comment by SethTisue** [comment]
we have plenty of disk space now, since the recent big Jenkins overhaul

**Comment by SethTisue** [comment]
this is a longstanding todo that never seems to rise to top of anybody's priority list. closing, but happy to reopen if someone considers it a priority
