### ISSUE TITLE
regression: Play fails to compile in 2.11.x-jdk8 build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#444]
as seen at https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/318/consoleFul

@gmethvin perhaps https://github.com/playframework/playframework/commit/8cffd51aeb8a35e59406c1dcb99e136cb5689fce ...?

**Comment by gmethvin** [comment]
well it looks like the failing line of code is:
```scala
Configuration.configError(if (underlying.hasPath(path)) underlying.getValue(path).origin else underlying.root.origin, message, e)
```
But the code on master looks correct: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Configuration.scala#L984

**Comment by SethTisue** [comment]
what about on the 2.4.x branch? that's the branch the 2.11.x-jdk8 build uses, and the branch the commit I linked to is on

**Comment by schmitch** [comment]
Same error is on the 2.5.x branch btw: https://github.com/playframework/playframework/pull/6839/commits/c6312f15e929949283dc4cbb42a237e4b0b0d55b

**Comment by gmethvin** [comment]
Okay I see what happened. Looks like we backported and missed one of the uses of that method.

**Comment by SethTisue** [comment]
green at https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/319/, so I guess this is fixed. thanks @gmethvin!

**Comment by gmethvin** [comment]
Yes it's fixed now.
