### ISSUE TITLE
Run the community builds with a locally published version of Scala

### ISSUE THREAD

**Issue by julienrf** [scala/community-builds#456]
My goal is to evaluate the impact of a change in the scala-library on user code. Here is what I did:

- [Changed](https://github.com/scala/scala/compare/2.12.x...julienrf:remove-mutable-views) the scala-library ;
- Run the following sbt incantations (based on [this](https://github.com/scala/scala#using-the-sbt-build))
  - ~~~
    > dist/mkPack`
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}library...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}bootstrap...
    [info] Done updating.
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}reflect...
    [info] Resolving org.scala-lang#scala-library;2.12.2-SNAPSHOT ...
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}compiler...
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}scaladoc...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}interactive...
    [info] Resolving org.scala-lang#scala-compiler;2.12.2-SNAPSHOT ...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}scalap...
    [info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
    [info] Done updating.
    [info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
    [info] Done updating.
    [info] Resolving org.apache.ant#ant-launcher;1.9.4 ...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl...
    [info] Resolving org.scala-sbt#test-interface;1.0 ...
    [info] Done updating.
    [info] Resolving org.scala-lang#scala-compiler-interactive;2.12.2-SNAPSHOT ...
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl-jline...
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl-jline-embedded...
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done updating.
    [info] Packaging /home/julien/workspace/dev/scala/scala/build/pack/lib/scalap.jar ...
    [info] Done packaging.
    [info] Packaging /home/julien/workspace/dev/scala/scala/build/pack/lib/scala-compiler-doc.jar ...
    [info] Packaging /home/julien/workspace/dev/scala/scala/build/pack/lib/scala-repl-jline.jar ...
    [info] Done packaging.
    [info] Done packaging.
    [info] Creating scripts in /home/julien/workspace/dev/scala/scala/build/quick/bin and /home/julien/workspace/dev/scala/scala/build/pack/bin
    [info] Packaging /home/julien/workspace/dev/scala/scala/build/pack/lib/scala-repl-jline-embedded.jar ...
    [info] Done packaging.
    [warn] bnd: Version for package scala.tools.asm is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.commons is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.signature is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.tree is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.tree.analysis is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.util is set to different values in the source (2.12.2.v20170109-163910-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Invalid package name: 'repl-jline.properties'
    [warn] bnd: Invalid package name: 'scala-asm.properties'
    [warn] bnd: Invalid package name: 'scala-buildcharacter.properties'
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}dist...
    [info] Resolving org.scala-lang.modules#scala-swing_2.12;2.0.0-M2 ...
    [info] Done updating.
    [success] Total time: 14 s, completed Jan 11, 2017 11:06:47 AM
    ~~~
  - ~~~
    > set baseVersionSuffix := "remove-mutable-views-SNAPSHOT"
    [info] Defining root/*:baseVersionSuffix
    [info] The new value will be used by */*:versionProperties
    [info] Reapplying settings...
    [info] *** Welcome to the sbt build definition for Scala! ***
    [info] Check README.md for more information.
    ~~~
  - ~~~
    > set publishArtifact in (Compile, packageDoc) in ThisBuild := false
    [info] Defining {.}/compile:packageDoc::publishArtifact
    [info] The new value will be used by bootstrap/*:artifacts, bootstrap/*:packagedArtifacts and 9 others.
    [info] 	Run `last` for details.
    [info] Reapplying settings...
    [info] *** Welcome to the sbt build definition for Scala! ***
    [info] Check README.md for more information.
    ~~~
  - ~~~
    > publishLocal
    [info] Packaging /home/julien/workspace/dev/scala/scala/target/scalap/scalap-2.12.2-remove-mutable-views-SNAPSHOT-sources.jar ...
    [info] Packaging /home/julien/workspace/dev/scala/scala/target/compiler/scala-compiler-2.12.2-remove-mutable-views-SNAPSHOT-sources.jar ...
    [info] Packaging /home/julien/workspace/dev/scala/scala/target/reflect/scala-reflect-2.12.2-remove-mutable-views-SNAPSHOT-sources.jar ...
    [info] Packaging /home/julien/workspace/dev/scala/scala/target/library/scala-library-2.12.2-remove-mutable-views-SNAPSHOT-sources.jar ...
    [info] Done packaging.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}library...
    [info] Done updating.
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/library/scala-library-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}manual...
    [info] Resolving org.scala-lang#scala-library;2.12.1 ...
    [info] Done packaging.
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}bootstrap...
    [info] Resolving jline#jline;2.14.1 ...
    [info] :: delivering :: org.scala-lang#scala-library;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:41 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/library/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}reflect...
    [info] Resolving org.scala-lang#scala-library;2.12.2-remove-mutable-views-SNAPSHOT ...
    [info] Done updating.
    [info] Done packaging.
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/reflect/scala-reflect-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [info] :: delivering :: org.scala-lang#scala-reflect;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:41 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/reflect/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}library-all...
    [info] Resolving org.scala-lang.modules#scala-swing_2.12;2.0.0-M2 ...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}compiler...
    [info] Done updating.
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done packaging.
    [info] Done updating.
    [warn] Skipped generating '<exclusion/>' for org.scala-lang#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
    [warn] Skipped generating '<exclusion/>' for org.scala-lang#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
    [warn] Skipped generating '<exclusion/>' for org.scala-lang#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/library-all/scala-library-all-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [warn] Skipped generating '<exclusion/>' for org.scala-lang#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/compiler/scala-compiler-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [info] :: delivering :: org.scala-lang#scala-library-all;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:41 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/library-all/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] :: delivering :: org.scala-lang#scala-compiler;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:41 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/compiler/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}scalap...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}scaladoc...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}interactive...
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/scalap/scalap-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [info] Resolving org.scala-lang#scala-library;2.12.2-remove-mutable-views-SNAPSHOT ...
    [info] Done updating.
    [info] Resolving org.scala-lang#scala-library;2.12.2-remove-mutable-views-SNAPSHOT ...
    [info] Done updating.
    [info] Resolving org.scala-sbt#test-interface;1.0 ...
    [info] Done updating.
    [info] 	published scala-library-all to /home/julien/.ivy2/local/org.scala-lang/scala-library-all/2.12.2-remove-mutable-views-SNAPSHOT/poms/scala-library-all.pom
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scala-library-all/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [info] Running scala.tools.docutil.ManMaker fsc, scala, scalac, scaladoc, scalap /home/julien/workspace/dev/scala/scala/target/scala-dist/resource_managed/main/doc/tools /home/julien/workspace/dev/scala/scala/target/scala-dist/resource_managed/main/genman
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl...
    [info] Wrote /home/julien/workspace/dev/scala/scala/target/scala-dist/scala-dist-2.12.2-remove-mutable-views-SNAPSHOT.pom
    [info] Resolving org.scala-lang#scala-compiler-interactive;2.12.2-remove-mutable-views-SNAPSHOT ...
    [info] Done updating.
    [info] :: delivering :: org.scala-lang#scalap;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:41 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/scalap/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}scala-dist...
    [info] Resolving jline#jline;2.14.1 ...
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl-jline...
    [info] Done updating.
    [info] Resolving jline#jline;2.14.1 ...
    [info] :: delivering :: org.scala-lang#scala-dist;2.12.2-remove-mutable-views-SNAPSHOT :: 2.12.2-remove-mutable-views-SNAPSHOT :: integration :: Wed Jan 11 11:15:42 CET 2017
    [info] 	delivering ivy file to /home/julien/workspace/dev/scala/scala/target/scala-dist/ivy-2.12.2-remove-mutable-views-SNAPSHOT.xml
    [info] Done updating.
    [info] Updating {file:/home/julien/workspace/dev/scala/scala/}repl-jline-embedded...
    [info] Resolving jline#jline;2.14.1 ...
    [info] Done updating.
    [info] Packaging /home/julien/workspace/dev/scala/scala/build/pack/lib/scalap.jar ...
    [info] Done packaging.
    [info] 	published scalap to /home/julien/.ivy2/local/org.scala-lang/scalap/2.12.2-remove-mutable-views-SNAPSHOT/poms/scalap.pom
    [info] 	published scalap to /home/julien/.ivy2/local/org.scala-lang/scalap/2.12.2-remove-mutable-views-SNAPSHOT/jars/scalap.jar
    [info] 	published scalap to /home/julien/.ivy2/local/org.scala-lang/scalap/2.12.2-remove-mutable-views-SNAPSHOT/srcs/scalap-sources.jar
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scalap/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [info] Creating scripts in /home/julien/workspace/dev/scala/scala/build/quick/bin and /home/julien/workspace/dev/scala/scala/build/pack/bin
    [info] Packaging /home/julien/workspace/dev/scala/scala/target/scala-dist/scala-dist-2.12.2-remove-mutable-views-SNAPSHOT.jar ...
    [info] Done packaging.
    [info] 	published scala-dist to /home/julien/.ivy2/local/org.scala-lang/scala-dist/2.12.2-remove-mutable-views-SNAPSHOT/poms/scala-dist.pom
    [info] 	published scala-dist to /home/julien/.ivy2/local/org.scala-lang/scala-dist/2.12.2-remove-mutable-views-SNAPSHOT/jars/scala-dist.jar
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scala-dist/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [info] 	published scala-library to /home/julien/.ivy2/local/org.scala-lang/scala-library/2.12.2-remove-mutable-views-SNAPSHOT/poms/scala-library.pom
    [info] 	published scala-library to /home/julien/.ivy2/local/org.scala-lang/scala-library/2.12.2-remove-mutable-views-SNAPSHOT/jars/scala-library.jar
    [info] 	published scala-library to /home/julien/.ivy2/local/org.scala-lang/scala-library/2.12.2-remove-mutable-views-SNAPSHOT/srcs/scala-library-sources.jar
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scala-library/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [warn] bnd: Version for package scala.tools.asm is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.commons is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.signature is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.tree is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.tree.analysis is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Version for package scala.tools.asm.util is set to different values in the source (2.12.2.v20170109-163910-remove-mutable-views-SNAPSHOT-135d82a) and in the manifest (5.1.0.scala-1). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
    [warn] bnd: Invalid package name: 'repl-jline.properties'
    [warn] bnd: Invalid package name: 'scala-asm.properties'
    [warn] bnd: Invalid package name: 'scala-buildcharacter.properties'
    [info] 	published scala-compiler to /home/julien/.ivy2/local/org.scala-lang/scala-compiler/2.12.2-remove-mutable-views-SNAPSHOT/poms/scala-compiler.pom
    [info] 	published scala-compiler to /home/julien/.ivy2/local/org.scala-lang/scala-compiler/2.12.2-remove-mutable-views-SNAPSHOT/jars/scala-compiler.jar
    [info] 	published scala-compiler to /home/julien/.ivy2/local/org.scala-lang/scala-compiler/2.12.2-remove-mutable-views-SNAPSHOT/srcs/scala-compiler-sources.jar
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scala-compiler/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [info] 	published scala-reflect to /home/julien/.ivy2/local/org.scala-lang/scala-reflect/2.12.2-remove-mutable-views-SNAPSHOT/poms/scala-reflect.pom
    [info] 	published scala-reflect to /home/julien/.ivy2/local/org.scala-lang/scala-reflect/2.12.2-remove-mutable-views-SNAPSHOT/jars/scala-reflect.jar
    [info] 	published scala-reflect to /home/julien/.ivy2/local/org.scala-lang/scala-reflect/2.12.2-remove-mutable-views-SNAPSHOT/srcs/scala-reflect-sources.jar
    [info] 	published ivy to /home/julien/.ivy2/local/org.scala-lang/scala-reflect/2.12.2-remove-mutable-views-SNAPSHOT/ivys/ivy.xml
    [success] Total time: 9 s, completed Jan 11, 2017 11:15:49 AM
    ~~~
- Finally, I ran the community builds (only for specs2 for brevity):
  - ~~~
    $ version=2.12.2-remove-mutable-views-SNAPSHOT JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ./run.sh specs2
    …
    [info] ---==  Execution Report ==---
    [info] Report from the dbuild run for dbuild: 
    [info] Project acyclic-----------------: EXTRACTION OK, but could not proceed
    [info] Project akka--------------------: EXTRACTION OK, but could not proceed
    [info] Project akka-contrib-extra------: EXTRACTION OK, but could not proceed
    [info] Project akka-http---------------: EXTRACTION OK, but could not proceed
    [info] Project akka-more---------------: EXTRACTION OK, but could not proceed
    [info] Project akka-sse----------------: EXTRACTION OK, but could not proceed
    [info] Project argonaut----------------: EXTRACTION OK, but could not proceed
    [info] Project async-------------------: EXTRACTION OK, but could not proceed
    [info] Project atto--------------------: EXTRACTION OK, but could not proceed
    [info] Project blaze-------------------: EXTRACTION OK, but could not proceed
    [info] Project catalysts---------------: EXTRACTION OK, but could not proceed
    [info] Project cats--------------------: EXTRACTION OK, but could not proceed
    [info] Project conductr-lib------------: EXTRACTION OK, but could not proceed
    [info] Project discipline--------------: EXTRACTION OK, but could not proceed
    [info] Project dispatch----------------: EXTRACTION OK, but could not proceed
    [info] Project fansi-------------------: EXTRACTION OK, but could not proceed
    [info] Project fastparse---------------: EXTRACTION OK, but could not proceed
    [info] Project fs2---------------------: EXTRACTION OK, but could not proceed
    [info] Project fs2-cats----------------: EXTRACTION OK, but could not proceed
    [info] Project genjavadoc--------------: EXTRACTION OK, but could not proceed
    [info] Project http4s------------------: EXTRACTION OK, but could not proceed
    [info] Project http4s-websocket--------: EXTRACTION OK, but could not proceed
    [info] Project jackson-module-scala----: EXTRACTION OK, but could not proceed
    [info] Project jawn--------------------: EXTRACTION OK, but could not proceed
    [info] Project jawn-fs2----------------: EXTRACTION OK, but could not proceed
    [info] Project json4s------------------: EXTRACTION OK, but could not proceed
    [info] Project kind-projector----------: EXTRACTION OK, but could not proceed
    [info] Project kxbmap-configs----------: EXTRACTION OK, but could not proceed
    [info] Project lift-json---------------: EXTRACTION OK, but could not proceed
    [info] Project log4s-------------------: EXTRACTION OK, but could not proceed
    [info] Project machinist---------------: EXTRACTION OK, but could not proceed
    [info] Project macro-compat------------: EXTRACTION OK, but could not proceed
    [info] Project macro-paradise----------: EXTRACTION OK, but could not proceed
    [info] Project mima--------------------: EXTRACTION OK, but could not proceed
    [info] Project minitest----------------: EXTRACTION OK, but could not proceed
    [info] Project monix-------------------: EXTRACTION OK, but could not proceed
    [info] Project monocle-----------------: EXTRACTION OK, but could not proceed
    [info] Project nyaya-------------------: EXTRACTION OK, but could not proceed
    [info] Project parboiled---------------: EXTRACTION OK, but could not proceed
    [info] Project parboiled2--------------: EXTRACTION OK, but could not proceed
    [info] Project pcplod------------------: EXTRACTION OK, but could not proceed
    [info] Project play-core---------------: EXTRACTION OK, but could not proceed
    [info] Project play-doc----------------: EXTRACTION OK, but could not proceed
    [info] Project play-json---------------: EXTRACTION OK, but could not proceed
    [info] Project sbinary-----------------: EXTRACTION OK, but could not proceed
    [info] Project sbt-testng--------------: EXTRACTION OK, but could not proceed
    [info] Project scala-------------------: EXTRACTION FAILED (RuntimeException: The artifact could not be resolved)
    [info] Project scala-abide-------------: EXTRACTION OK, but could not proceed
    [info] Project scala-continuations-----: EXTRACTION OK, but could not proceed
    [info] Project scala-java8-compat------: EXTRACTION OK, but could not proceed
    [info] Project scala-js----------------: EXTRACTION OK, but could not proceed
    [info] Project scala-json-ast----------: EXTRACTION OK, but could not proceed
    [info] Project scala-logging-----------: EXTRACTION OK, but could not proceed
    [info] Project scala-parser-combinators: EXTRACTION OK, but could not proceed
    [info] Project scala-partest-----------: EXTRACTION OK, but could not proceed
    [info] Project scala-partest-interface-: EXTRACTION OK, but could not proceed
    [info] Project scala-records-----------: EXTRACTION OK, but could not proceed
    [info] Project scala-refactoring-------: EXTRACTION OK, but could not proceed
    [info] Project scala-ssh---------------: EXTRACTION OK, but could not proceed
    [info] Project scala-stm---------------: EXTRACTION OK, but could not proceed
    [info] Project scala-swing-------------: EXTRACTION OK, but could not proceed
    [info] Project scalacheck--------------: EXTRACTION OK, but could not proceed
    [info] Project scalameter--------------: EXTRACTION OK, but could not proceed
    [info] Project scalamock---------------: EXTRACTION OK, but could not proceed
    [info] Project scalaprops--------------: EXTRACTION OK, but could not proceed
    [info] Project scalariform-------------: EXTRACTION OK, but could not proceed
    [info] Project scalatags---------------: EXTRACTION OK, but could not proceed
    [info] Project scalatest---------------: EXTRACTION OK, but could not proceed
    [info] Project scalaz------------------: EXTRACTION OK, but could not proceed
    [info] Project scalikejdbc-------------: EXTRACTION OK, but could not proceed
    [info] Project scodec------------------: EXTRACTION OK, but could not proceed
    [info] Project scodec-bits-------------: EXTRACTION OK, but could not proceed
    [info] Project scopt-------------------: EXTRACTION OK, but could not proceed
    [info] Project scoverage---------------: EXTRACTION OK, but could not proceed
    [info] Project shapeless---------------: EXTRACTION OK, but could not proceed
    [info] Project simulacrum--------------: EXTRACTION OK, but could not proceed
    [info] Project slick-------------------: EXTRACTION OK, but could not proceed
    [info] Project sourcecode--------------: EXTRACTION OK, but could not proceed
    [info] Project specs2------------------: EXTRACTION OK, but could not proceed
    [info] Project spray-json--------------: EXTRACTION OK, but could not proceed
    [info] Project spray-json-shapeless----: EXTRACTION OK, but could not proceed
    [info] Project ssl-config--------------: EXTRACTION OK, but could not proceed
    [info] Project twirl-------------------: EXTRACTION OK, but could not proceed
    [info] Project twitter-util------------: EXTRACTION OK, but could not proceed
    [info] Project unfiltered--------------: EXTRACTION OK, but could not proceed
    [info] Project upickle-pprint----------: EXTRACTION OK, but could not proceed
    [info] Project utest-------------------: EXTRACTION OK, but could not proceed
    [info] >>> The dbuild result is------------: EXTRACTION FAILED (failed: scala)
    [info] ---==  End Execution Report ==---
    [info] --== Done Console Notifications ==--
    [info] ---==  Tasks Report ==---
    [info] Successful: Deploy, Comparison, Notifications
    [info] ---==  End Tasks Report ==---
    Result: EXTRACTION FAILED (failed: scala)
    Build failed after: 00h 39m 19.5s
    All done.
    ~~~

**Comment by SethTisue** [comment]
it looks like dbuild's Aether build system insists on ignoring your local ivy repository even if you specifically ask for it. you can put `localIvy` in `options.resolvers` (via, in this repo, `resolvers.conf`) and it will be ignored, as we see if we edit `run.sh` to pass `-d` (for debug) to dbuild:

```
[scala-library] Extracting dependencies for: scala-library
[scala-library:debug] The predefined "local" Ivy repository will be ignored.
```

this is coming from code in dbuild, in support/src/main/scala/com/typesafe/dbuild/support/aether/AetherBuildSystem.scala:

```scala
    case p: xsbti.PredefinedRepository => p.id match {
      // "local" is made to point to the same ivyHome, but nothing is ever published there
      case Local =>
        log.debug("The predefined \"local\" Ivy repository will be ignored."); None
```

I tried adding it instead using an explicit `file:` URL:

```diff
-  01: "local"
+  01: "seth: file:///Users/tisue/.ivy2/local/"${vars.ivyPat}
```

but that didn't fool it, I still get `The predefined "local" Ivy repository will be ignored`

@cunei any ideas about how to proceed here? is there any way to tell dbuild that yes, we really want Aether to retrieve Scala jars from `~/.ivy2/local`?

@julienrf one workaround would be to submit a scala/scala PR with your changes and wait for Jenkins to publish it to scala-release-temp

**Comment by dwijnand** [comment]
What about using publishM2 and resolving for mavenLocal?

**Comment by julienrf** [comment]
Thanks a lot @SethTisue for the explanation!

@dwijnand What should I put in the resolvers.conf file to tell dbuild to use maven-local? I will try that and if that doesn’t work then I’ll use scala-release-temp, as advised by @SethTisue.

**Comment by cunei** [comment]
@julienrf You can always use ```publish```, rather than ```publishLocal```, by specifying any (other) local directory in the ```publishTo``` setting. For example:
```
set every publishTo := Some(Resolver.file("file", new File("/home/someone/dir1/dir2")))
publish
```
Then, just add a new resolver pointing to the directory that you published the files to (I've not tried, but it should work, in theory).

**Comment by cunei** [comment]
Possibly, you may need:
```
Some(Resolver.file("file", new java.io.File("/home/someone/dir1/dir2"))(Resolver.ivyStylePatterns))
```

**Comment by SethTisue** [comment]
Dale's suggestion worked. I did `publishM2` from the scala/scala repo, then here in this repo I added this line to resolvers.conf:

    01: "maven-local"

it also works to provide a full `file:///` URL instead.

then after adding `-d` to `run.sh` I see lines like:

```
[scala-library:debug] Trying to download: file:///Users/tisue/.m2/repository/org/scala-lang/scala-library/2.12.2-623f0a7-nightly/scala-library-2.12.2-623f0a7-nightly-sources.jar
[scala-library] Downloaded: file:///Users/tisue/.m2/repository/org/scala-lang/scala-library/2.12.2-623f0a7-nightly/scala-library-2.12.2-623f0a7-nightly-sources.jar (965 KB at 107165.4 KB/sec)
```

🎉

(I imagine Toni's suggestion would work just as well.)

**Comment by dwijnand** [comment]
Excellent. Using `publishM2` is good because it emulates "production" slightly better, ie. when you release to repo1 - even if the maven cache (~/.m2) isn't exactly a maven repository, it's still maven instead of ivy.
