### ISSUE TITLE
reinstate scala-refactoring once it becomes 2.12.1-friendly

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#462]
previously: #407, #461 

/cc @sschaef @fommil

the issue in the scala-refactoring repo is https://github.com/scala-ide/scala-refactoring/issues/180

**Comment by fommil** [comment]
please re-enable the compile of scala-refactoring's `master` branch. Tests are not green yet, hopefully soon!

**Comment by SethTisue** [comment]
I see that the failing tests were disabled in https://github.com/scala-ide/scala-refactoring/pull/185, so I will go ahead and do a full reinstatement.
