### ISSUE TITLE
regression: Slick failing in 2.12 and 2.13 community builds

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#466]
so e.g. at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1211/consoleFull 

```
[slick] [error] Failed: Total 1091, Failed 3, Errors 0, Passed 1088
[slick] [error] Failed tests:
[slick] [error] 	slick.test.profile.H2MemTest
[slick] [error] 	slick.test.profile.H2DiskTest
[slick] [error] 	slick.test.profile.H2RownumTest
```

attn @szeiger

**Comment by szeiger** [comment]
https://github.com/slick/slick/pull/1686

**Comment by SethTisue** [comment]
test 2.12 run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1214/consoleFull (404 til Jenkins finishes gazing at his reflection in a cool, clear mountain spring)

**Comment by SethTisue** [comment]
green :-)
