### ISSUE TITLE
play-core failing in 2.12.x and 2.13.x builds

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#471]
it's probably not 2.13 specific, probably the 2.12 would be failing too if it weren't broken for other reasons

```
[play-core] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.7-RC1/project-builds/play-core-1c5a6cad40a4c451d7786223e94f3eeb7df24e5d/framework/src/play/src/main/scala/play/api/http/Writeable.scala:95: value toBytes is not a member of object play.api.libs.json.Json
[play-core] [error]     Writeable(a => ByteString(Json.toBytes(a)))
[play-core] [error]                                    ^
[play-core] [error] one error found
```

@wsargent does this look like the usual kind of thing where the various Play repos are just a bit out of sync with each other and it will probably be fixed before long...?

**Comment by wsargent** [comment]
Looking -- this seems to be coming from Play-JSON -- shows up in master:

https://github.com/playframework/play-json/blob/master/play-json/shared/src/main/scala/Json.scala#L68

Shows up in M2:

https://github.com/playframework/play-json/blob/2.6.0-M2/play-json/shared/src/main/scala/Json.scala#L68

Does not show up in M1:

https://github.com/playframework/play-json/blob/2.6.0-M1/play-json/src/main/scala/play/api/libs/json/Json.scala#L68

My guess is that you have an M1 dependency :-) /cc @gmethvin

**Comment by SethTisue** [comment]
yes, we are frozen at M1 of play-json, but that's because play-ws requires M1. can play-ws be upgraded?

**Comment by SethTisue** [comment]
considering this at a higher level, perhaps it would be better if I just froze all of the Play repos at fixed versions in the community build. it really isn't the purpose of the Scala community build to be plan A for catching this kind of thing; it ought to be plan B, or, like, plan Z.

**Comment by wsargent** [comment]
I can fix the dependencies.  Sorry, we're moving around a bunch of stuff right now.

**Comment by SethTisue** [comment]
verified that this also fails in the 2.12.x community build (with `version=2.12.1 ./run.sh`)

**Comment by wsargent** [comment]
Should be fixed via https://github.com/playframework/play-ws/pull/78

**Comment by SethTisue** [comment]
sweet, sweet green:

```
[info] Project play-core---------------: SUCCESS (project rebuilt ok)
[info] Project play-json---------------: SUCCESS (project rebuilt ok)
[info] Project play-ws-----------------: SUCCESS (project rebuilt ok)
```

thank you @wsargent @cchantep!
