### ISSUE TITLE
regression: conductr-lib fails to extract

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#473]
this started recently: `[conductr-lib:error] java.lang.RuntimeException: These subprojects were not found: "lagom1ConductRBundleLib".  Found: "javaConductRBundleLib", "akka23TestLib", "play24ConductRBundleLib", "root", "akka24ConductRClientLib", "lagom1JavaConductRBundleLib", "play25Common", "play23Common", "akka24ConductRBundleLib", "play25ConductRClientLib", "scalaConductRBundleLib", "play24ConductRClientLib", "common", "lagom1ScalaConductRBundleLib", "javaTestLib", "akka23Common", "conductRBundleLib", "play25ConductRBundleLib", "akka24TestLib", "scalaCommon", "play24Common", "play23ConductRClientLib", "akka23ConductRBundleLib", "akka24Common", "javaCommon", "scalaConductRClientLib", "play23ConductRBundleLib".`

currently our conductr config section is:

```
  ${vars.base} {
    name: "conductr-lib"
    uri:  ${vars.uris.conductr-lib-uri}
    extra.exclude: [
      // not our Akka version
      "akka23Common", "akka23ConductRBundleLib", "akka23TestLib"
      // we don't have Lagom yet
      "lagom1ConductRBundleLib"
      // not our Play version
      "play23Common", "play23ConductRBundleLib", "play23ConductRClientLib"
      // also not our Play version
      "play24Common", "play24ConductRBundleLib", "play24ConductRClientLib"
      // "That particular lib shouldn't be processed", says Christopher
      "akka24ConductRClientLib"
      // Play stuff didn't work, maybe try again later?
      "play25ConductRBundleLib", "play25ConductRClientLib", "play25Common"
    ]
  }
```
 
@huntc can you advise me on how the config should be updated...?

**Comment by SethTisue** [comment]
thanks @BennyHill for reporting

**Comment by SethTisue** [comment]
for now, I dealt with it by freezing (171dd016e5796f2be6386ff8db10fc3a21d77c13)

**Comment by SethTisue** [comment]
@huntc can you advise me on how the config should be updated...?

**Comment by huntc** [comment]
The Lagom Libs recently received a Java and a Scala flavour:

lagom1JavaConductRBundleLib
lagom1ScalaConductRBundleLib

No more lagom1ConductRBundleLib.

Apologies for having forgotten to advise.

**Comment by SethTisue** [comment]
no worries, wasn't urgent! all good now after #485
