### ISSUE TITLE
spray-json-shapeless failing in 2.12.x build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#475]
depends on shapeless which is currently broken in 2.12.x, but the failure can be seen by running the build against 2.12.1

at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1258/consoleFull we see:

```
[spray-json-shapeless] [info] Compiling 3 Scala sources to /Users/tisue/community-builds.212/target-0.9.7-RC1/project-builds/spray-json-shapeless-fd6c394665ddf27a110c9db00c2144135b430073/target/scala-2.12/test-classes...
[spray-json-shapeless] [error] /Users/tisue/community-builds.212/target-0.9.7-RC1/project-builds/spray-json-shapeless-fd6c394665ddf27a110c9db00c2144135b430073/src/test/scala/fommil/sjs/FamilyFormatsSpec.scala:329: could not find implicit value for evidence parameter of type spray.json.JsonFormat[fommil.sjs.ExampleAst.TokenTree]
[spray-json-shapeless] [error]     roundtrip(SpecialToken: TokenTree, """{"type":"SpecialToken"}""")
[spray-json-shapeless] [error]              ^
[spray-json-shapeless] [error] one error found
```

@fommil can you help with this? it isn't obvious to me what's going on here.

**Comment by SethTisue** [comment]
to get the build green again, in #476 I just disabled compiling or running the tests

**Comment by fommil** [comment]
That's very bizarre. I don't think I've changed anything, so could be a regression from anything to do with implicut resolution.

**Comment by fommil** [comment]
@milessabin

**Comment by SethTisue** [comment]
oh, maybe https://github.com/scala/scala/pull/5654 will fix it! let's wait and see

**Comment by milessabin** [comment]
I think there's a good chance that scala/scala#5654 will fix it.

**Comment by SethTisue** [comment]
optimistically closing on that assumption, I'll come back to it if we're guessing wrong

**Comment by milessabin** [comment]
Is there a successor issue to reenable spray-json-shapeless before release? If not, isn't closing this in advance just asking for it to fall between the cracks?

**Comment by SethTisue** [comment]
oops, you're right

**Comment by SethTisue** [comment]
the test still fails to compile in the context of the 2.12 community build even with `2.12.2-05d5338-nightly` in which SI-10154 is fixed, so apparently this is something else

whatever it is, spray-json-shapeless is the only affected project in the community build

I attempted to reproduce the problem outside of the community build, in the spray-json-shapeless repo, with

```
set every scalaVersion := "2.12.2-05d5338-nightly"
set every scalaBinaryVersion := "2.12"
test:compile
```

but the error didn't occur.

I can't afford to investigate further given that the problem seems to involve multiple codebases that are unfamiliar to me.

**Comment by fommil** [comment]
@milessabin any ideas?

**Comment by milessabin** [comment]
@fommil on do my or @buzzard's comments on https://github.com/scala/scala/pull/5654 look relevant?

**Comment by fommil** [comment]
I have absolutely no idea what is causing this

**Comment by fommil** [comment]
I can run `sbt test` in spray-json-shapeless with this

```
// http://stackoverflow.com/questions/40622878
resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
scalaVersion := "2.12.2-bin-96cdfb4"
```

and I get green lights... so if this still happens in the community build then my guess is a shapeless regression.

**Comment by SethTisue** [comment]
I'm going to close this since it isn't, so far as we know, actionable in this repo.

**Comment by fommil** [comment]
It's this still failing? I thought I fixed everything? I'm honestly too busy to fix this failures at the moment as I'm moving house. Can you please request help from scala/contributors ?

**Comment by SethTisue** [comment]
it isn't making the community build red, because we simply disabled running your tests. very likely the problem isn't actually fixed, though someone would have to re-enable your tests and do a test run in order to find out.

I don't have time to pursue this further on my own, including seeking help elsewhere. the community build has alerted to you and Miles to a possible regression that may break your projects once Scala 2.12.3 comes out. or not, it isn't clear. it would be nice if I had time to investigate, but I don't. there are more than 100 projects in the community build and I already spend a substantial portion of my time chasing after failures.

**Comment by fommil** [comment]
sure, no problem. This will have to rot.

**Comment by fommil** [comment]
@SethTisue I fixed some compiler warnings (escalated to error in CI) in both spray-json-shapeless and pcplod. Could you please re-enable them? 2.12.2 introduced some pretty harsh unused variable checks.

**Comment by SethTisue** [comment]
> Could you please re-enable them

https://github.com/scala/community-builds/pull/550

**Comment by fommil** [comment]
I'm pretty sure this is a regression in shapeless because it passes fine with scala-2.12.2 + shapeless-2.3.2 and the problem been happening since before 2.12.2 was cut. @milessabin have there been any changes in shapeless master that could impact typeclass derivation of sealed families?

specifically, typeclass derivation of this AST https://github.com/fommil/spray-json-shapeless/blob/master/src/test/scala/fommil/sjs/ExampleAst.scala

**Comment by SethTisue** [comment]
@fommil would you like me to do a test run with shapeless frozen at https://github.com/milessabin/shapeless/releases/tag/shapeless-2.3.2?

**Comment by fommil** [comment]
the 2.3.2 release would be about right 77a826e7aad0abc91dd60c69c1283c5abcec86a6

**Comment by SethTisue** [comment]
okay, let's try it: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1540/consoleFull

**Comment by SethTisue** [comment]
note how responsive I am when we aren't about 9 timezones apart :-)

**Comment by SethTisue** [comment]
gah

```text
[shapeless] [error] **** Missing dependency: the library org.scala-js#scala-junit-mixin-plugin is not provided (in space "default") by any project in this configuration file.
[shapeless] [error] In order to control which version is used, please add the corresponding project to the build file
[shapeless] [error] (or use "check-missing:false" to ignore (not recommended)).
[shapeless] java.lang.RuntimeException: Required dependency not found
```

I'll look into it, probably some 1 line tweak is needed

**Comment by fommil** [comment]
Ha! And the irony, I was in the states when I fixed my end.

**Comment by SethTisue** [comment]
I'll have to come back to this sometime after June 14.
