### ISSUE TITLE
regression: scalacheck started failing in 2.12/2.13 builds

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#493]
as a result of recent build changes @rickynils committed to fix https://github.com/rickynils/scalacheck/issues/318

namely

```diff
+  // Force clean before packaging.
+  // https://github.com/rickynils/scalacheck/issues/318
+  packageBin in Compile := {
+    clean.value
+    (packageBin in Compile).value
+  },
```

example failure from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1331/consoleFull:

```
[scalacheck] java.lang.RuntimeException: Missing files for publishing:
[scalacheck] 	/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/scalacheck-20876ac490f394ffc550b0748cdc950adc0ffa63/jvm/target/scala-2.12/scalacheck-0.1-dbuildx20876ac490f394ffc550b0748cdc950adc0ffa63-sources.jar
[scalacheck] 	at scala.sys.package$.error(package.scala:27)
[scalacheck] 	at sbt.IvyActions$.checkFilesPresent(IvyActions.scala:393)
[scalacheck] 	at sbt.IvyActions$.publish(IvyActions.scala:377)
```

**Comment by SethTisue** [comment]
worked around it for now by freezing ScalaCheck in d5f670c2f4ce6d4464cf673fe6c99d43097554a3

**Comment by xuwei-k** [comment]
https://github.com/rickynils/scalacheck/commit/9b71bb3dfe186c03292faa59976487af2ee23caa

**Comment by SethTisue** [comment]
thanks for the heads up. unfreeze test run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1505/consoleFull (404 til Jenkins determines if the small houseplant on his desk is real or artificial)

**Comment by SethTisue** [comment]
try again without fatal warnings: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1506/consoleFull

EDIT: ScalaCheck built this time, but it'll take a while to rebuild the world
