### ISSUE TITLE
regression: scalafix, scalamock failing in 2.12

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#499]
e.g. at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1343/consoleFull

**Comment by SethTisue** [comment]
scalamock fixed in 870122c542aaa91a4ee7668c920eeca9b1e738f2

**Comment by SethTisue** [comment]
scalafix issue is:

```
[scalafix] Processing subproject: core
[scalafix] [error] **** Missing dependency: the library org.scalameta#paradise is not provided (in space "default") by any project in this configuration file.
[scalafix] [error] In order to control which version is used, please add the corresponding project to the build file
[scalafix] [error] (or use "check-missing:false" to ignore (not recommended)).
[scalafix] java.lang.RuntimeException: Required dependency not found
[scalafix] 	at scala.sys.package$.error(package.scala:27)
```

we recently refreshed our fork of scalafix, and when we did, we picked up a dependency change from `"org.scalameta" % "paradise"` to  `"org.scalamacros" % "paradise"`

@olafurpg can you explain what this is about? why did the dependency change?

I have worked around it for now by force-pushing the community-build-2.12 branch of scalafix in the scalacommunitybuild org back to the commit we were using before (104e37c3)

**Comment by SethTisue** [comment]
sigh, but then I get:

```
[scalafix] Processing subproject: core
[scalafix] [error] **** Missing dependency: the library org.scalameta#contrib is not provided (in space "default") by any project in this configuration file.
[scalafix] [error] In order to control which version is used, please add the corresponding project to the build file
[scalafix] [error] (or use "check-missing:false" to ignore (not recommended)).
[scalafix] java.lang.RuntimeException: Required dependency not found
```

we recently disabled the `contrib` subproject in scalameta, because there were failures and it didn't seem like something that was appropriate to include in the community build anyway. not that I even actually know what the `contrib` project is or why scalafix's core depends on it.

@olafurpg can you enlighten me about that as well, and suggest how I ought to be handling this?

for now, I've made this change in our fork of scalafix:

```diff
-  def scalameta: ModuleID                       = "org.scalameta" %% "contrib"                 % scalametaV
+  def scalameta: ModuleID                       = "org.scalameta" %% "scalameta"               % scalametaV
```

and that seems to have done the trick, at least as far as the community build is concerned

**Comment by olafurpg** [comment]
I'm sorry to hear this. 

The contrib module had breaking tests because of a bug in our ci build, which has been fixed. Scalafix core depends on contrib, it contains utilities to traverse/manipulate trees which may or may not make it into scalameta core later. 

I recommend we disable scalafix and scalameta in the community build for now. Both projects are still rapidly evolving, with a lot of moving parts. For example, we may add new dependencies or modules which could complicate the setup in the community build. Once the api + integrations stabilize more, we can reevaluate including scalafix and scalameta in the community build. 

What do you think?

**Comment by SethTisue** [comment]
as of https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1349/consoleFull our fork is green again (by rewinding to February and altering the scalameta dependency), so I'm content to just leave it where it is for now. later on, we can revisit the issue — either in the direction of refreshing the fork, or in the direction of disabling it, as the case may be, depending.

in 203b0490fe3f9f2bcaa8860463f4f33b6acff006 I added comments to the config file that refer to this discussion and caution my future self, or other maintainers, about attempting to refresh the forks

also, perhaps I was too hasty in simply removing scalameta-contrib — I barely even looked at whatever the failures were. I'll take a second look at that.
