### ISSUE TITLE
regression: scalaz & Monocle failing to extract (Scala Native issue)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#500]
at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1344/consoleFull

Scala Native related:

```
[scalaz] [error] no clang++38, clang++-3.8, clang++37, clang++-3.7, clang++ found in $PATH. Install clang (http://scala-native.readthedocs.io/en/latest/user/setup.html#installing-llvm-clang-and-boehm-gc)
[scalaz] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[scalaz:error] java.lang.RuntimeException: 
[scalaz:error] 	at scala.sys.package$.error(package.scala:27)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:92)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:73)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:73)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:73)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[scalaz:error] 	at sbt.IO$.withTemporaryFile(IO.scala:322)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:104)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:83)
[scalaz:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:21)
```

not reproducible locally, I guess because my Mac has that stuff on it

relevant scalaz commit is https://github.com/scalaz/scalaz/commit/1e3ce71fcf0a63c88166778c3f3823c9c8322f19

**Comment by SethTisue** [comment]
addressed for the time being in a003917d77a10dd41baae420a318e97d612b2fed by freezing at last good commit; but I should report the problem upstream to the scala-native project (the error is coming from scala-native/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala)

**Comment by SethTisue** [comment]
reported upstream at https://github.com/scala-native/scala-native/issues/562

**Comment by xuwei-k** [comment]
monocle will also fail https://github.com/julien-truffaut/Monocle/pull/508

**Comment by SethTisue** [comment]
thanks for the heads up — I froze Monocle in 5395c19670720f762a34ed343872e14dd34b3fa6

it looks like Guillaume is working on this and we'll be able to unfreeze before long, once he has a fix

**Comment by SethTisue** [comment]
scalaz is unfrozen, since @xuwei-k added workaround code while we await a real fix

**Comment by xuwei-k** [comment]
scala-native 0.2.0 released but I found an another issue https://github.com/scala-native/scala-native/issues/673

**Comment by xuwei-k** [comment]
https://github.com/julien-truffaut/Monocle/pull/518
