### ISSUE TITLE
Question: should the community build monitor Scala.js' `master` or `0.6.x` branch?

### ISSUE THREAD

**Issue by sjrd** [scala/community-builds#506]
Currently, the community build monitors Scala.js' `master` branch. Until now, that was the obvious thing to do, as it was the only long-lived branch in Scala.js.

However, now Scala.js has two long-lived branch: `0.6.x` and `master` (the latter targeting 1.0.0). So we have a dilemma: which branch should be tracked?

Downstream Scala.js projects definitely build against `0.6.x` for the moment, so that would be an argument in favor of `0.6.x`. But at the same time, downstream Scala.js projects are not built by the CB anyway, so maybe that's not that relevant.

There is now more "action" in the `master` branch. Only bug fixes and new JDK parts target the `0.6.x` branch, everything else goes to master. Moreover, the `0.6.x` branch will be periodically merged into `master`. So that's an argument in favor of tracking `master`.

Opinions from the CB maintainers?

**Comment by SethTisue** [comment]
(as an aside, note that dbuild's "spaces" features would actually allow building both; one of them in a "space" of its own that doesn't affect anything else, and another that other projects would actually see/use (to the limited/nonexistent extent that Scala.js gets "used" at all by anything downstream, in a community build context). that would probably be overkill here though.)

my experience in the past 1.5+ years has been that Scala.js rarely causes trouble and when it does it's often something we're all better off learning about promptly. so I'm fine staying on `master`.

a specific request, though: it would be nice if https://github.com/scala-js/scala-js/pull/2814 were merged onto master soon.

**Comment by sjrd** [comment]
> a specific request, though: it would be nice if scala-js/scala-js#2814 were merged onto master soon.

We're literally only waiting for the CI job: https://scala-webapps.epfl.ch/jenkins/job/scalajs-pr/3826/ ;)

**Comment by SethTisue** [comment]
master is green again on 2.13. let's leave it there

**Comment by SethTisue** [comment]
here's a master change that broke a project (utest): https://github.com/lihaoyi/utest/issues/108

for now, freezing Scala.js at scala-js/scala-js@d6e876381a61f58f122fad0232de53a0b499b720: d9704d00eb27e602686a795d8b6eeeebc846d9af
