### ISSUE TITLE
regression: Slick failing, problem with Ornate

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#513]
seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1395/consoleFull

**Comment by SethTisue** [comment]
cc @szeiger. I think it might work to just exclude the "root" project, since it isn't a real project anyway

**Comment by SethTisue** [comment]
2.11.x-jdk8 was affected as well. on that branch, I just froze it, we don't really need stuff unfrozen there: 75fcae36a68590cc5d0478bf0a16d6524822792a, green run https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk8-integrate-community-build/358/

**Comment by szeiger** [comment]
Oh, only a missing dependency because you don't build Ornate. I thought it would be something more sinister like strange exceptions being thrown from the internals of Rhino because a Java 8 installation on the build slave is a few patch levels too old :)

**Comment by SethTisue** [comment]
@szeiger would you like to take a stab at adding Ornate?

**Comment by szeiger** [comment]
I don't think it would be a very useful addition. It's an application (not a library), written in pretty simple Scala (nothing interesting to test) and heavily using Nashorn (which provides many opportunities for things to go wrong that are unrelated to what we want to test in the community build)
