### ISSUE TITLE
move scalaz to 7.3.x?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#515]
@aloiscochard asked if this would be possible

we can certainly try it and see what happens. cc @xuwei-k

**Comment by SethTisue** [comment]
I'll do a trial run sometime soonish (not this week, hopefully within the next week or two). success will depend on how many projects have scalaz-based code that is source-incompatible with 7.3. (dbuild will override their declared dependency, so as usual with community build stuff, only source compatibility matters.)

**Comment by SethTisue** [comment]
wip on this is at #524  in case we decide to return to it. the scalaz/scalaz readme still describes 7.2.x as the latest stable version, so it's fine to stay there for now.

**Comment by aloiscochard** [comment]
Thanks for starting the effort @SethTisue !

**Comment by SethTisue** [comment]
from what I hear, the new action is on scalaz 8 these days. it seems unlikely we'll ever move the community build to 7.3. we can reopen this if the situation changes. closing for now
