### ISSUE TITLE
deal with -Xfatal-warnings for Scala 2.12.2 release, and after

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#517]
once https://github.com/scala/scala/pull/5402 is merged, some projects in the community build that have `-Xfatal-warnings` will start failing — we've already seen that in the test runs on that PR.

What I have time to do right now (meaning in time for 2.12.2) is flip a big switch and temporarily disable `-Xfatal-warnings` community-build wide. At least, I think I can fairly-easily do that in dbuild.

We'll eventually want to flip that switch back, but hopefully the project maintainers will fix their projects themselves if we notify them via @-mention once 2.12.2 is released, and so that after a month or two has passed, flipping the switch back will be easy.

cc @lrytz @som-snytt

**Comment by SethTisue** [comment]
it looks like #521 will be sufficient here, no big hammer needed

**Comment by som-snytt** [comment]
When everything looks like a big nail, one always reaches for a big hammer.

**Comment by SethTisue** [comment]
btw I'm working on fixing the warnings in scala-partest

**Comment by som-snytt** [comment]
I have a fix for partest, since I was also touching another partest fix.

**Comment by SethTisue** [comment]
you snooze you lose https://github.com/scala/scala-partest/pull/83

**Comment by som-snytt** [comment]
Gah, conflicts.
