### ISSUE TITLE
move from cats 0.9 to 1.0

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#549]
the needed cats-effect change was made in https://github.com/typelevel/cats-effect/pull/61 (thanks @djspiewak!), but we can't unfreeze cats until https://github.com/monix/monix/issues/366 is resolved

**Comment by alexandru** [comment]
This cannot be fixed until Cats releases packages for master, because it's a binary compatibility issue, e.g...

```
[info] - Sync[Coeval[Int]].sync.forEffect consistent flatMap *** FAILED ***
[info]   Exception raised on property evaluation. (Checkers.scala:37)
[info]   > ARG_0: <function0>
[info]   > ARG_1: <function0>
[info]   > Exception: java.lang.AbstractMethodError: cats.effect.laws.SyncLaws$$anon$1.forEffectConsistency(Ljava/lang/Object;Ljava/lang/Object;)Lcats/laws/IsEq;
```

```
[info] - Sync[Coeval[Int]].sync.monadError ensure consistency *** FAILED ***
[info]   Exception raised on property evaluation. (Checkers.scala:37)
[info]   > ARG_0: <function0>
[info]   > ARG_1: java.lang.Error
[info]   > ARG_2: <function1>
[info]   > Exception: java.lang.AbstractMethodError: cats.effect.laws.SyncLaws$$anon$1.monadErrorEnsureConsistency(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lcats/laws/IsEq;
```

```
[info] - Sync[Coeval[Int]].sync.monadError ensureOr consistency *** FAILED ***
[info]   Exception raised on property evaluation. (Checkers.scala:37)
[info]   > ARG_0: Coeval.Once(<function0>)
[info]   > ARG_1: <function1>
[info]   > ARG_2: <function1>
[info]   > Exception: java.lang.AbstractMethodError: cats.effect.laws.SyncLaws$$anon$1.monadErrorEnsureOrConsistency(Ljava/lang/Object;Lscala/Function1;Lscala/Function1;)Lcats/laws/IsEq;
```

Basically `AbstractMethodError` happens when binary compatibility is broken. And in this case it is broken because the `cats-laws` package has new methods in those traits.

Hopefully we'll fix this once Cats releases the scheduled `1.0.0-MF` version.

/cc  @djspiewak

**Comment by djspiewak** [comment]
I'll try to put in some work this weekend to push on some of the 1.0-MF stuff.  @kailuowang has really been driving that effort, but I think he's blocked on other people now.

**Comment by SethTisue** [comment]
now that cats 1.0.0-MF is out, is it a plausible time to unfreeze, or to at least move to newer frozen versions?

**Comment by alexandru** [comment]
Hey, so the `master` in Monix is fixed and actually depends on Cats 1.0.0-MF.

**Comment by SethTisue** [comment]
well, let's take a stab at this and just see what happens: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1743/consoleFull

**Comment by alexandru** [comment]
@SethTisue apparently that build failed, any ideas why?

**Comment by SethTisue** [comment]
```
[info] >>> The dbuild result is------------: FAILED (failed: fs2-cats, doodle)
```

**doodle**: we have doodle forked, but I see they are already on cats 1.0.0-MF on their master branch, so I assume that when we refresh our fork (which is still on cats 0.9), the problem will go away. not worried about this one

**fs2-cats**: is there someone reading this who could take care of [upgrading fs2-cats to cats 1.0.0-MF](https://github.com/functional-streams-for-scala/fs2-cats/issues/20)? note that http4s depends on fs2-cats. @rossabaker what's the status of http4s moving to 1.0.0-MF...?

**Comment by rossabaker** [comment]
http4s on cats-1.0.0-MF is on the [release-0.18.x](https://github.com/http4s/http4s/blob/release-0.18.x/) branch.  I don't think that branch has users yet, but runs [green](https://travis-ci.org/http4s/http4s/builds/262084025).

**Comment by djspiewak** [comment]
Tagging @mpilquist for the fs2 questions.

**Comment by SethTisue** [comment]
new test run with http4s's release-0.18.x branch: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1753/consoleFull

**Comment by rossabaker** [comment]
Why was this aborted?  Did it hang?

**Comment by SethTisue** [comment]
I killed it so I could use the Jenkins node for something more pressing. I'll be returning to this soon.

**Comment by SethTisue** [comment]
notes on work in progress:
* doodle already moved to cats-1.0.0-MF on their `develop` branch, so we probably just need to refresh our fork
* Michael already fixed fs2-cats
* jawn-fs2 needs fs2-io now (there's probably no reason we weren't building fs2-io)

**Comment by SethTisue** [comment]
@rossabaker currently blocked on jawn-fs2 which still uses `fs2.time` which was removed from fs2 between 0.10.0-M2 and 0.10.0-M5. can you update jawn-fs2 to the newer fs2 version?

**Comment by SethTisue** [comment]
@rossabaker working around it for now by excluding these subprojects: "jawn", "argonaut", "json4s", "json4s-jackson"

**Comment by rossabaker** [comment]
jawn-fs2 is now based on fs2-0.10.0-M5 on master, and is released as jawn-fs2-0.12.0-M1.

**Comment by SethTisue** [comment]
@rossabaker I see https://github.com/rossabaker/jawn-fs2/commit/e313fefcd98e5d58943d4b3056843c06422c3518 exists, but it isn't on master

**Comment by rossabaker** [comment]
Oops. 😳  _Now_ it's on master.

**Comment by SethTisue** [comment]
@rossabaker thanks! the http4s part of this is now green 🎉, I'm just making sure something didn't regress elsewhere before merging.

**Comment by SethTisue** [comment]
@rossabaker note that we're not running http4s's tests, because org.http4s.CookieSpec org.http4s.EntityDecoderSpec are failing
