### ISSUE TITLE
sbt 1.0 support

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#552]
let's start thinking about this

dbuild already allows projects to use different sbt versions, by overriding `extra.sbt-version`

we'll need dbuild to support 1.0.

is it plausible that dbuild could support a mix of sbt 0.13 and sbt 1.0 based projects in the same overall build?

**if yes**, then we're fine, all the real work will be on the dbuild side, and here we'd just need to make sure each project gets the right sbt version.

**if no**, then we'll have to proceed as follows: split the build in two, 2.12.x-sbt-0.13 and 2.12.x-sbt-1.0.

when a project moves to sbt 1.0, in the 2.12.x-sbt-0.13 build, freeze that project before the change, and add it to the 2.12.x-sbt-1.0 build. if not all of its dependencies are available, add it commented-out, with a comment saying what will be needed to re-enable it.

once most projects have moved, eventually fully freeze and/or retire the 2.12.x-sbt-0.13 build.

some help/encouragement may be needed to encourage foundational projects like scalacheck, scalatest, cats, scalaz, shapeless, scala-js, akka, and so forth to switch early, otherwise the 2.12.x-sbt-1.0 build won't be able to contain much.

cc @cunei @dwijnand, thx for the thoughts on this earlier over delicious hors d'oeuvres

**Comment by SethTisue** [comment]
hmm. perhaps 2.12.x-sbt-1.0 would never need to have any commented-out projects, only projects that are retrieved from published binaries (rather than built from source), for dependent projects to use

**Comment by SethTisue** [comment]
@cunei is working on this

**Comment by SethTisue** [comment]
> is it plausible that dbuild could support a mix of sbt 0.13 and sbt 1.0 based projects in the same overall build?

@cunei dbuild 0.9.9 supports this, right?

**Comment by SethTisue** [comment]
> is it plausible that dbuild could support a mix of sbt 0.13 and sbt 1.0 based projects in the same overall build?

@cunei dbuild 0.9.9 supports this, right?

provisionally closing assuming the answer is "yes"

**Comment by cunei** [comment]
The answer is "yes" :slightly_smiling_face:
