### ISSUE TITLE
monix failing in 2.13.x

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#561]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/476/consoleFull

```
[monix] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.7-RC1/project-builds/monix-dc56ed4f6ed043d6c797fc1dc816e4971708feae/monix-eval/shared/src/main/scala/monix/eval/instances/CatsAsyncInstances.scala:37: overriding method unit in trait Applicative of type => monix.eval.Task[Unit];
[monix] [error]  value unit needs `override' modifier
[monix] [error]     val unit: Task[Unit] = Task.now(())
[monix] [error]         ^
```

**Comment by SethTisue** [comment]
dealt with it in edff76205ed254ed130aa27801bc3ae058d4aa07 by tracking series/2.x branch instead of master. fyi @alexandru

**Comment by SethTisue** [comment]
perhaps related? https://github.com/scala/community-builds/issues/549

**Comment by alexandru** [comment]
@SethTisue fixed in https://github.com/monix/monix/commit/f78b832ba5612d50973d4f56db37d245fa449dfc

**Comment by alexandru** [comment]
Btw, related to https://github.com/scala/community-builds/issues/549 - that one cannot be fixed right now, I've written a comment why.

**Comment by SethTisue** [comment]
@alexandru thanks! I think I'd actually prefer to stay on 2.x for now, here in the community build, since I assume that's what downstream users are generally still on
