### ISSUE TITLE
regression: jawn-fs2 fails to compile

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#563]
seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1610/consoleFull

```
[jawn-fs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/jawn-fs2-1c8587203784471ce181c73215ae15f3bab50fcc/src/main/scala/jawnfs2/Absorbable.scala:5: object Segment is not a member of package fs2
[jawn-fs2] [error] import fs2.{Chunk, Segment}
[jawn-fs2] [error]        ^
```

**Comment by SethTisue** [comment]
I attempted to deal with it in 5e2509ca2def8996b5e1eabeaa90b5c21c6647c9 by freezing jawn-fs2; we'll see how the next test run goes: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1611/consoleFull

**Comment by SethTisue** [comment]
yeah that made it green again. fyi @rossabaker

**Comment by rossabaker** [comment]
I haven't been able to keep tabs on this project as well as I'd like, but this looks like a result of publishing jawn-fs2 for fs2-0.10.0-M1 while the community build is still on fs2-0.9.  When fs2 is upgraded in the community build, I think jawn-fs2 can and should follow.

**Comment by SethTisue** [comment]
> When fs2 is upgraded in the community build, I think jawn-fs2 can and should follow.

happened in #586
