### ISSUE TITLE
2.13 regression in multiple repos: `Numeric#parseString` related compile failures

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#572]
```
[scala-js] [error] /Users/tisue/community.213/target-0.9.7/project-builds/scala-js-b4b1e8709e8bd2bf57f6513d376a2ff57907267f/test-suite/shared/src/test/scala/org/scalajs/testsuite/scalalib/RangesTest.scala:119: object creation impossible, since method parseString in trait Numeric of type (str: String)Option[A] is not defined
[scala-js] [error]     implicit object aIsIntegral extends scala.math.Integral[A] {
[scala-js] [error]                     ^
```

**Comment by SethTisue** [comment]
and the scala-collections-laws failure looks like the same thing

**Comment by lrytz** [comment]
caused by https://github.com/scala/scala/pull/5523/files#diff-a1c7fbbd4efafafc57671a3ac783aaeaR212

**Comment by SethTisue** [comment]
upstream PRs: https://github.com/Ichoran/scala-collections-laws/pull/1, https://github.com/scala-js/scala-js/pull/3067

**Comment by SethTisue** [comment]
8dfe5d7aae52a709b0417c50526b8ec2acb9bbcf uses my forks. leaving this ticket open so we don't forget to revert it once the PRs are merged

**Comment by SethTisue** [comment]
Rex merged the collections PR.

The scala-js PR is pending. I was asked to target 0.6.x instead of master, so I rebased and force-pushed my branch. Probably the 0.6.x vs master thing won't matter here in the 2.13 community build (and the change is only temporary anyway), but mentioning it in case some mysterious failure crops up.

**Comment by SethTisue** [comment]
scala-js PR merged onto 0.6.x, awaiting forward-merge onto master

**Comment by SethTisue** [comment]
fixing other failures uncovered a third instance of this `parseString` problem, in monix this time:

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/540/consoleFull

```
[monix] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.7/project-builds/monix-311f1b6395ed11c4bdc242046c80377df603b524/monix-execution/shared/src/test/scala/monix/execution/atomic/BoxedLong.scala:26: object creation impossible, since method parseString in trait Numeric of type (str: String)Option[monix.execution.atomic.BoxedLong] is not defined
[monix] [error]   implicit val numeric = new Numeric[BoxedLong] {
[monix] [error]                              ^
[monix] [error] one error found
[monix] [error] (executionJVM/test:compileIncremental) Compilation failed
```

I'll fix, but first, sleep.

**Comment by SethTisue** [comment]
8a8bbbc19b3f44ac4cb3936584509eba4a8a3bc9 forks monix temporarily. test run: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/544/consoleFull ~~(404 while Jenkins tries to remember which bottle of hot sauce is the hot one and which is the really really really hot one)~~

**Comment by SethTisue** [comment]
green

monix upstream PR: https://github.com/monix/monix/pull/386

**Comment by sjrd** [comment]
FYI: The fix contributed by @SethTisue has landed in Scala.js master.

**Comment by SethTisue** [comment]
test run with all 3 projects unforked: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/558/consoleFull (404 while Jenkins comes down from his hallucinogenic moonflower trip... could be a while)

**Comment by SethTisue** [comment]
unforkings pushed
