### ISSUE TITLE
2.11 regression: failure to resolve scala-xml 1.0.6

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#575]
first happened at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/712/

I figured this surely had to be transient, but a run the next day failed too: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/714/

```
[scala-xml] [warn] ==== dbuild: tried
[scala-xml] [warn]   https://scala-ci.typesafe.com/artifactory/dbuild/org/scala-lang/modules/scala-xml/1.0.6/scala-xml-1.0.6.pom
[scala-xml] [warn] ==== dbuild-ivy: tried
[scala-xml] [warn]   https://scala-ci.typesafe.com/artifactory/dbuild-ivy/org.scala-lang.modules/scala-xml/1.0.6/ivys/ivy.xml
[scala-xml] [warn] ==== dbuild-unchecked: tried
[scala-xml] [warn]   https://scala-ci.typesafe.com/artifactory/dbuild-unchecked/org/scala-lang/modules/scala-xml/1.0.6/scala-xml-1.0.6.pom
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scala-xml] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scala-xml] [warn] 	:: org.scala-lang.modules#scala-xml;1.0.6: not found
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

a bunch of scala-xml build changes did recently go in so maybe there's actually a rational explanation and it's not just an Artifactory glitch or some such

**Comment by SethTisue** [comment]
~~like maybe scala/scala-xml@91bd5c4753bb6351bb0d7fcceddce6417c0f9e42 and/or scala/scala-xml@a211848a41169953a43238f56bfe6f830ac1e953~~ see below

**Comment by SethTisue** [comment]
[last green run](https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/711/consoleFull) was at scala/scala-xml@f0c1e5f006e6708c868fd9aa93e0a732b5eb7713

**Comment by SethTisue** [comment]
it's looking for `org.scala-lang.modules#scala-xml;1.0.6` but of course that's wrong, it should be `org.scala-lang.modules#scala-xml_2.11;1.0.6` (or maybe, depending on context, some dbuild-mangled thing)

**Comment by SethTisue** [comment]
[happens in the 2.12 build as well](https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1679/console) and is reproducible locally too

**Comment by SethTisue** [comment]
culprit commit is scala/scala-xml@a211848a41169953a43238f56bfe6f830ac1e953 (cc @lrytz). that's a big jump in sbt-scala-module version.

~~fwiw scala-parser-combinators is also now on the same sbt-scala-module version, not sure why it wouldn't be failing as well (it was green at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/711/consoleFull on commit scala/scala-parser-combinators@1ece49c39bcc3d8706a1315390445076b5a1d369)~~ (see below)

**Comment by SethTisue** [comment]
> fwiw scala-parser-combinators is also now on the same sbt-scala-module version, not sure why it wouldn't be failing as well

(hmm actually no... scala-parser-combinators only uses that version on a branch, not on master, and master is what the community build builds)

**Comment by SethTisue** [comment]
I think this must be the culprit. from the v1.0.8..v1.0.12 diffs in the plugin:

```diff
-    // manual cross-versioning because https://github.com/typesafehub/migration-manager/issues/62
-    mimaPreviousArtifacts := Set(organization.value % s"${name.value}_${scalaBinaryVersion.value}" % mimaPreviousVersion.value.getOrElse("dummy")),
+    mimaPreviousVersion := None,
+
+    // We're not using `%%` here in order to support both jvm and js projects (cross version `_2.12` / `_sjs0.6_2.12`)
+    mimaPreviousArtifacts := Set(organization.value % moduleName.value % mimaPreviousVersion.value.getOrElse("dummy") cross crossVersion.value),
```

**Comment by SethTisue** [comment]
I don't fully understand what's going on here (outside of the community build, `xmlJVM/mimaReportBinaryIssues` does fine, reporting e.g. `checking against org.scala-lang.modules:scala-xml_2.12:1.0.6`), but it should be easy enough to work around by just not running MiMa here

**Comment by lrytz** [comment]
> big jump in sbt-scala-module version

I [burned a few version numbers](https://github.com/scala/sbt-scala-module/releases) recently, so it's just the successor of 1.0.9, which itself is just a renaming of 1.0.8.


> scala-parser-combinators only uses that version on a branch, not on master

it's just that 1.0.x hasn't been merged to master since the change.


> I don't fully understand what's going on here (outside of the community build, xmlJVM/mimaReportBinaryIssues does fine

I don't know either, but it very much reminds me of the bug that is linked in the diff you posted above: https://github.com/typesafehub/migration-manager/issues/62. It looks like `crossVersion.value` isn't doing the right thing here. Maybe it's picked from some wrong scope/configuration?

**Comment by SethTisue** [comment]
I hit this again with scala-parser-combinators in #680, but forgot about this previous occurrence. Add my flailings on that ticket to the case file.
