### ISSUE TITLE
Document local Artifactory proxy usage

### ISSUE THREAD

**Issue by gkossakowski** [scala/community-builds#58]
The first step of dbuild run is analysis of project dependencies. For that to complete, dependencies of each project need to be resolved through Ivy. It means we have to hit remote repositories a lot and it takes time. The workaround for slow Ivy resolution that Typesafe uses when running Jenkins [jobs](https://jenkins-dbuild.typesafe.com:8499) is going through a local repository proxy. We are using Artifactory for that.

We should cleanup repository defintions in our config files and document how to set up local Artifactory proxy so it's practical to run dbuild with community build config outside of Typesafe jenkins machine.

**Comment by SethTisue** [comment]
there is nice doc on this at https://docs.google.com/document/d/18fGjMz21J4-JMHXfDH4OyGOXu8NvWfsG4q83S9RT64M/edit, thanks @eed3si9n!

**Comment by SethTisue** [comment]
I'm now much more knowledgeable on this. As in, I now use a local Artifactory for everything (all community build work and all my other work too) — so I can answer questions, at least. There is some discussion and lore at #408.

**Comment by SethTisue** [comment]
I've added my local config to the repo: https://github.com/scala/community-builds/blob/2.12.x/artifactory.xml

**Comment by SethTisue** [comment]
declaring the current state good enough
