### ISSUE TITLE
move Akka from 2.4 to 2.5

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#592]
it's time, 2.5 has been out for a while.

https://github.com/SethTisue/community-builds/commits/akka-2.5 has an initial stab

the test run at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1829/  shows that unforking akka-http (possible now that they're running modern sbt-bintray) caused some weird OSGi-related OutOfMemoryError (cranking up the heap size didn't help, it must be constructing an infinite string). I should return to it

```
[akka-http:error] Caused by: java.lang.OutOfMemoryError: Java heap space
[akka-http:error] 	at java.util.Arrays.copyOf(Arrays.java:3332)
[akka-http:error] 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
[akka-http:error] 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
[akka-http:error] 	at java.lang.StringBuilder.append(StringBuilder.java:136)
[akka-http:error] 	at java.lang.StringBuilder.append(StringBuilder.java:76)
[akka-http:error] 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:484)
[akka-http:error] 	at java.lang.StringBuilder.append(StringBuilder.java:166)
[akka-http:error] 	at java.lang.StringBuilder.append(StringBuilder.java:76)
[akka-http:error] 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2769)
[akka-http:error] 	at java.util.Formatter.format(Formatter.java:2508)
[akka-http:error] 	at java.util.Formatter.format(Formatter.java:2455)
[akka-http:error] 	at java.lang.String.format(String.java:2940)
[akka-http:error] 	at aQute.bnd.osgi.Processor.report(Processor.java:1799)
[akka-http:error] 	at aQute.bnd.osgi.Processor.toString(Processor.java:2235)
```

likely culprit is https://github.com/akka/akka-http/pull/1008 — probably this OSGi stuff doesn't like dbuild-mangled version numbers, something like that?

it seems we already dealt with the same thing (probably the same?) in scala/scala, see https://github.com/scala/scala/pull/5581#issuecomment-265001683 and below

possibly relevant: https://github.com/sbt/sbt-osgi/issues/15 , https://github.com/bndtools/bnd/issues/724

note that in the test run, two subprojects succeed (akka-parsing, akka-http-core) before one fails (akka-http), but the successful logs include a great deal of spew like this:

```
[akka-http] [warn] -----------------
[akka-http] [warn] Warnings
[akka-http] [warn] 000: No translation found for macro: range;[===,=+);10.0.0-dbuildxae2a802999ec892c737b3f40cbe55f61d0316ada, in -----------------
[akka-http] [warn] Errors
[akka-http] [warn] 000: Invalid syntax for version: 10.0.0-dbuildxae2a802999ec892c737b3f40cbe55f61d0316ada, for cmd: range, arguments; [range, [===,=+), 10.0.0-dbuildxae2a802999ec892c737b3f40cbe55f61d0316ada]
[akka-http] [warn] bnd: No translation found for macro: range;[==,=+), in -----------------
[akka-http] [warn] Errors
[akka-http] [warn] 000: Invalid syntax for version: 10.0.0-dbuildxae2a802999ec892c737b3f40cbe55f61d0316ada, for cmd: range, arguments; [range, [===,=+), 10.0.0-dbuildxae2a802999ec892c737b3f40cbe55f61d0316ada]
```

we could always fork akka-http and just rip all of the OSGi stuff out, but perhaps there's something we could put in `extra.commands` to bypass the computation that's blowing up... maybe `set every osgiBundleVersion ....`

**Comment by SethTisue** [comment]
as part of this, we should unfork akka-contrib-extra, now that it is using a modern version of sbt-bintray. I made an incomplete stab at it in 790f4e0225051b9a515bdf806b3715de58dd18e0

same for akka-http now that https://github.com/akka/akka-http/issues/1355 is fixed

**Comment by SethTisue** [comment]
for akka-http, `set every OsgiKeys.bundleVersion := "10.0.0"` seems to do the trick

```
[info] Project akka-http---------------: SUCCESS (project rebuilt ok)
```

**Comment by SethTisue** [comment]
let's see what breaks next: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1835/consoleFull

the Scala community build: like 116 weasels in your pants!

**Comment by retronym** [comment]
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹 ▶️  👖
