### ISSUE TITLE
regression: Shapeless failing in 2.13 build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#596]
at e.g. https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/639/consoleFull

```
[shapeless] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.9/project-builds/shapeless-a7d6a88678f02e67e8c6d35d8799046b02da5894/core/src/test/scala/shapeless/tuples.scala:1255: Cannot prove that (String, Double) <:< CC1[El1].
[shapeless] [error]     val t2 = l4.transpose
[shapeless] [error]                 ^
```

@milessabin you want to look into this one?

**Comment by hrhino** [comment]
I suspect it's because scala/scala#6035 gave us a tuple method named `transpose`, as well.

**Comment by milessabin** [comment]
Thanks for the heads up ... I'm going to push back on the renaming to `transpose` ... it's really not an improvement on `invert` (which admittedly is not a good name either).

See https://github.com/scala/scala/pull/6035#issuecomment-328484411.

**Comment by SethTisue** [comment]
@lrytz opinion on how to proceed here? it's starting to make me itchy to have the 2.13 community build red for so long — and having Shapeless failing takes out numerous downstream projects too

**Comment by lrytz** [comment]
Not too sure.. @szeiger is deep into collections, maybe he could share his thoughts? https://github.com/scala/scala/pull/6035#issuecomment-334062557

**Comment by SethTisue** [comment]
scala/scala#6035 was reverted
