### ISSUE TITLE
2.13: sbinary fails to extract 

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#603]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/651/console

```
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sbinary] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sbinary] [warn] 	:: org.scala-lang.modules#scala-xml_2.13.0-pre-12b8cfb;1.0.5: not found
[sbinary] [warn] 	:: org.scalacheck#scalacheck_2.13.0-pre-12b8cfb;1.13.4: not found
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

note that we unforked sbinary in 99e8031c6aa80f490f9979fa41072755b55b58e5. this failure started when I merged the change onto 2.13.x

**Comment by SethTisue** [comment]
perhaps https://github.com/sbt/sbinary/pull/10 will fix it. even if not, it's a good baseline to start from

**Comment by SethTisue** [comment]
hmm, at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/654/consoleFull the scala-xml one went away but we still see:

```
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sbinary] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sbinary] [warn] 	:: org.scalacheck#scalacheck_2.13.0-pre-12b8cfb;1.13.5: not found
[sbinary] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by SethTisue** [comment]
this is a tough one...

I suspect this snippet of code in sbt-houserules:

```
// WORKAROUND https://github.com/sbt/sbt/issues/3393
def addSbtPlugin(m: ModuleID) =
  libraryDependencies += Defaults.sbtPluginExtra(
    m,
    (sbtBinaryVersion in pluginCrossBuild).value,
    (scalaBinaryVersion in update).value
  )
```

dependency extraction shouldn't normally cause library dependencies to be retrieved, but perhaps `(scalaBinaryVersion in update).value` is the culprit

**Comment by SethTisue** [comment]
this is a tough one. I don't have a clue what's going on. why would dbuild/sbt attempt to actually retrieve a dependency during dependency extraction?

**Comment by SethTisue** [comment]
I should enable dbuild's debugging mode and look at the resulting log; that's an obvious thing I haven't tried yet. (Most community build problems are solvable by looking at the regular log, so I sometimes forget about the debug log.)

**Comment by SethTisue** [comment]
full debug-mode log: https://gist.github.com/SethTisue/e74c824f82daff525a16db2a428482c0

I don't see any new clues :-\

**Comment by SethTisue** [comment]
asked for volunteer extra pairs of eyes on Slack. anyone watching this repo who wants to take a look, be my guest. not sure if there's something weird and elusive going on here? maybe it's something obvious staring me in the face that I'm somehow not seeing

**Comment by SethTisue** [comment]
@cunei any insight?

**Comment by cunei** [comment]
It seems you are using "2.13.0-pre-12b8cfb" as a Scala version during extraction. The failed dependency is not one of the main build level, but one of the plugins level. So sbt is just trying to compile the build definition, before dependency extraction, when the failure occurs. There may just not be a scalacheck published against 2.13.0-pre-12b8cfb. The same error occurs if you check out sbinary from scratch, change the scalaVersion in the build file, and launch "sbt" pointing to an empty ivy cache directory, before you even get to the prompt.
I am not sure why the plugin level would try to use that scalaVersion rather than 2.10, however. I'll have a look.

**Comment by SethTisue** [comment]
> I am not sure why the plugin level would try to use that scalaVersion rather than 2.10, however

exactly

> I'll have a look.

thanks!

**Comment by cunei** [comment]
The failure is due to the different version of `sbt-houserules`. Version 0.3.3 works ok, but version 0.3.4 leads to the incorrect dependency.

**Comment by SethTisue** [comment]
0.3.4 adds:

```
+sbtVersion in Global := "1.0.0" // must be Global, otherwise ^^ won't change anything
```

maybe that's confusing dbuild? sbinary's own project/build.properties still says 0.13.16

**Comment by SethTisue** [comment]
this, in 0.3.4, also looks like it could trip up dbuild:

```
+// WORKAROUND https://github.com/sbt/sbt/issues/3393
+def addSbtPlugin(m: ModuleID) =
+  libraryDependencies += Defaults.sbtPluginExtra(
+    m,
+    (sbtBinaryVersion in pluginCrossBuild).value,
+    (scalaBinaryVersion in update).value
+  )
```

**Comment by cunei** [comment]
dbuild is not involved. You get the same result if you check out commit `2a1cfe45192719e118bd8a87b1c8ae2284fc6d61` of sbinary, change scalaVersion to `2.13.0-pre-fa78b6d`, and start sbt.

**Comment by SethTisue** [comment]
hmm. `scalaBinaryVersion in update` seems especially suspicious?

**Comment by SethTisue** [comment]
I dealt with it (in 87ce08eae13235aa382c12e22e809edbd4e5dc29) by forking sbinary and downgrading sbt-houserules in the fork.

it should work to unfork once sbt 0.13.17 is out that fixes the underlying problem (sbt/sbt#3393) and once a new sbt-houserules has been released that removes the workaround code inserted in 0.3.4 for that issue

thx @cunei for your help!

**Comment by SethTisue** [comment]
ugh, I should have seen this coming: downgrading sbt-houserules also downgrades from sbt-bintray 0.5 to bintray-sbt 0.3, and then we run afoul of the usual dbuild/bintray-sbt incompatibility

**Comment by SethTisue** [comment]
scalacommunitybuild/sbinary@3fa07bf377b81c0579e78936b54e2d181c4fc542 just removes sbt-houserules altogether. done.

**Comment by SethTisue** [comment]
over at https://github.com/sbt/sbinary/pull/11 I've submitted a PR that, once merged, should permit unforking
