### ISSUE TITLE
where'd fommil/spray-json-shapeless go?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#606]
@fommil ?

**Comment by SethTisue** [comment]
I had a clone sitting around on my laptop which I've put at https://github.com/scalacommunitybuild/spray-json-shapeless — last commit March 2017

**Comment by SethTisue** [comment]
in both 2.11 community builds, only ensime depends on spray-json-shapeless, and we have spray-json-shapeless frozen at v1.1.0, which is old enough to be included in https://github.com/scalacommunitybuild/spray-json-shapeless

in the 2.12 community build, nothing depends on spray-json-shapeless, so it's okay to just drop if it's effectively a dead project

**Comment by SethTisue** [comment]
provisionally dropped from 2.12 in 51b548f8480c73d6834547b5ca7c7a1cc8def388

**Comment by fommil** [comment]
Oh yeah, i put everything I'm not maintaining into an attic at gitlab. Off with its head!

**Comment by fommil** [comment]
You can kill ensime from 2.11

**Comment by SethTisue** [comment]
ok, thanks for clarifying.

ensime is already frozen in the 2.11 build.... actually deleting it there isn't necessary, freezing is adequate. I'll go ahead and use the scalacommunitybuild fork of spray-json-shapeless

**Comment by SethTisue** [comment]
6f44121f310e4d76772cd5dd81df3a38b8e4031f (closing on the assumption this will work)

UPDATE: it worked.
