### ISSUE TITLE
2.12: new cats-effect failure

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#612]
seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1998/consoleFull

```
[cats-effect] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/cats-effect-db3ea0a31df5a4c7495c66e0748f3b89148128e0/laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala:50:
  assignments in argument position are deprecated in favor of named arguments. Wrap the assignment in brackets, e.g., `{ cur = ... }`.
[cats-effect] [error]     val change = F.delay(cur = f(cur))
[cats-effect] [error]                              ^
```

root cause is https://github.com/scala/scala/pull/6089 (hello @lrytz)

**Comment by SethTisue** [comment]
@djspiewak could you make the needed changes to the cats-effect sources? (if you can do it fairly soon, awesome. otherwise, I can just disable `-Xfatal-warnings` for cats-effect in the context of the community build)

**Comment by djspiewak** [comment]
@SethTisue I'll take care of it this week.  Sorry for the delay.

**Comment by SethTisue** [comment]
no worries, that's plenty fast

**Comment by djspiewak** [comment]
@SethTisue This should be fixed as of `284268a`.  Do you need a release?

**Comment by SethTisue** [comment]
Nope, if it’s on master, the community build will pick it up. I’ll check on it on Monday. Thanks!

**Comment by SethTisue** [comment]
Adriaan had temporarily disabled `-Xfatal-warnings` in 7c29e2b648ef6ff7340553567d13ee9b0370e9c7; now reverted. green in a local test
