### ISSUE TITLE
add more http4s now that we have circe

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#626]
we'd disabled a number of http4s subprojects because we didn't have circe, but now we could try again (since #623 was merged)

/cc @rossabaker @travisbrown

**Comment by rossabaker** [comment]
I think we're talking about [this configuration](https://github.com/scala/community-builds/blob/8e107e25107dc0f9020c3f20cf460d9ab2e6a33c/configs/community.dbuild#L1383)?

The circe modules and the examples all make sense.  docs won't build anything unless you're running tut.

**Comment by SethTisue** [comment]
fixed by #627
