### ISSUE TITLE
Document how to test community-build against a locally-built compiler

### ISSUE THREAD

**Issue by soronpo** [scala/community-builds#630]
This documentation is missing.

**Comment by SethTisue** [comment]
will do

**Comment by SethTisue** [comment]
Note to self, I should also note somewhere, probably both here and in the scala/scala repo, that anyone can request a community build against their scala/scala PR

**Comment by SethTisue** [comment]
locally built Scala: https://github.com/scala/community-builds/wiki/Local-runs#can-i-use-a-locally-built-scala

requesting a run against a Scala PR: https://github.com/scala/community-builds/wiki#can-i-run-it-against-a-pull-request-in-scalascala

and, over in scala/scala: scala/scala#6185
