### ISSUE TITLE
move sbt tags from 1.0.4 -> 1.1.0

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#650]
sequel to #642, sister to #645 

it can wait until 1.1.0 is finalized, I think.

**Comment by SethTisue** [comment]
we might make another attempt to enable the test suite (last time we tried, as part of #642, just one test failed)

**Comment by SethTisue** [comment]
@dwijnand can I interest you in PR-ing this...?

**Comment by SethTisue** [comment]
@dwijnand can I interest you in PR-ing a move to 1.1.4?

**Comment by dwijnand** [comment]
Sure!
