### ISSUE TITLE
don't disable tests build-wide, just for specific subprojects where the failures are

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#657]
there are a number of projects where we don't run _any_ tests just because of (perhaps as little as) _one_ failing test in _one_ subproject

I hadn't previously tried to find a way to disable tests just for one subproject, but I know one now:

    set executeTests in thisParticularSubproject in Test :=
      Tests.Output(TestResult.Passed, Map(), Iterable())

we should do a sweep through `community.build`, look for disabled test suites, re-enable them, see what fails, and then more selectively re-disable

we might even find that all the tests actually pass once enabled. when we disable running tests, they normally just stay disabled, perhaps for years

**Comment by SethTisue** [comment]
test run with all test suites re-enabled: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2450/consoleFull ~~(404 til Jenkins finishes wondering what the difference between a tea "bag" and a tea "sachet" really is, anyway)~~

**Comment by SethTisue** [comment]
results from this round:

* succeeded: shapeless, scala-stm, scala-async, scala-refactoring
* failed: specs2, genjavadoc, scoverage, parboiled, scalacheck-shapeless, sbt
* blocked: akka-more, akka-http, breeze, ssl-config, scalikejdbc, scala-ssh, monix, unfiltered, akka-contrib-extra, scala-gopher, zinc, ammonite, http4s, github4s

**Comment by SethTisue** [comment]
69878ce9c86b4a466795003dfedb500a6a6fbd76 re-enables tests on those four projects 🎉

most of the blocked projects are blocked by specs2 and/or genjavadoc

the genjavadoc failure looks like an overly sensitive test (only ordering differs, I think?)

what's going on with specs2? the single failing test in `core` (after which the other subprojects don't get to run)  is `org.specs2.specification.IsolatedExecutionSpec` in `core/test:test`. we track their `specs2-3.x` branch. if I check out that branch locally and do `++2.12.4` and `core/test:testOnly *IsolatedExecutionSpec`, it fails. it also fails with `++2.12.3`, but passes with `++2.12.2`, so it seems this is a regression (of some sort, perhaps just a too-fragile test? idk) that the community build _would_ have caught. I've reported it at https://github.com/etorreborre/specs2/issues/622

**Comment by SethTisue** [comment]
let's try again but disable running the tests in specs2 `core` only: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2457/consoleFull (404 til Jenkins stops feeling he can't even and decides that actually he can even)

**Comment by SethTisue** [comment]
as for genjavadoc, the failure is reproducible outside dbuild with `++2.12.5-bin-3792784` followed by `genjavadoc-plugin/testOnly *BasicSpec`; it passes with `++2.12.4`

it looks like I just need to submit an upstream PR that adds an appropriate `plugin/src/test/resources/patches/2.12.5.patch` file (hopefully the Scala version number handling is smart enough to select that file when a Scala version number such as `2.12.5-bin-3792784` is involved)

**Comment by SethTisue** [comment]
https://github.com/lightbend/genjavadoc/pull/123 fixes the genjavadoc issue, and a445762d04626b11dc2bb9f1c5fbd4fa8d9f04ef re-enables the tests

**Comment by SethTisue** [comment]
let's try again but with SethTisue/community-builds@ca8faf34e593a6758f46d3bf6d4d1b8b32d4bb5a which disables running the tests in specs2 `core` only: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2457/consoleFull ~~(404 til Jenkins stops feeling he can't even and decides that actually he can even)~~

EDIT: again, with another specs2 project's tests disabled: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2458/consoleFull

**Comment by SethTisue** [comment]
the part of this that enables specs2 tests has now been merged onto 2.12.x as its own thing.

I rebased my `run-more-tests` branch, here's a new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2507/consoleFull (404 til Jenkins gets back from the optometrist)

**Comment by SethTisue** [comment]
the specs2 failure in run 2507 seems mysterious, and 2506 (not on this branch) had mysterious failures as well, so let's just run it again: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2509/consoleFull

**Comment by SethTisue** [comment]
run 2509: `failed: scoverage, scalacheck-shapeless, scala-gopher`

I'm pretty happy with the other results, so I'm going to declare victory and go with what we have

**Comment by dwijnand** [comment]
TIL of `executeTests`.
