### ISSUE TITLE
regression: scala-js started failing

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#662]
```
[scala-js] scala.reflect.internal.Types$TypeError: type mismatch;
[scala-js]  found   : Object
[scala-js]  required: Unit
[scala-js] 	at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1429)
[scala-js] 	at scala.tools.nsc.typechecker.Contexts$ContextReporter.issue(Contexts.scala:1281)
[scala-js] 	at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:584)
[scala-js] 	at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:106)
```

last green run:
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2522/consoleFull
* Scala: 2.12.5-bin-4bf5e52 (scala/scala@4bf5e52)
* scala-js: scala-js/scala-js@6169a651ad74c482a6fa7f0295fa3b13c04a04c9

first red run:
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2523/consoleFull
* Scala: 2.12.5-bin-707b0f3 (scala/scala@707b0f3)
* scala-js: scala-js/scala-js@6169a651ad74c482a6fa7f0295fa3b13c04a04c9

merged PRs between those two Scala versions:
* scala/scala#6154 (just documentation),
* scala/scala#6138 (override getOrElse in Map[1-4])
* scala/scala#6160 (Copy annotations to bridge methods)

**Comment by SethTisue** [comment]
the problem is reproducible outside the community build, on scala-js's master branch, with:

```
++2.12.5-bin-707b0f3
set scalacOptions in testInterface -= "-Xfatal-warnings"
testSuite/test:compile
```

@sjrd @lrytz @retronym does scala/scala#6160 seem like it might be causing this somehow...?

**Comment by sjrd** [comment]
Uh. I wouldn't be terribly surprised if https://github.com/scala/scala/pull/6160 somehow interfered with one of the uses we make of annotations to encode the JS interop semantics. In particular I'd venture a wild guess about member exports.

I will have a look tomorrow.

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js/pull/3258

**Comment by SethTisue** [comment]
```
[info] Project scala-js----------------: SUCCESS (project rebuilt ok)
```

thanks Sébastien!

**Comment by SethTisue** [comment]
scala-js/scala-js#3258 is merged onto 0.6.x now, but hasn't reached master yet. at the time we unfork we should also merge 2.11.x-jdk8 onto 2.12.x in order to get b5f6cea63ee6c11d2b9c0465dbbc1ae9a9248dce

**Comment by sjrd** [comment]
I'll set up a merge from 0.6.x to master as soon as https://github.com/scala-js/scala-js/pull/3260 is merged.

Oh and ... er ... yeah sorry about the split of `tools`. I should have foreseen that it would require some adaptations to the community build :s

**Comment by sjrd** [comment]
The fix has now reached master :)
