### ISSUE TITLE
document running local Artifactory via Homebrew

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#667]
for a long time I've been running a local Artifactory inside a Docker container, following some of @eed3si9n's instructions. but I was setting up a new laptop today and I decided to see if involving Docker was really necessary.

I found that this works (on MacOS):

    brew install artifactory
    brew services start artifactory

now Artifactory is running at http://127.0.0.1:8081

if Artifactory fails to start, it could be because you have Java 9 installed and it seems that at present, the Artifactory version Homebrew installs can't cope with that (the problem appears to be [this](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j))

but I found this can be worked around by (after `brew install` but before `brew services start`) editing `/usr/local/Cellar/artifactory/5.8.3/libexec/bin/artifactory.sh` and adding this at the top:

    export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

with that change, Artifactory starts and the config file in the repo (`artifactory/artifactory-lightbend.xml`) works just fine when loaded in the web UI via Admin -> Config Descriptor (just paste in the contents of the file). ezpz!

UPDATE: I see @lrytz has his own writeup on this at https://gist.github.com/lrytz/202aa06b0153dbd6c606fef3b6b4c713

**Comment by SethTisue** [comment]
within Lightbend I got one "I don't use Docker, and use the brew install way too" and one "For me, Docker is preferred in cases where I want to be able to swap between specific version" (not a consideration for the community build I think, I've never had an issue that depended on Artifactory version)

**Comment by SethTisue** [comment]
I've encountered another problem where every time you `brew upgrade artifactory`, it won't start up again. doesn't matter what that the two versions are. un-installing and re-installing doesn't fix it because some database files are left behind.

so my current recommendation is: after installing, use `brew pin` to stick with whatever version you have.

I thought I had it written down somewhere how this can be repaired, or at least what directory you have to blow away in order for the uninstall-and-reinstall route to work, but I can't seem to find it :-/

**Comment by SethTisue** [comment]
(oh btw I don't actually know if the Java 9 workaround described above is even necessary anymore with current Artifactory versions, I'm `brew pin`ned so I don't know)

**Comment by SethTisue** [comment]
> at least what directory you have to blow away in order for the uninstall-and-reinstall route to work

after `brew uninstall artifactory`, do `rm -rf /usr/local/var/artifactory /usr/local/Cellar/artifactory` before reinstalling

**Comment by dwijnand** [comment]
I've stuck to pinning (still on 5.1.3) and editing `/usr/local/opt/artifactory/libexec/bin/artifactory.default`.  I posted in Lukas' gist.

**Comment by dwijnand** [comment]
I think I was the "I don't use Docker, and use the brew install way too", JFYI I'm thinking of switching to Docker in the future.

**Comment by SethTisue** [comment]
the doc at https://github.com/scala/community-builds/wiki/Local-Artifactory is in reasonably good shape
