### ISSUE TITLE
regression: Scaladex frozen (won't extract)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#682]
after some recent commits by @MasseGuillaume 

```
[scaladex] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scaladex] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[scaladex] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scaladex] [warn] 	:: com.dwijnand#sbt-compat;1.1.0: not found
[scaladex] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

not sure if we need to add a resolver to our Artifactory, or what. it isn't clear to me where sbt-compat is even coming from, here (`git grep sbt-compat` in the scaladex repo shows nothing)

**Comment by SethTisue** [comment]
worked around it for now by freezing Scaladex at an older commit (e42200ee546bf92d756e34eefc1deff9c777d3c9)

**Comment by MasseGuillaume** [comment]
@SethTisue https://github.com/scalacenter/scaladex/commit/56035c71fba13366fb78fda5b21076fe9ab0ec4b#diff-a84f91f20f040218bccd09fed4761fb3 ?

**Comment by SethTisue** [comment]
@MasseGuillaume maybe? I really don't know. maybe something to do with https://github.com/sbt/sbt/issues/3393? sbt-compat is [all the way at version 1.2.4](https://github.com/dwijnand/sbt-compat/releases) these days

@jrudolph @dwijnand?

**Comment by dwijnand** [comment]
Even if sbt-compat isn't an sbt plugin it's cross-built to sbt versions so I published it to the sbt's sbt-plugin-releases ivy repo, and there are variants for version 1.1.0 for both sbt 0.13 and sbt 1:

* https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/jars/
* https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.1.0/jars/

Here's the changelog from the commit Seth froze to to the latest master commit: https://github.com/scalacenter/scaladex/compare/8f943f196179a8f5b73f1efee958ee462d5b3938...60da649ef05e3724b52d71556b76874691bf0174

It's unclear to me why every other plugin (and transitive dependency) is resolving but not sbt-compat via sbt-dependency-graph.

One possible workaround is to PR scaladex to not include sbt-dependency-graph, which I think is reasonable as it's not a plugin the build requires, it's a user utility that should be installed user-wide ("globally").

**Comment by SethTisue** [comment]
Scaladex isn't currently under active development, so I'm content to leave it frozen
