### ISSUE TITLE
fs2 started failing to compile in 2.12 build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#689]
```
[fs2] [error] /Users/tisue/community.212/target-0.9.11/project-builds/fs2-39db6ede7ef12fb3f6ceb78567d325c845b86955/core/shared/src/main/scala/fs2/async/async.scala:138:27: method shift in trait Async cannot be accessed in cats.effect.Effect[F]
[fs2] [error]     F.liftIO(F.runAsync(F.shift *> f) { _ =>
[fs2] [error]                           ^
[fs2] [error] /Users/tisue/community.212/target-0.9.11/project-builds/fs2-39db6ede7ef12fb3f6ceb78567d325c845b86955/core/shared/src/main/scala/fs2/async/async.scala:148:18: method shift in trait Async cannot be accessed in cats.effect.Effect[F]
[fs2] [error]     F.runAsync(F.shift(ec) *> fa)(f).unsafeRunSync
[fs2] [error]                  ^
```

this look like a version mismatch thing between fs2 and cats-effect rather than a Scala issue

**Comment by SethTisue** [comment]
dealt with it by freezing cats-effect at 0.9

also monix just today moved off cats-effect 0.9 onto a development version; so we have to freeze monix too

we can unfreeze all this stuff (or just move to newer tags, tags are probably better; it's hard trying to keep up with fast-evolving projects like these) once it settles down again

fyi @mpilquist @alexandru

**Comment by alexandru** [comment]
@SethTisue ouch, sorry, the upcoming cats-effect 0.10 contains some cleanups, the project being still binary compatible but not source compatible.

It's coming up next week: https://github.com/typelevel/cats-effect/milestones

**Comment by SethTisue** [comment]
> ouch, sorry

no worries, it's normal
