### ISSUE TITLE
cala spark notebook inside IntelliJ

### ISSUE THREAD

**Issue by gnanasekar6914** [scala/community-builds#691]
Hello All,

I use andypetrella/spark-notebook, and it's great:

docker run -p 9001:9001 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.7.3
However, I would like to use such a notebook from inside InteliJ to use completion and debugging. How to achieve this?

I see the IntelliJ you can have New -> jupyter, but I think it is only python. Or does it work on scala and spark?

I also see that IntelliJ has a Scala worksheet. With its experimental REPL, IntelliJ evaluates incrementally the new lines added, but it evaluates all the file from the beginning if you change a line in the middle of the file. So, not very convinient compared to a jupyter notebook.

I see other questions about running scala spark notebook inside IntelliJ, such as this one, but they do not answer the question here. How to run Spark [Scala application](https://mindmajix.com/scala-training) inside Intellij

The question is how to have the equivalent of andypetrella/spark-notebook from inside IntelliJ (so, only evaluate the lines changed)?

**Comment by SethTisue** [comment]
http://scala-lang.org/community/ has advice on where to seek help with Scala
