### ISSUE TITLE
2.13: replace macro paradise dependencies with `-Ymacro-annotations`

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#724]
this is needed to test https://github.com/scala/scala/pull/6606

**Comment by SethTisue** [comment]
me:

> adding the -Y flag is easy, removing the macro-paradise dependency without forking every project might be trickier, but I'll take a whack at it. I'll keep y'all posted

@adriaanm :

> I guess you could hack together a dummy paradise plugin that simply enables the y flag?

yeah, that's one solution I considered, but I think I can make something like `removeScalacOptions` but that operates on `libraryDependencies`. trying that first.

**Comment by SethTisue** [comment]
stab: https://github.com/SethTisue/community-builds/tree/2.13-earthly-paradise

test run: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1095/ ~~(404 while Jenkins rouses himself)~~

**Comment by adriaanm** [comment]
Jenkins is done! Not sure how to interpret the result. What are the reverse dependencies for paradise in the community build? I looked at the `---== Dependency Information ===---` section but didn't see that many projects.

**Comment by SethTisue** [comment]
the Jenkins run is good enough to confirm that this approach to testing the PR is working. I'll push my changes once https://github.com/scala/scala/pull/6606 is merged

as for what the Jenkins run tells us about the quality of the PR, I'll respond on the PR
