### ISSUE TITLE
standardize on a single metaconfig version

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#737]
it would be nice not to need separate spaces for the two metaconfig versions

over at #730 @olafurpg said he'd work on getting scalafix and scalafmt to use the same version so we could eliminate the split in the config here

**Comment by olafurpg** [comment]
I've opened https://github.com/scalameta/scalafmt/pull/1226 to upgrade scalafmt to the latest metaconfig. There were no breaking changes in v0.8, it was mostly a feature release

**Comment by SethTisue** [comment]
interesting, I wonder why I thought the split was still necessary, then. maybe a figment of my imagination

let's see how #738 does

**Comment by olafurpg** [comment]
The split was necessary until recently, I managed to upgrade scalafmt right
around scaladays Berlin.
