### ISSUE TITLE
recurring trouble with scalameter failing extraction

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#747]
finally was able to reproduce it. reported upstream at https://github.com/scalameter/scalameter/issues/204

what's less clear is the best fix/workaround. I'm tempted to blow away `~/.sbt/0.13/staging` in `run.sh`, but it's not safe to do it on a machine where multiple concurrent jobs might be running.

if we can't determine the underlying cause (and I don't plan to investigate, it isn't important enough), another workaround would be to find a way to ask dbuild not to look in `~/.sbt` at all, but to use a local directory. I sort of thought the `export HOME="$(pwd)"` in `run.sh` did that, but I guess not.

this has been such an annoying time sink that I'm pretty tempted to just shrug, drop scalameter from the community build, and just document that projects that use source dependencies, even in their build definitions, aren't eligible. having scalameter in the community build is nice, but it isn't a must-have. /cc @axel22

**Comment by axel22** [comment]
@SethTisue If this is a big problem, I could just remove the source dependency on mecha in scalameter, and use a normal one.

**Comment by SethTisue** [comment]
@axel22 that'd be nice, unless you can think of some workaround I could use

**Comment by axel22** [comment]
This commit should fix the issue.

https://github.com/scalameter/scalameter/commit/9924aad2e7cc47927e6270320d02307be07fdee3

**Comment by SethTisue** [comment]
thanks Aleks! appreciated
