### ISSUE TITLE
possible to include at least a little Scala.js stuff?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#798]
as I wrote at https://github.com/scala/bug/issues/11174 :

>> Actually is it still the case that you can't use Scala.JS in the community build?

> We've historically been reluctant to expand the scope of the community build to include the Scala.js ecosystem, not primarily for technical reasons, but primarily because the community build already consumes a lot of engineering resources so we have to be skeptical of any further expansions of scope. But perhaps we could at least include a handful of things?

/cc @sjrd @japgolly

**Comment by nafg** [comment]
Isn't it well worth it? Scala.js is a major part of the scala ecosystem nowadays.

**Comment by ngbinh** [comment]
Please do. Scala.js and scala.js react plays a vital role in our tech stack.

**Comment by SethTisue** [comment]
first stab at #799 

@nafg time and money are finite, these "worth it" judgements are extremely hard to make. it is clearly desirable, yes, there's no question. but for every thing we take on at Lightbend or the Scala Center or LAMP, there's 10 or 100 other things we can't take on that are also desirable

**Comment by SethTisue** [comment]
P.S. note that we have enough capacity on our Jenkins, that isn't the issue. so if somebody in the community wants to put together a Scala.js community build config file, to be community-maintained going forward, I'd be happy to make a Jenkins job for it, assuming the dbuild issue we're hitting at #799 can be resolved (which is unclear)

**Comment by ngbinh** [comment]
@SethTisue are there any guide on how to help to add more projects to the community build? I would love to help if I can

**Comment by SethTisue** [comment]
@ngbinh yup, lots of docs in https://github.com/scala/community-builds/wiki

**Comment by SethTisue** [comment]
see Toni's remarks at 
https://github.com/scala/community-builds/pull/799#issuecomment-429091848 about the technical feasibility and required effort level of this

**Comment by SethTisue** [comment]
some previous discussion on this at https://github.com/lightbend/dbuild/issues/193

**Comment by SethTisue** [comment]
it seems unlikely this will progress, unless new impetus comes from outside. I don't think the ticket needs to stay open

**Comment by SethTisue** [comment]
we ended up removing even Scala.js itself (see #1009), instead accomplishing equivalent testing here: https://github.com/scala-js/scala-js-test-scala-nightly

ticket on the possibility of taking that approach further: https://github.com/scala-js/scala-js-test-scala-nightly/issues/1
