### ISSUE TITLE
add metals?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#818]
@olafurpg would the new metals make sense to include?

**Comment by olafurpg** [comment]
@SethTisue I think it's best to keep it out of the CB for now, the repo is under active development and even though I'm trying to keep Scala dependencies low I can't promise new Scala dependencies won't get added in the near future.

**Comment by SethTisue** [comment]
I'm interested in revisiting this. since #1472, the cost of adding a repo like this, with many dependencies, has dropped a lot

cc @tgodzik — thought prompted by https://github.com/scala/scala/pull/10148 — ideally these sorts of things would be caught by the community build
