### ISSUE TITLE
2.13 dropping symbol literals

### ISSUE THREAD

**Issue by ashawley** [scala/community-builds#824]
I have a branch of Scala 2.13 that drops symbol literals:

https://github.com/scala/scala/pull/7499

There's a proposal to deprecate symbol literals in 2.13, but not to drop them.  So this is just an exploratory branch with no intent to merge in 2.13.  

In preparation for dropping after 2.13, would it be possible to see what this branch breaks in the community build? I predict since ScalaTest uses symbols and is a root dependency in the ecosystem, that not much of the question would be answered, but I figure it's worth a shot of letting the community build explode once and then inspecting the wreckage for clues.

Also, the branch introduces a new symbol shorthand syntax (`sym"foo"`), see https://github.com/scala/scala/pull/7495, which no projects will be using, but it would will be good to have community build double-duty check if it introduces problems.

**Comment by SethTisue** [comment]
(I'll respond after my December vacation)

**Comment by ashawley** [comment]
Happy vacationing!

**Comment by ashawley** [comment]
Closing in favor of #827.
