### ISSUE TITLE
2.12: akka-http-session and akka-http-cors are failing

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#825]
in both cases the error is `java.lang.ClassNotFoundException: akka.testkit.package$TestDuration$`

akka-http-session is a leaf project. we can try again after https://github.com/softwaremill/akka-http-session/pull/63 is merged

akka-http-cors is a dependency of sttp. we can try again after https://github.com/lomigmegard/akka-http-cors/pull/41 is merged

perhaps we moved to a too-new akka-http in c1e7bb720d876954d94207939b3367ae2c6f9f5c and we need to back up a little bit, if moving the other repos to newer versions doesn't do the trick

it's not urgent since only 3 projects total are affected.

**Comment by SethTisue** [comment]
this is sorted now, both those PRs were merged, and we're tracking master for the relevant projects

```
configs/project-refs.conf:  akka-http-cors-uri:           "https://github.com/lomigmegard/akka-http-cors.git"
configs/project-refs.conf:  akka-http-session-uri:        "https://github.com/softwaremill/akka-http-session.git"
configs/project-refs.conf:  akka-http-uri:                "https://github.com/akka/akka-http.git"
```

**Comment by SethTisue** [comment]
@poohsen not sure what you mean or what you're referring to

**Comment by poohsen** [comment]
Nvm, this was non-sense
