### ISSUE TITLE
build compiler bridge independently of the rest of zinc/sbt

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#842]
reference: https://github.com/scala/scala-dev/issues/602

I'm thinking that it shouldn't fall only on scala-dist-smoketest to catch this, the community build ought to be catching it too. the community build includes sbt, but sbt has a ton of dependencies and hasn't been ported to 2.13 yet. the community build ought to build the compiler bridge by itself. I'll look into it.

ah, actually the community build does catch it, when compiling any project at all:

```
[scala-xml:error] /var/folders/j1/sv5gcszx0tn0t_q5xr58v1q40000gn/T/sbt_a8a36df5/xsbt/ExtractAPI.scala:334: error: value isLocal is not a member of ExtractAPI.this.global.Symbol
[scala-xml:error]       !(s.isPrivate && (s.privateWithin == NoSymbol || s.isLocal))
[scala-xml:error]                                                          ^
er, actually not any project at all, an sbt 1 project compiled, it's an sbt 0.13.x project that broke. hmm.
```

ah, only the older bridge uses the removed API.

**Comment by SethTisue** [comment]
so the community build does catch this, but I still feel that I'd feel safer if we built both bridges, the 0.13 and the 1.0 bridges, directly.

**Comment by SethTisue** [comment]
working on this. I get a warm fuzzy feeling from:

```
[info] Project compiler-bridge-1-0
[info]   depends on: cloc-plugin, scala, scalacheck, scalatest
[info] Project compiler-bridge-0-13
[info]   depends on: cloc-plugin, scala
```

as compared to

```
[info] Project zinc
[info]   depends on: acyclic, catalysts, cats, cloc-plugin, discipline, expecty, export-hook, fansi, fastparse, geny, gigahorse, jawn-0-10, json4s, kind-projector, machinist, macro-compat, macro-paradise, metaconfig, minitest, paiges, portable-scala-reflect, pprint, sbinary, sbt-io, sbt-librarymanagement, sbt-util, scala, scala-js-stubs, scala-parser-combinators, scalacheck, scalafmt, scalameta, scalapb, scalatags, scalatest, scopt, shaded-scalajson, shapeless, simulacrum, sjson-new, sourcecode, specs2, spray-json, ssl-config, unfiltered, utest, wartremover
[info] Project sbt
[info]   depends on: acyclic, catalysts, cats, cloc-plugin, discipline, expecty, export-hook, fansi, fastparse, geny, gigahorse, jawn-0-10, json4s, kind-projector, machinist, macro-compat, macro-paradise, metaconfig, minitest, paiges, portable-scala-reflect, pprint, sbinary, sbt-io, sbt-librarymanagement, sbt-util, scala, scala-js-stubs, scala-parser-combinators, scalacheck, scalafmt, scalameta, scalapb, scalatags, scalatest, scopt, shaded-scalajson, shapeless, simulacrum, sjson-new, sourcecode, specs2, spray-json, ssl-config, unfiltered, utest, wartremover, zinc
```

**Comment by SethTisue** [comment]
fyi @eed3si9n

**Comment by smarter** [comment]
(we just rewrote the dotty compiler bridge in Java which avoids this problem and a bunch of other issues: https://github.com/lampepfl/dotty/pull/5596, that's easier in dotty than in scalac because most of the logic that was in the bridge was moved into the compiler: https://github.com/lampepfl/dotty/tree/master/compiler/src/dotty/tools/dotc/sbt)

**Comment by SethTisue** [comment]
keeping this open until I merge it onto 2.13.x

**Comment by SethTisue** [comment]
during dependency extraction on 2.13.x, 

```
[compiler-bridge-0-13] scala.MatchError: 2.13.0-pre-caf0db9 (of class java.lang.String)
[compiler-bridge-0-13] 	at NightlyPlugin$$anonfun$projectSettings$1.apply(NightlyPlugin.scala:35)
[compiler-bridge-0-13] 	at NightlyPlugin$$anonfun$projectSettings$1.apply(NightlyPlugin.scala:34)
[compiler-bridge-0-13] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[compiler-bridge-0-13] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[compiler-bridge-0-13] 	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
[compiler-bridge-0-13] 	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
[compiler-bridge-0-13] 	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
[compiler-bridge-0-13] 	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
[compiler-bridge-0-13] 	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
[compiler-bridge-0-13] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[compiler-bridge-0-13] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[compiler-bridge-0-13] 	at java.lang.Thread.run(Thread.java:748)
```

looks like I might need to submit a little patch to the 0.13 branch of sbt in order to get around this

**Comment by SethTisue** [comment]
> looks like I might need to submit a little patch to the 0.13 branch of sbt

I added it to https://github.com/sbt/sbt/pull/4518 . so we're not waiting, it's also now in the community-build-2.12 branch of the scalacommunitybuild fork

so that gets it extracting. still leaving this open until it doesn't just extract, but is actually green

**Comment by SethTisue** [comment]
it isn't green on 2.13, in local testing I see a bunch of compile errors, for example:

```
[compiler-bridge-0-13] [error] trait FileFilter extends java.io.FileFilter with NotNull {
[compiler-bridge-0-13] [error]                                                  ^
[compiler-bridge-0-13] [error] /Users/tisue/community.213/target-0.9.16/project-builds/compiler-bridge-0-13-1c4041e671f1e364cf169d7b625c9afa4210cd53/util/io/src/main/scala/sbt/NameFilter.scala:25: not found: type NotNull
[compiler-bridge-0-13] [error] trait NameFilter extends FileFilter with NotNull {
[compiler-bridge-0-13] [error]                                          ^
```

but this looks like we're building more code than just the compiler bridge.

**Comment by SethTisue** [comment]
the problem is in `compileInterfaceProj`. we definitely want to include that, it contains the source file that prompted this ticket.

the problem seems to be that `compileInterfaceProj` has test-only dependencies that bring in code we don't want to compile in this context:

```
  dependsOn(interfaceProj % "compile;test->test", ioProj % "test->test", logProj % "test->test", /*launchProj % "test->test",*/ apiProj % "test->test").
```

**Comment by SethTisue** [comment]
gah. this is getting difficult. `compileInterfaceProj` isn't the first reason this failing (or maybe isn't a reason at all)

the first reason it's failing is that `interfaceProj` has a `sourceGenerators` setting that uses `fullClasspath in Compile in datatypeProj`, and then `datatypeProj` pulls in `ioProj` and `controlProj`. none of this is actually part of the compiler bridge and shouldn't be expected to compile on 2.13

**Comment by SethTisue** [comment]
gah. starting to feel like maybe this is a boondoggle and I should just forget about it, and back out the work I already did, too. I'll ponder further

**Comment by SethTisue** [comment]
> gah. starting to feel like maybe this is a boondoggle and I should just forget about it, and back out the work I already did, too. I'll ponder further

removed everything in 86832b96d4787a5e0c5a36df4b452884ddffc502

maybe I'll come back to this, idk
