### ISSUE TITLE
add more playframework/* and lagom/* repos, more Lagom projects?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#846]
the following seem like candidates:

Play

* https://github.com/playframework/play-slick
* https://github.com/playframework/anorm
* https://github.com/playframework/play-grpc
* https://github.com/playframework/play-iteratees
* https://github.com/playframework/play-scala-starter-example

Lagom (repos)

* https://github.com/lagom/online-auction-scala
* https://github.com/lagom/lagom-scala-grpc-example

@marcospereira @dwijnand thoughts? I could try just tossing all of these in there and see what happens

as for Lagom subprojects, we don't currently build: api-javadsl, api-tools, broker-javadsl, build-tool-support, cassandra-server, client-javadsl, cluster-javadsl, dev-environment, devmode-scaladsl, immutables, integration-client-javadsl, integration-tests-javadsl, integration-tests-scaladsl, jackson, kafka-broker, kafka-broker-javadsl, kafka-broker-scaladsl, kafka-client, kafka-client-javadsl, kafka-client-scaladsl, kafka-server, log4j2, maven-dependencies, maven-java-archetype, maven-launcher, maven-plugin, persistence-cassandra-javadsl, persistence-javadsl, persistence-jdbc-javadsl, persistence-jpa-javadsl, play-integration-javadsl, pubsub-javadsl, pubsub-scaladsl, reloadable-server, sbt-build-tool-support, sbt-plugin, sbt-scripted-library, sbt-scripted-tools, server-javadsl, service-locator, service-registration-javadsl, service-registry-client-core, service-registry-client-javadsl, testkit-javadsl

not sure which of these might be candidates for adding.

**Comment by dwijnand** [comment]
cc @renatocaval @ignasi35 for those lagom projects

**Comment by marcospereira** [comment]
You may also include:

- https://github.com/playframework/scalatestplus-play/

Or is it there already? :-)

**Comment by SethTisue** [comment]
omnidoc seems like another likely candidate.

(note to self, note the omnidoc exclusion in play-webgoat)

**Comment by ignasi35** [comment]
> as for Lagom subprojects, we don't currently build: api-javadsl, api-tools, broker-javadsl, ...

@SethTisue I'm not familiar with the setup or how the build works, but [IIUC](https://github.com/scala/community-builds/blob/2.12.x/configs/community.dbuild#L1638
), _only_ `"server"` and `"testkit-scaladsl"` are being referenced but all its dependenceies will be built, is that correct?

`testkit-scaladsl` and `server` together depend on almost all the `scaladsl` projects, if not all. There's scala code on the `javadsl` projects but I think it's fine for the time being.

![projects-graph](https://user-images.githubusercontent.com/762126/52124086-6c5b9780-2628-11e9-9ca0-fa2081046f4d.png)

**Comment by SethTisue** [comment]
candidate: https://github.com/lagom/shopping-cart-scala

**Comment by SethTisue** [comment]
> only "server" and "testkit-scaladsl" are being referenced but all its dependenceies will be built, is that correct

@ignasi35 right

**Comment by SethTisue** [comment]
https://github.com/lightbend/play-meta/pull/35 refreshes the list of Play and Lagom repos out there

**Comment by SethTisue** [comment]
and https://github.com/lagom/shopping-cart-java — wouldn't be a bad idea to include some application-level Java code consuming Scala-based stuff

**Comment by SethTisue** [comment]
currently working on unfreezing Lagom and adding Lagom sample apps over at #869

**Comment by SethTisue** [comment]
closing, as it's a very open-ended ticket and I don't currently have a clear directive to pursue this further.

Lagom is unfrozen on 2.12, but is failing in 2.13 for now, but I don't think it makes sense to pursue until it's on Akka 2.6 (see #963, which remains open)

Lagom samples app PR remains open and will hopefully still progress.

**Comment by SethTisue** [comment]
I gave up on the Lagom samples app PR (#950)
