### ISSUE TITLE
SSL error scala-ci.typesafe.com

### ISSUE THREAD

**Issue by ashawley** [scala/community-builds#857]
Running the 2.13 build on Java 8, I'm getting this error when trying to retrieve dependencies:

```
Caught
javax.net.ssl.SSLHandshakeException:
sun.security.validator.ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to
find valid certification path to requested target
(sun.security.validator.ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to
find valid certification path to requested target) while downloading
https://scala-ci.typesafe.com/artifactory/dbuild/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom
```

From what I read, it might be a Let's Encrypt! certificate issue.  My laptop is old and I only have the free version of Oracle's JDK, so maybe it's just me.

**Comment by ashawley** [comment]
Looks like you ran in to this with as well with JDK6 in #836.  

I did something similar and just added [the intermediate certificate for Let's Encrypt](https://letsencrypt.org/certificates/#intermediate-certificates).

```
curl https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt > lets-encrypt-x3-cross-signed.cer
sudo keytool -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts \
             -storepass changeit -noprompt -importcert -file lets-encrypt-x3-cross-signed.cer
```

**Comment by SethTisue** [comment]
fwiw, I have not had to mess with certificate stuff on any Java 8+ JVMs. if you find that the issue can be resolved by using a newer Java 8 release, then I think we could close the ticket.

**Comment by ashawley** [comment]
Ok, good to know.  Yeah, it was probably just me.  I was using `jdk1.8.0_40.jdk`.
