### ISSUE TITLE
Add ZIO & Scalaz to community builds

### ISSUE THREAD

**Issue by jdegoes** [scala/community-builds#896]
I was recently made aware of the fact that in a [single unreviewed commit](https://github.com/scala/community-builds/commit/be8d3f07832c78044a65d3840a9338dc05943af7), ZIO and Scalaz were unilaterally removed from the community build.

As far as I can tell, no explanation has been provided, just a commit message that I personally find quite cryptic (_CoC-incompatible_ ?). Moreover, I cannot find any discussion of this decision, nor evidence that the decision comes from pre-existing policies and procedures, which has left me very confused about what is going on.

As someone who works on and recommends both Typelevel and Scalaz projects, and has worked toward a unified functional Scala community, I find this move quite disheartening.

I am very grateful for all the community build has done to improve stability of the Scala compiler, and I'm delighted that Typelevel projects are included in the build.

I believe that including Scalaz and ZIO in the build has tremendous value for the community, because these projects (mostly Scalaz) are widely deployed in industry; and both push the compiler in their own distinct ways, exploring different combinations of Scala features.

In light of all this, I would like to ask: **What have ZIO or Scalaz done to get them removed from the community build?** 

And more importantly: _how can we **all** work together to get them back on the community build, where they will help to ensure the stability of the Scala compiler, and benefit the entire Scala community?_

Thank you for your time and consideration!

**Comment by nmcb** [comment]
If we are going to have the CoC compliancy discussion at all, please let that (future) CoC be phrased in terms of actions and not intentions. As for the originating action to the commit removing scalaz projects, I am not aware of _any_ action taken by the scalaz community that was against an agreed upon CoC. If any, I would like to know of agreed upon due processes regarding decisions to allow and remove "community" members as I consider myself one, and for that one with a 10 year investment in and professional dependency on Scala and its community as a whole. I intent to value that investment in the future as much as I have in the past.

**Comment by SethTisue** [comment]
see https://contributors.scala-lang.org/t/coc-compatible-community-builds/3097

**Comment by SethTisue** [comment]
the linked thread has become extremely long, but this recent addition is especially relevant: https://contributors.scala-lang.org/t/coc-compatible-community-builds/3097/245
