### ISSUE TITLE
projects are moving to Fastparse 2

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#897]
which is hard because it isn't remotely source-compatible with Fastparse 1

this is timely because right now is an important time to be testing on Scala 2.13, but if a project's 2.13 support is landing in a branch that also requires Fastparse 2, we have a problem

perhaps this can be addressed with splitting the build into spaces

or perhaps we could keep everything in the same space, but use dbuild to publish Fastparse 1 and 2 under different org and/or artifacts, and then override the dependency downstream accordingly

**Comment by SethTisue** [comment]
this might be easier than I feared. eyeballing the config, it appears that fastparse is used by:

* coursier, scalatex, scala-xml-quote: these are leaf projects
* scalapb, scalameta (and scalapb may be a leaf other than being used in scalameta)

I can't tell just from eyeballing whether there are any projects that are downstream of scalapb and/or scalameta that might also use fastparse directly. but I do know that nobody uses scalapb who doesn't also use scalameta.

but in any case, anything downstream of scalameta is fairly leaf-ish, capstone stuff rather than fundamental stuff.

and anyway, I recently discovered over in the 2.13 build that scalameta is using a shaded version of fastparse 1, so we ought to be able to just add the repo with the shaded version to the build, and everything will be hunky dory! 🤞 probably any fastparse-1-using project will be able to use the shaded one too

**Comment by SethTisue** [comment]
there's some question of whether I can track scalameta master, or whether I need to stick with the one I have. but I would probably be able to use the shaded version of fastparse 1 regardless

https://github.com/scala/community-builds/pull/910 was an attempt to move the 2.13 build to scalameta master; perhaps the difficulties I ran into there were 2.13-specific

/cc @olafurpg

**Comment by SethTisue** [comment]
the fastparse repo still has an sbt build in it, but presumably the mill build is the main build these days?

**Comment by SethTisue** [comment]
the fastparse repo doesn't have a proper sbt build anymore, there is a `build.sbt`, but it is vestigial and doesn't actually build the main code

**Comment by SethTisue** [comment]
perhaps I should start by just fetching fastparse 2 from Maven Central, get everything working, and then worry about whether it's necessary to actually build it ourselves

**Comment by SethTisue** [comment]
PR #915

**Comment by olafurpg** [comment]
The Scalameta fork of Fastparse is identical to Fastparse v1 except that the code lives in the `scala.meta.internal.fastparse` package instead of toplevel `fastparse` package. User source code needs to be manually rewritten to use that namespace in order to use the fork.

**Comment by SethTisue** [comment]
in 2.13.x land, #946, which will be merged soon, fixes this by including both fastparse 2 (using an sbt build I artisanally handcrafted) and the scalameta fork of fastparse 1

in 2.12.x, I'm content to leave things as they are, freezing projects as needed
