### ISSUE TITLE
Subsume akka-more

### ISSUE THREAD

**Issue by dwijnand** [scala/community-builds#899]
The comment above akka-more says:

>   // this is separate from "akka" because there is a circular dependency between
>   // the akka and ssl-config repos. and also just so failures in obscure subprojects
>   // don't take out too much of the build

The circular dependency isn't there any more (AFAICT).  So is it work merging them back together, or should it be kept for the second reason?

**Comment by SethTisue** [comment]
86855a32a24fa924c801f99f7a3654d3ef06f2d1

**Comment by dwijnand** [comment]
Perhaps it's fine or perhaps it's not intended, but it's strange to run Akka's "classic" actor tests, but not the typed ones, but still compile the akka-actor-typed (in the "akka" dbuild project).

Also perhaps "akka-more" could have a more explicit name: at first I thought it was some extension of Akka I wasn't aware of (like commercial addons/enhancements).

**Comment by SethTisue** [comment]
> Perhaps it's fine or perhaps it's not intended, but it's strange to run Akka's "classic" actor tests, but not the typed ones, but still compile the akka-actor-typed (in the "akka" dbuild project).

yeah idk, it could go either way, it's maybe a bit strange, but it could also fall under "because it takes a long time to build and run the tests, and so failures in obscure subprojects don't take out too much of the build", if we figure that the plain actor tests are enough to verify that Akka isn't completely broken

> Also perhaps "akka-more" could have a more explicit name: at first I thought it was some extension of Akka I wasn't aware of (like commercial addons/enhancements)

hmm... "akka-remainder"? "akka-full"?

**Comment by dwijnand** [comment]
"akka-rest-of-the-owl"

But actually it sounds like it would be a major enhancement in dbuild if it wired between projects.  So a downstream project to akka-actor wasn't cut off from running due to a flaky akka-streams test.
