### ISSUE TITLE
remove all uses of `check-missing: false`

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#903]
I've been doing this wrong.

in 2.12.x, this has been resulting in binaries being retrieved from Maven Central instead of dbuild-built ones being used (e.g. for kind-projector)

in 2.13.x, it just doesn't work at all (because Maven Central doesn't have matching binaries), which is how the problem turned up

this will take some work to make the change build-wide

**Comment by SethTisue** [comment]
closing in favor of #914

**Comment by dwijnand** [comment]
JFYI you can change an issue into a pull-request by using the `-i` flag in hub's `pull-request`. https://hub.github.com/hub-pull-request.1.html

**Comment by SethTisue** [comment]
oh, does that still work? I had thought they removed that capability

**Comment by dwijnand** [comment]
Yeah, it was gone but it was brought back (a few months ago).  Not sure why.
