### ISSUE TITLE
Switch akka-persistence-cassandra to older version

### ISSUE THREAD

**Issue by dwijnand** [scala/community-builds#904]
The community build (using the 2.13 one as reference) akka-persistence-cassandra (APC) is present as it is a dependency of Lagom.  However, it's building on APC 0.85, while real Lagom uses APC 0.61.

For some background context, there was a jump in versioning from 0.59 to 0.80, with 0.60/0.61 being on a separate branch.  Oh and latest APC is 0.96.

**Comment by SethTisue** [comment]
will you be PRing this yourself, coming out of your recent Lagom-in-the-community-build work, or is it I something I should look at myself...?

**Comment by dwijnand** [comment]
I'm not sure what strategy to use.  I'm not sure how to min-max here, i.e. minimise the time spent and maximise the improvement.  I could push the web of branches I used to build up Lagom on RC1, but maybe that'll be too many changes.

Also, how does PRing changes work?  I see no PR validation.  Do I test locally first, then open a PR, then verify on Jenkins and leave a comment?  Or would you rather hand-review and selectively test PR changes?

**Comment by SethTisue** [comment]
>  I see no PR validation

the lack of PR validation is https://github.com/scala/scala-jenkins-infra/issues/92

> Do I test locally first, then open a PR, then verify on Jenkins and leave a comment? Or would you rather hand-review and selectively test PR changes?

well, it depends, I guess. I don't always test locally first, sometimes I just go straight to Jenkins. but yeah, whatever you do, just leave a comment on the PR so it's clear what the status is.

**Comment by SethTisue** [comment]
@dwijnand do you plan on returning this soon? if not, I would prefer that the ticket be closed, and be replaced with a comment in the config file explaining the situation

**Comment by dwijnand** [comment]
Let's close it.  Lagom master is moving to APC 0.98 which is much better (there's a more ambitious 1.x, but Lagom 1.6 won't be migrating to it).
