### ISSUE TITLE
behemoths are running low on disk space

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#905]
in the last couple weeks especially, but also in recent months generally, the behemoths sometimes run out of disk space. between community build runs, 80-100GB is free, but during runs, we're running out of space

the community build's temporary disk space requirements are *really* high. during a run, a ton of space is used which ends up being freed up again at the end

so usually the community build fixes itself simply by running it again; because previous successfully built projects will be cached, the next run's temporary space requirements are much less

but, we can't really afford for community build disk space issues to randomly cause scala/scala PR validation failures

**Comment by SethTisue** [comment]
Adriaan has been disabling the JDK11 and/or JDK12 jobs as a temporary measure

**Comment by cunei** [comment]
@SethTisue I have a commit in a devel branch of dbuild that allows the user to specify as cleanup time "-1", which means each successful extraction or build dir is deleted immediately after completion, rather than at the end: https://github.com/lightbend/dbuild/pull/221/commits/644481ed2c779c4727ed91f954df094e65d4ca2c
I could cut a beta release of dbuild which includes the latest changes, for your testing from: https://github.com/lightbend/dbuild/pull/221
Please let me know if you'd like to try that path.

**Comment by SethTisue** [comment]
I haven't had time to try @cunei's build yet :-/

we got through the 2.13.0 release frenzy without running out of space by disabling some less essential jobs (JDK 6, 11, 12) and (important!) clearing their workspaces. I have since re-enabled some but not all of the jobs; I'll probably re-enable the JDK 12 ones in July. (the JDK 6 one can stay permanently disabled, there is no point anymore.)

another thing that I've been doing that's been helping is: whenever I bump the Scala SHA on any of the three branches (2.11.x, 2.12.x, 2.13.x), I wipe out that branch's workspaces. that really helps a lot, especially during periods when SHA bumps are frequent.

**Comment by cunei** [comment]
![image](https://user-images.githubusercontent.com/686260/59642017-b7072780-9163-11e9-8709-116d19d5546f.png)
```
$ bin/dbuild --help
Typesafe dbuild 0.9.17-toni22   (176ed360b8a2)
```
([info](https://github.com/lightbend/dbuild/commit/644481ed2c779c4727ed91f954df094e65d4ca2c#diff-8f90661ddc4840debe6dffbf6c4ef3e5R1023))

**Comment by SethTisue** [comment]
closing, since the main difficulty here was resolved by clearing the workspaces whenever I bump the Scala SHA

as for trying Toni's dbuild beta, I split that off as #970
