### ISSUE TITLE
json4s tests in community build?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#911]
@xuwei-k at https://twitter.com/not_xuwei_k/status/1130817276310151169 you write:

> Json4s has long been part of Community Build, bu it seems like it hasn't been running all of the tests for a while. why...?

you can advise me on how we might improve this? the project's entry is:

```
  json4s-uri:                   "https://github.com/json4s/json4s.git#3.6"

  // 3.6 is the current stable branch (as of March 2019);                                                               
  // there is also a development branch                                                                                 
  ${vars.base} {
    name: "json4s"
    uri:  ${vars.uris.json4s-uri}
    // TODO: exclude subprojects we don't want, rather than naming a few we want. probably adding more would work?      
    extra.projects: ["json4s-native", "json4s-jackson", "json4s-ast"]
  }
```

**Comment by xuwei-k** [comment]
FYI, json4s-tests subproject depens on scalaz 😇 

https://github.com/json4s/json4s/blob/6d9ceb1ed4cbf6457f11e40553826b4d42103d3c/build.sbt#L103-L115

**Comment by SethTisue** [comment]
workaround for missing scalaz: https://github.com/scalacommunitybuild/json4s/commit/ddfaa0bb65c9904b1670ee6b2a6ed4abc90ae084

**Comment by SethTisue** [comment]
thanks for calling this to my attention!

afaict, there's no particular reason I'd never tackled this before

**Comment by SethTisue** [comment]
green in 2.13 as well, `[info] Project json4s----------------------: SUCCESS (project rebuilt ok)`
