### ISSUE TITLE
regression: play-ws failing (joda-time related)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#912]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4531/

```
[play-ws] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/play-ws-2d6c0f0f06fac969b30d0e0e6fba7bf067b9643a/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/cache/AhcHttpCache.scala:75:81: type mismatch;
[play-ws] [error]  found   : org.joda.time.DateTime
[play-ws] [error]  required: java.time.ZonedDateTime
[play-ws] [error]         val expiredEntry = entry.copy(expiresAt = Some(HttpDate.fromEpochSeconds(0)))
[play-ws] [error]                                                                                 ^
```

@dwijnand can you guide me on whether I should freeze play-ws at an older version, or move some dependency of play-ws to a newer version, or what?

**Comment by dwijnand** [comment]
I fixed that in https://github.com/playframework/play-ws/pull/350.  So just need to be using master play-json and master play-ws.  But then play might break (and downstream).  So you might want to pin back until I've finished climbing this dependency tree (FML).

**Comment by SethTisue** [comment]
well, at least there's plenty of other monkeys up in this tree to keep us company :-)

**Comment by SethTisue** [comment]
pursuing this now as part of #1008
