### ISSUE TITLE
Any reason scalamock is not pointing to https://github.com/paulbutcher/ScalaMock ?

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#922]
Any reason scalamock is not pointing to https://github.com/paulbutcher/ScalaMock ?

_Originally posted by @Philippus in https://github.com/scala/scala-dev/issues/563#issuecomment-496222471_

**Comment by SethTisue** [comment]
says 2.12.x configs/community.build:

```
-  // frozen (November 2017) at June 2017 commit, for compatibility with
-  // github4s which depends on the older version.  we might also consider
-  // forking github4s and/or contributing the needed change upstream
-  // forked (October 2018) to apply JDK 11 patch
```

I haven't checked recently whether this still applies.

and in any case, in the 2.13.x branch we make these judgment calls differently. if a base project lands 2.13 support, we move to that branch, and if downstream projects like github4s break, so be it.

I see that in the 2.13.x build scalamock is blocking 3 downstream projects, so I guess we should move to scalamock master there.

**Comment by SethTisue** [comment]
on 2.13.x, as of f04284dd24d4d8a1d51a87b751d78262b7cc6569 we are now tracking scalamock master `[info] Project scalamock-------------------: SUCCESS (project rebuilt ok)` 👍 

(on 2.12.x it's okay to stay forked, for now or even indefinitely)
