### ISSUE TITLE
Subprojects run all tests

### ISSUE THREAD

**Issue by eatkins** [scala/community-builds#924]
I am testing a new sbt version and noticed that when dbuild was checking sbt itself that it seems to be running `test` without scoping to the subproject. For instance, in the sbt build, I will see something in the logs like: `Processing subproject: commandProj ` and then, below that, I'll see the output of ParserSpec, which is in the mainProj subproject. This makes the sbt dbuild take forever since it reruns all of the tests for every subproject (running all of the tests takes at least a minute and a half and there are 22 subprojects).

I don't know enough  about dbuild to know if this is intentional or not, but it feels like the community build could run a lot faster if the commands it ran were scoped to the subproject it was validating (i.e. run `commandProj/test` instead of `test`).

**Comment by eatkins** [comment]
I now see that this may be specific to the sbt dbuild configuration which has this line:
`extra.test-tasks: ["safeUnitTests"]`
which is a custom sbt command that runs all of the tests in the entire build.

**Comment by SethTisue** [comment]
@eed3si9n @eatkins can you suggest (or even PR) a fix?

**Comment by SethTisue** [comment]
I dealt with the immediate performance problem (thank you @eatkins, I've very glad to have this noticed and reported!) in the linked commit. @eed3si9n up to you if there's a need to do anything else here. (if I start having problems with flaky tests I'll disable them individually.)
