### ISSUE TITLE
explore the possibility of supporting Dotty

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#927]
this is only one possible path forward for building community projects on Dotty; the overarching ticket is https://github.com/lampepfl/dotty/issues/6708

I'm hoping that we can adjust the "scala" section of the config file to pull Dotty JARs using either, set the Scala version to 0.16.0-RC3 or what have you, and go. maybe dbuild will blow up. if that happens @cunei can advise us on whether we're stymied, or what.

* WIP branch: https://github.com/scala/community-builds/tree/dotty
* Jenkins job: https://scala-ci.typesafe.com/view/dotty/job/dotty-dbuild/

**Comment by SethTisue** [comment]
one obstacle I already see coming is that we need the included projects to have sbt-dotty plugin.

we have not previously attempted to inject an sbt plugin into every build. there's a ticket on that at https://github.com/scala/community-builds/issues/553. Toni has specific advice on what to try at https://github.com/scala/community-builds/issues/553#issuecomment-305484145

fortunately, automatically injecting the sbt-dotty plugin isn't a hard requirement for getting started. we can PR the addition of the plugin to repos we care about, and/or just do the addition in our own forks (in our personal forks when experimenting is fine; under the `scalacommunitybuild` organization is better for anything that we expect to keep) and point the config file here to those forks.

scala-xml and ScalaTest are two repos I know of that already have Dotty in their cross-builds; we could start with those. (@liufengyun what ScalaTest branch would we use and where does it live?)

**Comment by liufengyun** [comment]
@SethTisue The branch `3.1.x` https://github.com/scalatest/scalatest/tree/3.1.x has Dotty support.

We run the following SBT commands to run the test set of ScalaTest:

```
scalacticTestDotty/test;scalatestTestDotty/test
```

**Comment by liufengyun** [comment]
@SethTisue The branch `3.1.x` https://github.com/scalatest/scalatest/tree/3.1.x has Dotty support.

We run the following SBT commands to run the test set of ScalaTest:

```
scalacticTestDotty/test;scalatestTestDotty/test
```

**Comment by SethTisue** [comment]
progress so far: to set the Scala version for all projects, in the community build we normal use dbuild's `assemble` build system, which has hardcoded expectations about scala-library.jar

our choices here:
* patch dbuild to allow `dotty-library` instead?
* figure out how to do without the `scala` build system

it seems to me that we shouldn't need `assemble` to assemble a scala for us, that was mainly used historically when Scala 2 still had its own dependencies (scala-xml, scala-parser-combinators). let's try just controlling it with `extra.settings: ["scalaVersion := ..."]` or some such.

**Comment by liufengyun** [comment]
@SethTisue we have a version of `scala-library`, which seems can be used for the purpose:

```Scala
  // Depend on dotty-library so that sbt projects using dotty automatically
  // depend on the dotty-library
  lazy val `scala-library` = project.
    dependsOn(`dotty-library-bootstrapped`).
    settings(commonDummySettings).
    settings(
      // Need a direct dependency on the real scala-library even though we indirectly
      // depend on it via dotty-library, because sbt may rewrite dependencies
      // (see https://github.com/sbt/sbt/pull/2634), but won't rewrite the direct
      // dependencies of scala-library (see https://github.com/sbt/sbt/pull/2897)
      libraryDependencies += "org.scala-lang" % "scala-library" % scalacVersion
    )
```

https://github.com/lampepfl/dotty/blob/0a67182e84c577575a181af95732e970054fc9a9/project/Build.scala#L979-L990

**Comment by SethTisue** [comment]
the scala-library check in dbuild hardcodes `l.info.organization == "org.scala-lang"`, but of course that would be easy to patch

but we can disable the check with `cross-version: disabled`, but I'm not sure what the implications of that are in this case. I'll keep experimenting

**Comment by SethTisue** [comment]
(I'm out of time to mess with this any further until July)

**Comment by liufengyun** [comment]
Thanks a lot @SethTisue 👍  I'll spend some time to get familiar with the relevant tools and think about the alternatives too.

Have a nice holiday !

**Comment by SethTisue** [comment]
oh, I forgot to say: I had a local run that actually built scala-xml, generated doc, and ran the tests. I thought that I'd pushed that config to GitHub, but it seems not because the same thing didn't happen in the Jenkins run. oh well, I'll get back to it...

**Comment by SethTisue** [comment]
closing since the dbuild-based option isn't currently moving forward. we can always reopen if it starts moving again. the broader ticket remains https://github.com/lampepfl/dotty/issues/6708

**Comment by SethTisue** [comment]
> one obstacle I already see coming is that we need the included projects to have sbt-dotty plugin

as of sbt 1.5.0-M1, sbt-dotty's functionality has been folded into sbt itself, so this is no longer an issue.

I first need to make sure that sbt 1.5.0-M1 works with dbuild at all, even for Scala 2. Assuming there's no problem there (probably there won't be), then I could re-try my previous experiment with Scala 3 and see what happens.
