### ISSUE TITLE
Remove references to sbt-idea

### ISSUE THREAD

**Issue by gkossakowski** [scala/community-builds#93]
According to mpeltonen/sbt-idea#327 the `sbt-idea` plugin looks abandoned. That's not a big deal because IntelliJ imports Scala project natively now.

We should get rid of sbt-idea project from community build. However, we can do that only once all projects defined community build drop their references to sbt-idea plugin.

This ticket is created for tracking progress on this.

**Comment by retronym** [comment]
Play has removed the dependency https://github.com/playframework/playframework/pull/4108

**Comment by SethTisue** [comment]
we don't build sbt plugins anymore, so this is now n/a
