### ISSUE TITLE
Add Alpakka Kafka

### ISSUE THREAD

**Issue by ennru** [scala/community-builds#932]
Alpakka Kafka https://github.com/akka/alpakka-kafka/ (aka akka-stream-kafka) could be included it builds for both 2.12.8 and 2.13.0 (by excluding a few tests that need an embedded Kafka broker).

Lagom depends on Alpakka Kafka (relevant for #846)

**Comment by SethTisue** [comment]
let's tackle this!

**Comment by SethTisue** [comment]
let's discuss the gory details on the new PR, #969
