### ISSUE TITLE
move to scalameta master (or v4.2.0 tag) and enable `testsJVM`

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#936]
see https://github.com/scala/community-builds/issues/935 for background

> move to scalameta 4.2.0 with `testsJVM` enabled (making or requesting any needed fixes), scalafmt master, and then if scalafix breaks as a result, just remove or disable it until @olafurpg (or whoever) has moved it to scalameta 4.2.0 as well

**Comment by SethTisue** [comment]
this is currently blocked because scalameta master uses a version of scalapb that depends on fastparse 2

scalameta still uses fastparse 1 internally, but it uses a shaded version that we can retrieve with aether, so we won't have a fastparse 1 vs 2 conflict, but adding fastparse 2 is still work. (it's #897)

**Comment by olafurpg** [comment]
See scalameta/fastparse for the manually shaded version of fastparse v1. It might be possible to add it to the community build since the package name doesn’t conflict with fastparse v2.

**Comment by SethTisue** [comment]
wip on this at #946

**Comment by SethTisue** [comment]
#946 fixes this on 2.13.x and will be merged soon

in 2.12-land, I think I'm content to leave things where they are.
