### ISSUE TITLE
Unfreeze airframe

### ISSUE THREAD

**Issue by xerial** [scala/community-builds#956]
@SethTisue 

I've fixed the cyclic dependency issue of airframe in https://github.com/wvlet/airframe/pull/592, by making Airspec (a new testing framework, which depends on airframe's code itself) a standalone project.

I think the latest master branch of airframe fixed the issue of https://github.com/scala/community-builds/commit/31459b014e49b2333bf51bc7d884baa481a3ab1c

Thank you for reporting this issue. This helped the restructuring of the project settings.

**Comment by SethTisue** [comment]
thanks for letting me know
