### ISSUE TITLE
we are wildly overcounting LOC, there are not 15 million lines

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#961]
LOL `15155450 TOTAL`. not!

not sure when this started, I'll have to look at the history of how cloc-plugin is getting added

here's an example log excerpt from one of the overcounted projects, showing the same numbers being repeated

```
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
[specs2] ** COMMUNITY BUILD LINE COUNT: 920
[specs2] [info] Done compiling.
[specs2] [info] Compiling 154 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/classes ...
[specs2] [info] Main Scala API documentation to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/api...
[specs2] ** COMMUNITY BUILD LINE COUNT: 8640
[specs2] model contains 577 documentable templates
[specs2] [info] Done compiling.
[specs2] [info] Main Scala API documentation successful.
[specs2] Running "test" in: commonJVM
[specs2] [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
[specs2] ** COMMUNITY BUILD LINE COUNT: 920
[specs2] [info] Done compiling.
[specs2] [info] Compiling 154 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/classes ...
[specs2] ** COMMUNITY BUILD LINE COUNT: 8640
[specs2] [info] Done compiling.
[specs2] [info] Compiling 1 Scala source to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/test-classes ...
[specs2] ** COMMUNITY BUILD LINE COUNT: 22
[specs2] [info] Done compiling.
[specs2] Publishing: commonJVM
[specs2] [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
[specs2] ** COMMUNITY BUILD LINE COUNT: 920
```

**Comment by SethTisue** [comment]
looking at some of the obviously over-counted projects:

```
  4327548 akka-more
   991553 twitter-util
   765342 akka-http
   448319 specs2
```

I suspect the common denominator is "build has lots of subprojects"

**Comment by smarter** [comment]
How about dropping cloc-plugin ?

**Comment by SethTisue** [comment]
well, the line counts are useful for publicity, and this was working before, it probably just needs a little tweak

but you're right that it might make sense to just drop it, and run it again every 6 months or so to get updated counts, come blogging time

it was added in the first place partly as an exercise in seeing whether we could inject a compiler plugin into every project, something we thought we'd have other use cases for (e.g. testing scala-fortify), but I think we can consider that experimental successfully concluded; it has never caused any trouble

**Comment by smarter** [comment]
Honestly I think at this point you could just say "millions of lines of code" and leave it at that, humans can barely comprehend such numbers anyway :).

**Comment by SethTisue** [comment]
I haven't said so yet, but one of the reasons the overcounting concerns me is that in the above transcript, it isn't just the `LINE COUNT` lines that are repeated, there's also these repeated lines:

```
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
[specs2] [info] Compiling 154 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/classes ...
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
[specs2] [info] Compiling 154 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/common/jvm/target/scala-2.12/classes ...
[specs2] [info] Compiling 15 Scala sources to /Users/tisue/community.212/target-0.9.16/project-builds/specs2-dc3ebe5cea3b6dbb97dfd6a54519995518e90f25/fp/jvm/target/scala-2.12/classes ...
```

which seems to indicate that we're compiling the same sources over and over again. I'd like to get to the bottom of that: is it sbt? dbuild? or what? does it happen even when cloc-plugin is removed? and so on

perhaps cloc-plugin is just causing trouble.... but maybe it's actually helped us here by calling attention to a problem that we might not have noticed otherwise

**Comment by SethTisue** [comment]
an example of a zero-dependency project (easy to do testing on) that's affected is scala-parser-combinators

the overcompilation still happens even if I remove cloc-plugin entirely from the config file

the overcompilation stops if I downgrade from sbt 1.3.0-RC3 to sbt 1.2.8. (downgrading to 1.3.0-RC2 or RC1 does not help.)

so that narrows it down. it's either an sbt regression, or a latent dbuild issue that sbt 1.3 has somehow uncovered

looking closely at the logs, the extra compilation happens when the `publish` command is issued — that's when sbt decides it needs to recompile the stuff it already compiled when it ran `test`

**Comment by SethTisue** [comment]
minimal(-ish?) config file at https://github.com/SethTisue/community-builds/blob/overcount/configs/community.dbuild

**Comment by SethTisue** [comment]
hmm, the problem isn't specific to `publish`:

if I run sbt in the dbuild debugging environment, with commands such as:

```
./dbuild-0.9.16/bin/dbuild checkout 861647e644cbd1ece7039aa834f043189849628b scala-parser-combinators  newdir
./newdir/.dbuild/start
```

then do `project scala-parser-combinators` and run `compile` twice in a row, the second time everything is recompiled — it should be a no-op

enabling `debug`, every time we run `compile` we see:

```
[debug] Modified binary dependencies: Set(/Users/tisue/community.212/newdir/.dbuild/scala/d17810cf691d3aed3352a2ad17a5abf6dba26418/lib/scala-library.jar)
```

followed by full recompilation. that copy of `scala-library.jar` isn't actually changing, neither its contents nor its timestamp

@eed3si9n is this enough digging to get you to the point where you have some glimmer of what might be going on or what I should try next?

**Comment by SethTisue** [comment]
dbuild isn't monkeying with scala-library.jar:

```
% sum ...
20514 5560 /Users/tisue/community.212/newdir/.dbuild/scala/a9e8b19c7d6c7cab415dfcf2a5eb0d3536bd04f8/lib/scala-library.jar
20514 5560 /usr/local/scala/scala-2.13.0/lib/scala-library.jar
```

**Comment by SethTisue** [comment]
I wonder about https://github.com/sbt/sbt/commit/25e97f99f588d1ddc9bbd114740bfb25c2a955c6#diff-324c154efade6a91675ce59c16db4b9d (part of https://github.com/sbt/sbt/pull/4335) /cc @eatkins

(conceivably related: https://github.com/sbt/sbt/pull/4679 — it seems that nobody ever figured out _why_ `rt.jar` was being invalidated, and just excluded it)

**Comment by eed3si9n** [comment]
I'll escalate this to an issue on sbt/sbt.

**Comment by SethTisue** [comment]
sbt fix incoming!!! https://github.com/sbt/sbt/pull/4949

**Comment by eatkins** [comment]
I think the sbt fix will also fix some of the projects like playframework and circe that had to be pinned to 1.2.8.

**Comment by SethTisue** [comment]
when RC4 comes out, I will retest every project that was pinned to 1.2.8

**Comment by SethTisue** [comment]
using scala-parser-combinators as my test repo, I verified that 1.3.0-RC4 fixes the problem. 1.2.8 and 1.3.0-RC4 both give a line count of `2202 scala-parser-combinators`, where 1.3.0-RC3 gave `4600 scala-parser-combinators`

**Comment by SethTisue** [comment]
> when RC4 comes out, I will retest every project that was pinned to 1.2.8

this in process now, beginning with https://github.com/scala/community-builds/commit/0b65e06cd9712fab0dfbe66437cd3038517df848 (which I'll revert pieces of as needed, e.g. https://github.com/scala/community-builds/commit/d5d87f582d56ae145e650260bf1def0296e195e6)

UPDATE: ticket is #966
