### ISSUE TITLE
2.13: move to Akka 2.6, revive Lagom

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#963]
Lagom's 2.13 support is on their master branch where they have also moved to Akka 2.6. the CB is still on Akka 2.5

(it's true that we had Lagom on 2.13 green here for a while, but that was using a special branch, I don't see any value in continuing with that)

at some point we could/should move everything forward to Akka 2.6, but I think attempting to do so now would likely not have good cost/benefit. maybe once 2.6 is in RCs would be good timing? I could coordinate with the Akka and Play/Lagom teams

(likely the 2.12 build should stay on Akka 2.5 and Lagom 1.5 forever)

fyi @patriknw @dwijnand

**Comment by SethTisue** [comment]
@dwijnand is it time yet?

**Comment by dwijnand** [comment]
At the very least not until https://github.com/lagom/lagom/pull/2350 (which upgrades and fixes a source-incompatible change with M7).  There might be similar breakages in Akka's RC1, but I'm not sure (upgrading tomorrow).

**Comment by SethTisue** [comment]
@dwijnand I see Lagom 1.6.0-RC1 is out; is now the right time?

**Comment by dwijnand** [comment]
Yep!

**Comment by SethTisue** [comment]
pursuing this now at https://github.com/scala/community-build/pull/1008

**Comment by SethTisue** [comment]
done
