### ISSUE TITLE
push sbt 1.3.0-RC4 upgrade through

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#966]
including re-testing all projects that failed on RC3

/cc @eed3si9n @eatkins

**Comment by SethTisue** [comment]
this is now done on 2.12 as of https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4923/

the full list of projects that didn't work on RC4 is:

* fs2 (worked on RC3)
* genjavadoc
* scala-js
* blaze
* sbt-io, sbt-util, sbt-librarymanagement (very old versions)
* sttp
* tsec

Error details are in comments in https://github.com/scala/community-builds/blob/2.12.x/configs/community.dbuild

I'm working on pushing the change through the 2.11 and 2.13 builds.

**Comment by eatkins** [comment]
I think sttp will pass with -Dsbt.classloader.close=false. We should probably bump the sbt pinned versions to something more recent. The tsec tests passed when I ran them locally so it may have just been a flaky test or something about the community build. The genjavadoc tests worked for me with 2.12.8 but failed in the same way the community build did with 2.13.0.

**Comment by SethTisue** [comment]
> I think sttp will pass with -Dsbt.classloader.close=false

let's find out! https://github.com/scala/community-builds/pull/968 (UPDATE: green, merged)

> We should probably bump the sbt pinned versions to something more recent

I think the 1.3.0 release would be a good opportunity for that, but I'm hoping @eed3si9n will tackle it for me :-)

**Comment by SethTisue** [comment]
on 2.13, scala-parallel-collections weirdness: f09999ddaccdf659f3758a0bf573d90daf9d8c50
